### ISSUE TITLE
Trace viewer needs a javascript and testing style guide

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#1172]
Trace viewer has lots of coding conventions that live in the heads of its developers. Those coding conventions should be written down so that new contributors can avoid common pitfalls in contributing.

A few example topics might include:

  - Which ES6 features are okay to use?
  - Are `<!-- @fileoverview -->` blocks necessary in every file?
  - Are `@constructor` blocks necessary for every constructor?
  - Do you need to specify an include when it's already being imported transitively through another file?
  - Is testing private methods okay?

**Comment by zeptonaut** [comment]
As suggested by @dj2:

  - The class name should match the filename
  - Each file should only contain one class

The style guide will be under construction here: https://docs.google.com/a/google.com/document/d/1cD1hUhYnMQ9AlxdL_OAftrQXBKlcgbLJiwmHVEug268/edit?usp=sharing

**Comment by egonelbre** [comment]
Rather than writing a style guide, automatic formatting and checking is better. If you switch between projects it's easy to mix up different styles; with style guides you still end up looking rules or making mistakes. Something like http://editorconfig.org/ would be easiest to start with and there should be some formatter as well, e.g. js-beautify.

**Comment by petrcermak** [comment]
I think it would be ideal if we could use <tt>git cl format</tt>.

**Comment by dj2** [comment]
I don't think we need lay out in stone the answers to those questions. A quick round of review for a first Cl will answer many of them, and, honestly, I think only the filename matching contents one I've seen in code review.

**Comment by zeptonaut** [comment]
@egonelbre For linter warnings, I definitely agree. There are some style guidelines that can't be linted for, though. For example, one style no-no that will be included in the style guide is to omit a `@fileoverview` block if it's obvious:

```html
<!-- @fileoverview A time range is a range of time. -->
```

This is something that would be really difficult to write a linter for, but is still bad.

**Comment by dj2** [comment]
I'm not sure why the fileoverview is bad. It's redundant, sure, but it doesn't hurt anything, it doesn't make the code slower.

**Comment by zeptonaut** [comment]
I'm definitely not saying it's the *worst* thing in the world. Redundancy is something we should avoid if possible, though.

**Comment by natduca** [comment]
This is a really tough subject area, because everyone feels that they are a stakeholder, and it can very easily become a rathole. Lets keep in mind that we have some really urgent deliverables for Q3 and that this can really easily snowball if unchecked.

The reason I support work here is because we're onboarding a pretty large number of people into our tracing codebase. Right now, the onboarding process involves slightly-more-than-average surprises during codereview where unwritten conventions are discovered. I support reducing the surprises here by writing down things. But this is about doing a *minimal bit* of work to help improve folks comfort with the code: for Q3, there is an upper bound on that investment, because Google culture is pretty clear that coders should be good at following the convention of neighbor code in face of convention ambiguities. For Q4 we can revisit and see if we have some systematic code convention issues that require higher investment levels.

An implication of this "upper bound" rationale is that while we should *always* prefer and be writing presubmits, linters, and formatters, we shouldn't be actively diverting primary eng assignments to writing them. If folks wanna do it in their 20% time, thats great, though: for instance, Annie wrote a great presubmit checker for presubmit BUG= formatting. But, that is a background activity. We can revisit the priority in Q4 once we know the scale of the problems: with data, better choices can be made.


So, backing up: for now, we wanna focus on this guide being about making onboarding a bit easier. As such, I'd suggest we put our effort on discovering as a team what is clearly agreed upon but unwritten, what is ambiguous but unwritten. And, of course, getting those written down.

And, since we're just trying to help improve onboarding, we should punt on changes to convention. Where we have ambiguities or dissagreements, oh well! :) Lets write it down if appropriate, and move on. In Q4 we can discuss whether we wanna do something about it.

For instance, fileoverview is not something we agree upon. Okay. We don't agree. Write down & punt. Next topic!

Hope this guidance helps!

**Comment by zeptonaut** [comment]
Just wanted to chime in and say that I definitely agree. I think this is something that's valuable to have for now to help onboard people, and to help bring to light competing approaches. I think that "there are multiple ways to do this" is a perfectly acceptable resolution for now, though, given much the team has on its plate.

**Comment by zeptonaut** [comment]
I updated the doc some more - let me know if there's anything else that you think it needs before adding it to the CONTRIBUTING file and wiki page.

**Comment by natduca** [comment]
@zeptonaut how do we finish this bug out so we can close it?

**Comment by zeptonaut** [comment]
I went ahead and added the trace viewer style guide to the CONTRIBUTING.md doc (with a note that it's only for trace viewer) and also the "contributing" section of the "trace viewer getting started" wiki article. I'm going to close this now if you don't have any object, but I'd be happy to add it anywhere else that you feel like it'd be useful to have.
