### ISSUE TITLE
@sourceURL annotation doesn't work when the parse fails

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1215]
During loading, if you have a file that has a typo in it, then you get an undefined filename in the error that results.

I wonder if this is endemic to eval, or something that can be fixed with putting the sourceURL at the front of the file?

**Comment by natduca** [comment]
@nedn i did a quick experiment and it seems like moving sourceURL doesn't do anything. So maybe there's no real fix possible without d8 exposing a module lading api?

**Comment by paulirish** [comment]
fwiw, `@ sourceURL` is now `# sourceURL`. Don't know if the character change would fix things for ya.

**Comment by nedn** [comment]
I also encountered this.
@ sourceURL has to be put at the top to work in parsing failure case. But that will increase increase all the line number by 1. A trick I have been thinking about is insert it at the top if we have blank lines there (which we do majority of the time due to <HTML...> <--! Chromium...> lines). A bit gross but I think could be ok?

Also there is this issue: https://code.google.com/p/v8/issues/detail?id=4364

**Comment by natduca** [comment]
That seems promising. Maybe if it fails to find a gap, we fall back to appending?

**Comment by nedn** [comment]
Yeah, that's the plan.

**Comment by nedn** [comment]
Feel free to reopen if you think this is not fixed. It also turns out that  https://code.google.com/p/v8/issues/detail?id=4364 is issue on mac, but not linux.

**Comment by natduca** [comment]
Thanks Ned!
