### ISSUE TITLE
Initial dev-server unification steps

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1237]
0) In each project's x_build folder,  (bikeshed0
1) Move dev_Server and its tests up to build/
2) Introduce PerProjectDevServer class, that provides
- AddOptionsToGroup(argparse_group): adds cmdline options to provided argparse group (https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.add_argument_group)
- GetHandlers(options) -> [wsgi route tuples] , where options is all results of argparse
- GetSourcePaths() -> []
3) dev_server has hard coded list of project dev servers

I suggest option 2 of a devserver class because the GetHandlers and AddOptionsToGroup are specific to the devserver use case. We could add them to the project, but then the:
1) the project would take on a dependency on wsgi/webapp2 for all uses of the project
2) the project file would get big... it is not a module, but a toplevel file, x_project.py, whereas if we put the per-project devserver stuffs in x_build, we can have class-per-handler were needed

I suggest we keep the per-project tests.html  for v1, which means that the test handlers are in the perproject parts of the devservers. And, the / redirects would point to some index.html that would let you pick which tests.html to jump to. We might do differetnly down the road , but this'd be a baby step.

**Comment by natduca** [comment]
@anniesullie fyi

**Comment by anniesullie** [comment]
I started looking at this and had a bunch of questions:

* It seems like at least in this version, if you are working on perf_insights and tracing at the same time you'd have two dev_servers running, right? Or does the server automatically add a path for the handlers listed in GetHandlers() for each project, so that all the tracing ones are /tracing/...?
* If there are multiple servers being run, how does the dev_server pick between its hard-coded list of project dev servers? I was assuming an argument, but then we need to parse arguments to do that, and we can't provide an argparse group to just the specified project (unless we just have the arguments added for all of them? Then arguments have to be unique across projects, right?)
* It sounds like PerProjectDevServer would ideally be a base class implemented by each project. So the base class would be in a separate module, living in build/, and the per-project classes would import it? (worried about cyclic imports)
* What's the command line used to run the tracing dev server? Is it still tracing/bin/run_dev_server, or is it bin/run_dev_server <some arguments>?

**Comment by anniesullie** [comment]
Oh, another question: Right now the handlers individually do what they need with the source paths. Would having a separate GetHandlers(options) and GetSourcePaths() mean that we are pulling some shared handler code which deals with source paths into build/dev_server?

**Comment by natduca** [comment]
It seems like the basic misunderstanding here is that there'd be multiple dev servers. Rather, there'd be only one dev server, one dev server script. bin/run_dev_server for instance, that imports build/ and calls main. The master dev server would hard code the list of per-project servers and directly include them.

dev_server.py would be

def Main():
```
add tracing, dash, perf_insights to sys.path
from tracing_build import tracing_dev_server
from perf_insights_build import perf_insights_dev_server
... dashboard here in the future
pds = [tracing_dev_server.TracingDevServer(), perf_insights_dev_server.PerfInsightsDevServer()];

argparse = as before
argparse.add_option(--port)
for pd in pds:
  g = argparse.AddOptionsGroup(pd.__class__.__name__)
  pd.AddOptionstToArgParseGroup(g)
args = argparse.parse_args(argv[1:])

app = CreateApp(args, pds)
... wsgi run with app as usual...
```

CreatApp(args, pds)
```
routes = []
.. add redirects to /tests.html 
... add TestsHandler(defaultData: pds) so that /test.html points at the different per-project tests.htmls
.. add test routes first, those are common, e.g. the test tests_completed handlers
for pd in pds:
  routes += pd.GetRoutes(args)

source_paths = []
for pd in pds:
  source_paths += pd.GetSourcePaths(args)

routes += [ SourceHandler for the source_paths]
return routes
```

The individual "servers" just add in their routes, and provide their paths. Their routes are:
- their test listing handlers, e.g. tracing/tests and perf_insights/tests
- their test_data folders (tracing is skp_data and test_data, perf insights is test data)


If this is to vague, I'm happy to do this tonight. My teammmates are having a hard time working with the two devservers.

**Comment by anniesullie** [comment]
I understand what you mean now, but with meetings and first-time-implementing slowness I might not have it fully done until Friday. I've got a fully tested CL up for fixing the code duplication when running dev_server tests here: https://codereview.chromium.org/1283333002/

If you need this done faster, feel free to assign yourself, and also feel free to break off any smaller pieces you see and assign to me.

**Comment by anniesullie** [comment]
I updated https://codereview.chromium.org/1285333002/
