### ISSUE TITLE
Appengine-compatible way for projects to reference other projects

### ISSUE THREAD

**Issue by fmeawad** [catapult-project/catapult#1246]
In #1122, we set up a pathing strategy where appengine app.yaml for project "x" are in x/x.yaml, its python code is x/x/__init__.py. And, other projects are siblings to x, e.g. y projects python code is in y/y/__init__.py 

The issue #1244 showed that Appengine doesn't support referencing above x/. This makes reaching other catapult projects impossible.

We will need a plan for proceeding here, eventually.

+@anniesullie +@natduca

**Comment by natduca** [comment]
@anniesullie though #1122 is closed, we still have this outstanding issue. I'm not so clear how we want to proceed here.

**Comment by fmeawad** [comment]
I discussed this with @qeny, he seemed to have solved it for the dashboard component by doing 2 tricks:
<ul><li>adding an <a href="https://cloud.google.com/appengine/docs/python/tools/appengineconfig">appengine_config.py</a> file
<li>Adding a <a href="https://github.com/catapult-project/catapult/blob/master/dashboard/third_party">symlink</a> to the anything above app.yaml beside app.yaml
</u>

**Comment by natduca** [comment]
Do we want to have symlinks in our checked in repo layout? Seems pretty funky...

**Comment by natduca** [comment]
Or put another way, maybe if we go that way, we should have the app.yaml in a subfolder called appengine/app.yaml, and then anything it needs is symlinked in from there.

that way, things running in non-appengine mode don't have multiple ways to get to a given asset in our repo]

**Comment by dj2** [comment]
Symlinks aren't portable, they don't work on Windows for example.

**Comment by anniesullie** [comment]
@qeny - How does the perf dashboard work on Windows? I see that the tests pass, does the dev_server run? Can you deploy to prod?

I haven't looked at this too deeply at all, but maybe simlinks in a 'lib' directory? https://cloud.google.com/appengine/docs/python/tools/libraries27#vendoring

**Comment by qeny** [comment]
I haven't tried deploying perf dashboard (deploying or using dev_appserver) on Windows, and I expect that it doesn't work. The tests pass on Windows only because the third-party libraries added to sys.path in a different way when running the tests vs in production. (Specifically: when running tests, libraries are added to sys.path in run_tests.py, but for deploying or dev_appserver, they're added using vendor.add in appengine_config.py.)

There is another possible way to solve this problem: The deploy script could copy the code and third-party libraries to a temp directory and then deploy from there.

Pros:
 - Don't need any funky symlinks.
 - All required third-party libraries could be copied into the same directory as app.yaml in the temp directory, so there's no need to call vendor.add in appengine_config.py to set up sys.path.
 - We probably want to do this for dashboard anyway, since we want to generate vulcanized template HTML files and (ideally) versioned static files -- all of this requires making new temporary files/directories just for deploying.

Cons:
 - Can't run dev_appserver.py directly, have to run it through a script that copies everything over then runs it on the temp directory.
 - When debugging locally, one would have to modify files in the temp directory, not the real catapult directory. (Need to have a clear README saying how to debug locally).

**Comment by natduca** [comment]
A specific deploy step might give us a clean way to slot in stuff like vulcanizing, right?

Is there a way to have a deploy step that creates symlinks in the build image for quick turn development?

**Comment by anniesullie** [comment]
I think a deploy script is the way to go. Quinten, can you investigate if there's a way to have a deploy step that creates symlinks as in Nat's comment?

**Comment by qyearsley** [comment]
Tomorrow I plan to make a CL to change catapult/dashboard/deploy.sh to do this, and then when that works we can do the same thing for perf_insights :-)

**Comment by natduca** [comment]
Can we plan on moving from shell script to python for the deploy at some point? sh is known for being unmaintainable.

**Comment by qyearsley** [comment]
Sounds good!

**Comment by anniesullie** [comment]
@qyearsley - Can you work on making deploy.sh and the unit tests work without symlinks? I got confused a few times between third_party and dashboard_third_party myself, but after #1283 I see this has the potential to really be a time sink.

**Comment by qyearsley** [comment]
Alright -- now we can include code from other parts of catapult when deploying and running dev_appserver by using the new build/appengine_deploy.py and build/appengine_dev_server.py modules, which take a list of required files/directories for deployment and makes a temp directory with them in it.

(Now it only uses symlinks so for windows support we'll have to change those to copy instead of symlink on windows.)
