### ISSUE TITLE
Memory-infra trace w/ lot of renderers looks misaligned

### ISSUE THREAD

**Issue by primiano** [catapult-project/catapult#1251]
Got a trace from android (www/~primiano/memory_infra/traces/trace_misaligned_android.json) with 3 dumps (lot of renderers).
The graphs in the renderers look temporally misaligned. See below. Is this WAI?

![regr](https://cloud.githubusercontent.com/assets/7137473/9245162/93853c5c-4199-11e5-817f-d1cb54f57cf0.png)

**Comment by natduca** [comment]
can we put a trace around the dumping operation so we can see how heavy the dumping was?

**Comment by petrcermak** [comment]
This is **WAI**. I wrote a script to find the ranges of each dump in the JSON trace and got the following results:

```
Event count: 398
Memory dump count: 44
=== Dump 0xaf56544c85eaee75 (15 process dumps) ===
min: 0.00
max: 1.12

=== Dump 0xaf56544c85eaee73 (15 process dumps) ===
min: 1.15
max: 1.51

=== Dump 0xaf56544c85eaee7d (14 process dumps) ===
min: 2.01
max: 3.05
```

As you can see, the three global dumps do not overlap, but they are quite "wide" (there is more than one second delay between the first and last process dump in two cases).

Since there are no global memory dumps in raw JSON traces, we create them during import and assign them the *timestamp of the first process memory dump* with the given dump ID. This has the following impact on the visual alignment of dumps in the timeline:

![93853c5c-4199-11e5-817f-d1cb54f57cf0](https://cloud.githubusercontent.com/assets/2546601/9246587/8215a492-41a4-11e5-928a-bd20a936b4e9.png)

Maybe the solution would be to indicate the range of global memory dumps in the track at the top (using something like a slice).

Note that you can see when the dumping occurred in each process by enabling high details in Trace Viewer (press 'h').

**Comment by primiano** [comment]
> can we put a trace around the dumping operation so we can see how heavy the dumping was?
Yep I have already a patch for that (https://codereview.chromium.org/1188803003/) we can apply locally and retry.

OK I suspect that what happens here is that the 1st dump is heavy (w/ mmaps) and there are lot of processes here (14-15 IIRC). The thing that I don't understand, though, is why there is so much variability between the various processes. 
Will find out tracing memory-infra :)

Thanks for the thorough explanation

**Comment by petrcermak** [comment]
@primiano: Gentle ping (this bug hasn't been updated for 6 months).

**Comment by primiano** [comment]
OH I definitely did put async slices with flow events connections around memory-infra events, so now they are all traced. I think that the result of the analysis is that sometimes (during scrolling etc) the threads are busy and there isn't much we can do other than PostTask.
We have debugging info to figure out what took long, and we are being as smart as we can when posting, so I think there isn't anything left to do on this bug.
