### ISSUE TITLE
Rename tracing/third_party/tvcm to third_party/py_vulcanize and focus it on vulcanizing

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1266]
- Its name is wonky. Rename it to py_vulcanize
- It is mostly a vulcanizer now, but it also has things that should be presubmit checks

**Comment by qyearsley** [comment]
One first sub-task I can see here is to remove test_runner.py from tvcm. `tvcm.test_runner` is currently used by `perf_insights_build/run_py_tests.py` and `tracing_build/run_py_tests.py`. Those two scripts could be changed to use `catapult_build/run_py_tests.py` instead, and any functionality in `tvcm/test_runner.py` could be incorporated into that.

**Comment by natduca** [comment]
That seems good except that i'd like to extract tvcm to its own github project over time. So, I'd prefer that tvcm not have a dependency up to catapult_build.

I believe we were planning on moving all our test running to typ? @nedn

**Comment by nedn** [comment]
Yes. Not only typ supports test parallelization, it also has other neat features like supporting json output for test results, etc..
@dpranke

**Comment by natduca** [comment]
Yeah, so probably the right plan for this [inasmuch as "right" is even possible] is probably for us to move  all users of the tvcm test runner, including tvcm, over to tvp. Then separately, we'd move tvcm out to third_party py_vulcanize

**Comment by qyearsley** [comment]
typ is https://github.com/dpranke/typ, right? Are we planning to add a copy to catapult/third_party?

Would it be OK to first make all of the Python test running scripts use catapult/catapult_build/run_py_tests.py (https://github.com/catapult-project/catapult/issues/1478) and then make that script use typ after typ is added to catapult?

**Comment by dpranke** [comment]
Yes, typ is https://github.com/dpranke/typ .

As an aside, you can always pull typ in via DEPS or git submodules (typ from here on github or via googlesource.com), but it looks like for now you're checking third party stuff in directly rather than using DEPS or submodules, right?

If there's interest, I can always produce a release of typ that is a smaller subset of files than the full repo as well.

**Comment by qyearsley** [comment]
Right; currently all other third party code is checked in directly to third_party with a README.chromium file, so I'd expect we'd probably do the same with typ.

Generating a release that is a subset of the files in the repo sounds good, but probably not necessary since typ is small (less than 500KB).

**Comment by qyearsley** [comment]
I'm planning to upload a CL to do this this week.
