### ISSUE TITLE
Trace viewer examples path seems wrong.

### ISSUE THREAD

**Issue by dj2** [catapult-project/catapult#1271]
Currently, to access the example trace_viewer the URL is /examples/trace_viewer.html. I think this should be /tracing/examples/trace_viewer.html now that we've moved to a global dev server.

**Comment by anniesullie** [comment]
I started looking into this and if I understand the request correctly, it's a really large change. I have a WIP here:

https://codereview.chromium.org/1300653003

The actual code change is in https://codereview.chromium.org/1300653003/diff/1/build/dev_server.py - I thought we could fix this by just always prefixing files served through SourcePathsHandler with the project name they came from (i.e. /tracing/examples/trace_viewer.html is '/tracing' + '/examples/trace_viewer.html'). But then all the test.html pages failed to load, because all the paths need to be changed on the imports, so I did that, but then it ends up being quite verbose and of course tvcm fails because it doesn't recognize the paths.

@natduca - sorry for not catching this earlier, what do you think is the best thing to do here? Right now, we're just assuming there are no duplicate paths from the source paths the projects pass in.

**Comment by anniesullie** [comment]
Oh, looks like this is covered in the doc https://docs.google.com/document/d/1clC4bV_3aNc-z3L9WmGswjYtOco0udxmJhVjeugIP04/edit#:

"HTML search paths are arranged such that they have the same name as they would in python. E.g. tracing/tracing/base/base.html is /tracing/base/base.html for an HTML import, and tracing/tracing/base/base.py is 'tracing.base.base' in Python."

So I should update all the paths, as I started in this CL, right?

**Comment by dj2** [comment]
None of the paths should be /tracing/tracing. The path is /tracing/base/base.html which matches the tracing.base.base. We should not have /tracing/tracing/base/base.html as a path.

**Comment by natduca** [comment]
I think all you need to do is tweak tracingdevserverconfig should return an extra test_data_paths = "/tracing/examples" -> self.project.examples_path

We might also have to update the tracing/tracing/tests.html to point at the right url , but that should be it.

**Comment by anniesullie** [comment]
Thanks! Much simpler patch uploaded at https://codereview.chromium.org/1300813004/
