### ISSUE TITLE
run_dev_server lost the -d flag.

### ISSUE THREAD

**Issue by dj2** [catapult-project/catapult#1273]
The tracing dev server used to allow passing -d <directory> to change the test_dir. This was useful for things like measuremt-traces when you had a directory of files you wanted to use.

This does not seem to work with the global dev_server anymore.

**Comment by anniesullie** [comment]
I made a change to add -d (and -s) back in here: https://codereview.chromium.org/1294203002

But I realized I don't know how to test it. Suggestions?

**Comment by natduca** [comment]
This probably is p1 because folks use this so that they can do local development using the traces in https://github.com/natduca/measurmt-traces instead of the ones checked in.

In the medium term, we need to decide whether we're okay with +250mb of binary trace data checked into our main repo, or if we want to use gclient or cloud storage or etc

**Comment by anniesullie** [comment]
Thanks! I uploaded another patch I think does the right thing.
