### ISSUE TITLE
Make it easier to deploy private instances of the trace upload server

### ISSUE THREAD

**Issue by dstockwell** [catapult-project/catapult#1305]
`‘performance-insights’` is hard coded as the bucket name in https://github.com/catapult-project/catapult/blob/master/perf_insights/perf_insights/upload.py#L35

But most people setting up appengine instances would prefer to use the default bucket: `app_identity.get_default_gcs_bucket_name()`

**Comment by fmeawad** [comment]
Originally the project was using get_default_gcs_bucket_name, but when I migrated the project from deep reports to perf_insights, there was no easy way to import the default bucket for that project.
So I decided to decouple the bucket and the appengine.

I will look into how to make a decoupled bucket work as the default one for a project or allow for configuring the bucket name in a different way without having to change the code.

**Comment by anniesullie** [comment]
Maybe we could configure this in the deploy script somehow? @qyearsley

**Comment by qyearsley** [comment]
If this were configured in the deploy script, there are several ways to do it:
 1. The deploy script could write a plain config file (JSON or YAML) which is marked as static and [application_readable](http://stackoverflow.com/questions/2630205/read-a-file-on-app-engine-with-python) in app.yaml. Then upload.py can could read that file.
 2. Similarly, the deploy script could write a Python file which just contains `BUCKET_NAME = 'performance-insights'`. This could then be imported by upload.py.

I think using a Python file for config seems more hacky, but I'm not sure why. What do you all think?

Note: another related thing that the deploy script could do would be to  use a versioned name for the static files directory; this would involve writing a config file and reading it in a handler (so that it can be used in Jinja templates).

**Comment by fmeawad** [comment]
I have added a variable in os.environ that can be configured in app.yaml, if removed it will use the default instance as discussed in the original bug description, thanks for reporting.
