### ISSUE TITLE
Pull MVP pieces together into a PI Demo

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1337]
The plan:
https://docs.google.com/document/d/1mX743HJELD7JmCpAYtkDYiL0Fc4rWOWVjiZJYhrI4_s/edit#heading=h.b27l48qaofqa

**Comment by natduca** [comment]
#1258 may be useful

**Comment by dj2** [comment]
Also needs #1335 for the rail report.

**Comment by benshayden** [comment]
What should the rail score visualization look like?

The histogram is cool, but doesn't seem like it's going to produce any insights on its own.
I can imagine a few different directions we might want to explore.

One is this tree-table Explorer:
https://x20web.corp.google.com/~benjhayden/1312783006.png
https://codereview.chromium.org/1312783006
It sorts so that the low-scoring traces, IRs, sub-scores (joy=1-pain, efficiency), and WorkGroups bubble up for attention. It's definitely a Small Data thing, but it might be a good starting point for finding examples of problems that can we can then write code to detect automatically.

I could plot pain on one axis and efficiency on the other, and plot dots or a heatmap for imperfect IRs. This would be more of a Mid-size Data thing to help us get a feel for the shape of the corpus and how the definitions of pain and efficiency play out in a real corpus and whether we want to change them, but would not necessarily lead straight towards any insights about web performance.

We could use scores as a behind-the-scenes filter for other analysis -- take all the IRs in the corpus with score < 0.5 and do some math (waves hands). I could figure out how much Response pain is directly attributable to which ad networks. I could figure out what kinds of work (script/style/layout/etc.) contributes the most to slow or janky animations. Visually, these would just be tables of names and numbers.

What kinds of analysis do you want to see that requires rail scores?

**Comment by dj2** [comment]
@natduca @benshayden @philippebeaudoin have been driving this forward, changing the assignee to @natduca.
