### ISSUE TITLE
Easy to send too-long URL graphing data stoppage alerts

### ISSUE THREAD

**Issue by rschoen** [catapult-project/catapult#1408]
https://chromeperf.appspot.com/alerts

I currently have 11 data stoppage alerts. Checking 9 of them and then clicking "Graph" results in:

Error: Bad Request

Your client has issued a malformed or illegal request.

I'm assuming it's because the URL is too long.

**Comment by qyearsley** [comment]
That's correct -- this is a consequence of the fact that the datastore keys for stoppage alerts are long (since they contain the test path), so the urlsafe version of the key is also super long, so even less than 10 alerts makes the URL too long.

Possible next actions:
 * When clicking "Graph", check the length of the URI and lop off some part of the query parameter so it's not so long?
 * Change StoppageAlert to not have a key which includes the test path. The original rationale for making StoppageAlert have test path and revision in the key was to make it so that there couldn't be duplicate alerts (like we sometimes saw for Anomaly alerts). But in retrospect maybe it would have been better to keep it simpler and more consistent with Anomaly.

**Comment by anniesullie** [comment]
I think the simplest course of action would be to do a POST request instead of a GET when we detect the url would be too long.
