### ISSUE TITLE
Dashboard not showing alert icons

### ISSUE THREAD

**Issue by chrisphn** [catapult-project/catapult#1427]
Looks like chart is not able to load material icons.  Maybe resource link issue?  If it's unreliable, maybe go back to core-icons.

![alert_error](https://cloud.githubusercontent.com/assets/11621527/9621919/baa0e4ba-50e1-11e5-9505-92c465fd2291.png)

**Comment by qyearsley** [comment]
Yep, if we keep seeing this, I think we have a couple options:

1. Change back to core-icon and put them inside a div like you tried -- we know that works too
2. If we did want to keep using the material-icons icon font, we could host the static resources instead of loading it from https://fonts.googleapis.com/icon?family=Material+Icons

**Comment by qyearsley** [comment]
Hey Chris, looks like others are seeing this too :-( Could we go with your solution (use core-icon and put the core-icon elements in divs)?

**Comment by chrisphn** [comment]
Let me look into self hosting.  I do like the material icons more.

**Comment by qyearsley** [comment]
Chris has fixed this: https://github.com/catapult-project/catapult/commit/bcacc064ae18f58b530cf7526a3de4f034f94d15
