### ISSUE TITLE
Perf Dashboard: improvement alerts incorrectly marked as recovered

### ISSUE THREAD

**Issue by tednakamura** [catapult-project/catapult#1459]
Chrome version: 46.0.2490.22 (Windows)
URL: https://chromeperf.appspot.com/group_report?bug_id=530537

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):
N/A

Please describe the problem:
http://crbug.com/530537 was filed earlier today for the series of alerts noted in the above URL. However, just two hours after the bug was manually filed by a sheriff, a bot came in and claimed that all alerts had recovered (comment #4). However, visual inspection of the actual graphs shows no such "recovery."

Did the bot get confused because the bug is ultimately tracking an improvement (i.e. graph values did go down)? We do occasionally file such bugs to make sure that medium to large scale improvements like that are expected.

**Comment by qyearsley** [comment]
You're right! There must be a bug in [auto_triage._IsAnomalyRecovered](https://github.com/catapult-project/catapult/blob/155650a8b278f6eafb6a7422682e8f2646b889ac/dashboard/dashboard/auto_triage.py#L191).

For now, you can just ignore the "recovered" label on these alerts, since it's incorrect. After this bug is fixed, future improvement alerts shouldn't get (confusingly, incorrectly) marked as recovered.

**Comment by benshayden** [comment]
Looks like this was fixed in https://chromium-review.googlesource.com/c/catapult/+/1058188/
