### ISSUE TITLE
Proposal: Catapult auto-roller

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#1463]
_[suggesteed by @primiano]_

We (memory infra) find that we often forget to manually roll Catapult. As a result, it takes several days/weeks before a new Trace Viewer feature makes it to the Chromium tree. Furthermore, manually rolling is quite tedious (despite being a one-line patch). So...

**Should Catapult have an auto-roller in Chromium like [Blink](https://code.google.com/p/chromium/codesearch#chromium/build/scripts/tools/blink_roller/auto_roll.py) does?**

@Apeliotes, @anniesullie, @natduca, @dj2: WDYT?

**Comment by anniesullie** [comment]
I think the only downside to this is that we tend to hit a lot of the edge cases where we can pass the CQ and break the main waterfall or perf waterfall. In particular:

 * The sizes test
 * When telemetry is in catapult, the perf waterfall tests

We'd also need a plan for what to do when the autoroll fails (is there a single person responsible? A sheriff rotation?)

An alternative to autorolling would be some way to decouple most of the trace-viewer code from Chrome so that it could automatically update. Some ideas for how we could do this:

 * Make trace-viewer an extension, and have some process to automatically update
 * Make the part of trace-viewer that rolls into Chrome just the recording UI, and make the viewer a web page or extension that automatically updates

I'd love to get people's opinions on what direction is best. @nedn has thought about this as well.

**Comment by primiano** [comment]
> Make trace-viewer an extension, and have some process to automatically
update
I like this. Every now and then I have to point people to a hack I uploaded
on some www server (a vulcanized traceviewer ui) to get UI features they
don't have yet in their dev/beta version.
Making traceviewer a chrome app would be super nice.

**Comment by nedn** [comment]
@anniesullie If we hit the edge cases where we can pass the CQ and break the main waterfall or perf waterfall, that just mean we need more test coverage. Also for the cases of breaking stuff in chromium/src, not only delaying the roll doesn't help but it usually makes it more expensive to fix the problems later on.

Whether we gonna pursue traceviewer as chrome app now or later, I am all for "rolling as fast as possible". A sheriff rotation for watching out auto rolling SGTM.

**Comment by anniesullie** [comment]
Skeleton design doc:
https://docs.google.com/document/d/130oqBitiy15SBZNu2TYhVQhA-k4AjpjxbtLpv-k0_40/edit

**Comment by anniesullie** [comment]
Thanks to massive help from skia infra team, this is up and running and just committed its first roll: https://catapult-roll.skia.org/

If anyone would like to help triage failures, it will mail this list with problems: groups.google.com/a/chromium.org/forum/#!forum/catapult-sheriff

**Comment by natduca** [comment]
Should we update a contributing guide with information about this? There is currently a deps rolling section.

**Comment by anniesullie** [comment]
Good point. https://codereview.chromium.org/1539973003 up for review.
