### ISSUE TITLE
Canary memory-infra gives exceptions on ToT

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1471]
47.0.2510.0 (Official Build) canary (64-bit)

TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at Object.iterItems (chrome://tracing/tracing.js:340:78)
    at Object.<anonymous> (chrome://tracing/tracing.js:3259:44)
    at Object.iterItems (chrome://tracing/tracing.js:340:139)
    at Object.<anonymous> (chrome://tracing/tracing.js:3252:84)
    at Array.forEach (native)
    at Object.<anonymous> (chrome://tracing/tracing.js:3240:188)
    at Object.iterItems (chrome://tracing/tracing.js:340:139)
    at Object.TraceEventImporter.createMemoryDumps_ (chrome://tracing/tracing.js:3237:165)
    at Object.TraceEventImporter.finalizeImport (chrome://tracing/tracing.js:3110:117)

**Comment by natduca** [comment]
@petrcermak fyi

**Comment by natduca** [comment]
https://drive.google.com/open?id=0B2UAouCtyY6-cHc0bVdseHRBeVU

**Comment by petrcermak** [comment]
I assume you are using Yosemite. The issue here is that it uses ".Helvetica Neue DeskInterface" as the system font. This results in the following allocator entries from Skia:

  * <tt>skia/sk_glyph_cache/**.**Helvetica Neue DeskInterface_  1/index_20</tt>
  * <tt>skia/sk_glyph_cache/**.**Helvetica Neue DeskInterface_  1/index_21</tt>
  * <tt>skia/sk_glyph_cache/**.**Helvetica Neue DeskInterface_  1/index_22</tt>

which Chrome interprets __nested__ (because of the dot):

```
...
'skia/sk_glyph_cache/': {
  'Helvetica Neue DeskInterface_  1/index_20': { 'attrs': A1, 'guid': G1 },
  'Helvetica Neue DeskInterface_  1/index_21': { 'attrs': A2, 'guid': G2 },
  'Helvetica Neue DeskInterface_  1/index_22': { 'attrs': A3, 'guid': G3 }
},
...
```

instead of __flat__:

```
...
'skia/sk_glyph_cache/.Helvetica Neue DeskInterface_  1/index_20': { 'attrs': A1, 'guid': G1 },
'skia/sk_glyph_cache/.Helvetica Neue DeskInterface_  1/index_21': { 'attrs': A2, 'guid': G2 },
'skia/sk_glyph_cache/.Helvetica Neue DeskInterface_  1/index_22': { 'attrs': A3, 'guid': G3 },
...
```

**Comment by petrcermak** [comment]
This is a **Chrome issue**, so I filed a bug for it: https://code.google.com/p/chromium/issues/detail?id=532838

**Comment by primiano** [comment]
Ok this is due to the idiotic dot-path-expansion on the chrome base::Value side.
There are two issues here:
1) Traceviewer should not crash, just fire a warning and ignore the dump or part of it. Petr has fixed this in crrev.com/1356553002
2) Chrome-side should not auto expand dots. I can fix it easily (crrev.com/1354493003).

@natduca the main question for you (and @dj2 ) is: Can I assume that nothing in tracing is relying on that idiotic dot expansion in trace arguments, or would you expect that something is?

**Comment by primiano** [comment]
Hmm bummer, apparently cc.debug.display_items is depending on the dot expansion already. :-/
I guess the alternative will be normalizing font names in skia

**Comment by dj2** [comment]
That sounds like a bug in cc.debug.display_items that we should fix. We shouldn't be depending on that behaviour (mostly because I didn't even know it did that and it seems very surprising).

**Comment by primiano** [comment]
Ok the fix for that seems easy. See crrev.com/1354493003
Just don't know at this point if we have other instances of this case. ¯\(°_o)/¯

**Comment by natduca** [comment]
Agreed. Fix the idiocy. Dot expansion is @#)$*@# and we shouldn't rely on
it anywherez.

**Comment by petrcermak** [comment]
I'm marking this as **fixed** (https://codereview.chromium.org/1354493003).
