### ISSUE TITLE
500 errors showing up from dashboard on Mac Retina bots

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#1485]
I manually whitelisted the mac retina bots. But I am seeing some strange behavior from the perf dashboard. Here is an example:

smoothness.tough_ad_cases step:
http://build.chromium.org/p/chromium.perf/builders/Mac%20Retina%20Perf%20%285%29/builds/29/steps/smoothness.tough_ad_cases
http://build.chromium.org/p/chromium.perf/builders/Mac%20Retina%20Perf%20%285%29/builds/29/steps/smoothness.tough_ad_cases/logs/stdio

> @@@STEP_LINK@Results Dashboard@https://chromeperf.appspot.com/report?masters=ChromiumPerf&bots=chromium-rel-mac-retina&tests=smoothness.tough_ad_cases&rev=349922@@@
> HTTPError: 500. Reponse: 
> `<html><head>`
> `<meta http-equiv="content-type" content="text/html;charset=utf-8">`
> `<title>500 Server Error</title>`
> `</head>`
> `<body text=#000000 bgcolor=#ffffff>`
> `<h1>Error: Server Error</h1>`
> `<h2>The server encountered an error and could not complete your request.<p>Please try again in 30 seconds.</h2>`
> `<h2></h2>`
> `</body></html>`

If you follow the link to the perf dashboard, you'll see that the data *is* there. And I checked the logs, can't find the 500 errors. Any idea what's happening?

**Comment by qyearsley** [comment]
Note, this isn't happening in the latest builds:
http://build.chromium.org/p/chromium.perf/builders/Mac%20Retina%20Perf%20%285%29/builds/34/steps/smoothness.tough_ad_cases/logs/stdio

When I did a search through the logs, I also didn't the corresponding log entry for this response. (I do see a lot of errors for /add_point_queue due to "too much contention", but that's a separate issue).

Will check back to see if something like this happens again.

**Comment by qyearsley** [comment]
Closing since this apparently isn't happening any more.
