### ISSUE TITLE
Need to be able to be able to easily view individual page_cycler pages on /group_report

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#1508]
I hit this almost every day. I know it simplified the logic not to show them, but I think it was the wrong choice for users. Today I tried to show someone how to go through all the steps to add them to a chart on /report and then drill down into the worst regression and bisect, and it was over a dozen steps. I think regressions are getting lost because of this. It really needs a fix. @chrisphn

**Comment by qyearsley** [comment]
Example graph:
https://chromeperf.appspot.com/group_report?keys=agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDAyYTH7QgM

Currently, when viewing individual page series on that , one must:

1. Click "cold_times" in the chart title (this step may not be obvious)
2. Wait a couple seconds.
3. Click "20 more" in the chart legend. 
4. Select the items in the legend you want to view - e.g. select all and hover over items in the legend to find the clearest step.

Step 3 could be made unnecessary if we showed all items by default whenever that box would otherwise be empty.

But what I think you are picturing is having all per-page results shown on the chart right away without clicking "cold_times" in the chart title.

I think that if we changed the `group_report` page so that if we want to show a graph for an alert on a test like "ChromiumPerf/chromium-rel-mac-retina/page_cycler.morejs/cold_times/page_load_time" (a leaf test, with no sub-tests), then make a chart for the parent test instead.

Specifically, in [group_report.html in getTestPathAndSelectedSeries_](https://cs.corp.google.com/#github/catapult-project/catapult/dashboard/dashboard/static/group_report.html&l=47), check the sub-tests dict there and if the test for the alert has no sub-tests, return the test path of the parent ("ChromiumPerf/chromium-rel-mac-retina/page_cycler.morejs/cold_times") and put the specific test ("page_load_time") in the list of selected tests. (Chris, does that sound right?)

**Comment by chrisphn** [comment]
Yea, you can change the view level base on testPathAndSelectedSeries params in group_report.  The current view makes sense to me.  But if it's more useful to conditionally move a level up, then I think it's fine too.

**Comment by anniesullie** [comment]
Yeah, I think conditionally moving a level up is the right thing to do. Thanks!

**Comment by anniesullie** [comment]
Looks like there are problems for more than just page_cycler. On this page, I can't navigate to the individual pages at all: https://chromeperf.appspot.com/group_report?bug_id=502254 (smoothness.top_25_smooth)

**Comment by qyearsley** [comment]
In this case, the individual pages show up after about 3-4 seconds of waiting (for me) - I think this is a separate issue: https://github.com/catapult-project/catapult/issues/1522

**Comment by qyearsley** [comment]
CL submitted and deployed, but not verified.

**Comment by qyearsley** [comment]
Now actually deployed, and verified: https://chromeperf.appspot.com/group_report?keys=agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDAyYTH7QgM
