### ISSUE TITLE
The slice cost report has many groupings in the top controller.

### ISSUE THREAD

**Issue by chiniforooshan** [catapult-project/catapult#1521]
One possible way to make this better is to replace the check boxes by a single drop down menu of common groupings (suggested by Nat).

**Comment by benshayden** [comment]
I emailed a whiteboard photo to you guys. The slice cost report is monolithic, which doesn't fit in the Composable Reports vision. I think that the slice cost report needs to be decomposed into several similar CPU bar charts. Instead of Grouping By Thread and expanding the Renderer sub-tree, you click the Renderer bar in the CPU By Thread chart, which will update all the other charts, including the Slice CPU Duration Histogram.

**Comment by paulirish** [comment]
In my head i was thinking of a drag 'n drop action to define groupings, as you may want a parent grouping that's different.
That could look something like this:

![image](https://cloud.githubusercontent.com/assets/39191/10151137/7bfdd362-65f9-11e5-89e3-56b78f9b68af.png)

**Comment by paulirish** [comment]
However if we didn't do configurable grouping order, this would be my perfect order:

* [ ] Interaction 
* [ ] Thread
* [ ] Event Category
* [x] Event Title
* [ ] Domain
  * [ ] Categorize 3rd parties

**Comment by paulirish** [comment]
For right now, the only configurability we have in this grouping order is thread vs interaction (rail phase).   So given that, we can just enforce the above order. drag and drop is unnecessary. :)

**Comment by natduca** [comment]
I think I fixed this with 8950f933967f437354d43e102e3a2d89f6dca755
