### ISSUE TITLE
Add a mechanism so UMA events can easily be embedded into traces

### ISSUE THREAD

**Issue by philippebeaudoin** [catapult-project/catapult#1543]
Came up from a conversation with Gab. He'd really like if the traces showed where some specific UMA events happened. Maybe provide some way to quickly attach a bunch of UMA events to a trace event category? Glob UMA events? Like Foobar.* --> cat:Foobar

**Comment by philippebeaudoin** [comment]
Assigning to myself so I start a conversation or doc around this.

**Comment by natduca** [comment]
calling @dj2 @vinterstum @fmeawad

**Comment by philippebeaudoin** [comment]
Closing. Adding TraceEvent call when needed sounds like the right thing to do for now, Gab used that successfully.

**Comment by benshayden** [comment]
Sorry, can I ask why this idea was rejected?

It seems like it would remove a significant hurdle for potential clients if they could see their familiar UMA histogram data in traces without needing to add a separate trace event and write catapult javascript to analyze it.
People are writing new C++ UMA histograms faster than we can write them in trace-based javascript.
RAIL and telemetry and PI could more easily re-use their UMA metrics, instead of rewriting them in terms of trace events, possibly subtly differently.
With UMA data in traces, it seems like it would be easier to validate that PI produces aggregated metrics that are comparable to UMA.
With UMA data in traces, clients who want to change their metrics would have the option of either modifying their C++ and waiting for it to propagate, or they could try writing a little javascript.

**Comment by natduca** [comment]
Good question! This was closed, not rejected. gab found a specific solution that worked for him, so the issue was closed. The use case you are describing remains an open question... I totally agree more synergy with uma would be cool.

The main question I have is whether our "ideal" well defined enough to be a bug.

Some eng philosophy first: my experience has shown that bugs are best when they are actionable. Open ended issues tend to languish on a bug tracker. A good compromise is to have two systems --- one for backlog, and one for bugs. We use github issues for bugs, and our team page has a link to our tracker.

Do we know what we want to do here, precisely? If not, then I'd suggest a backlog entry...

**Comment by benshayden** [comment]
I see it on the backlog now. That makes sense. Thanks!
