### ISSUE TITLE
Presubmit check on BUG=# doesn't catch BUG=# with no number

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1549]
Just put up a cl that had

 BUG=#

but no text. Seemed to get through.

**Comment by natduca** [comment]
calling @anniesullie

**Comment by qyearsley** [comment]
It appears that when you first run `git cl upload` to create a CL, the presubmit checks are done *before* there is a commit description, so the BUG check in the presubmit never catches anything the first time. When I try making a CL with BUG=# and uploading, it passes the first time, but then catches it on subsequent runs of `git cl upload` or `git cl presubmit`.

**Comment by qyearsley** [comment]
The way catapult is doing this check appears to be the same as [this example](https://www.chromium.org/developers/how-tos/depottools/presubmit-scripts#TOC-Details-and-Example); since the checks are also run in `CheckChangeOnCommit` in [PRESUBMIT.py](https://github.com/catapult-project/catapult/blob/master/PRESUBMIT.py), I think that a commit with BUG=# would initially get through on the first run of `git cl upload`, but would not actually get committed.

**Comment by qyearsley** [comment]
Just verified (with CL https://codereview.chromium.org/1378413002/): the presubmit fails before committing when the CL just has "BUG=#" with no bug number.

Shall we close this issue, or is there something that we want to change?

**Comment by natduca** [comment]
Your notion is that the cq would prevent this from landing? It seems like I could do git cl upload, with a bad message, and then git cl set-commit. Would that land?

**Comment by qyearsley** [comment]
I believe that it wouldn't land, because if it goes through the commit queue, then the try job on [Catapult Presubmit](https://build.chromium.org/p/tryserver.client.catapult/builders/Catapult%20Presubmit?numbuilds=50) should catch it.

(I quickly tried [this](https://codereview.chromium.org/1394303002), but in order for commit-bot to let the commit queue try jobs get triggered in the first place, the CL needs an LGTM on Rietveld, I believe?)

**Comment by eakuefner** [comment]
Archiving; we now check for this.
