### ISSUE TITLE
UserFriendlyCategory categories syncchannel::send as part of parent

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1551]
Thinking maybe this isn't the right approach. Afaict, thats typically sync calls to the browser for things like getCookie. Unfortunately, categorizing it as part of its parent causes it to get lumped inside v8 usually.

Might want to revisit

Calling @benshayden @dstockwell

**Comment by dstockwell** [comment]
Hmm, I see. I think the cases where I saw it where usually inside resource loading.

Not sure if we want to undo this, or make a special case for v8.

**Comment by natduca** [comment]
@chiniforooshan can you take a few minutes to grok this and provide feedback?

**Comment by chiniforooshan** [comment]
Trying to understand the issue... Sync calls happen in many places. Most of them in V8 and resource loading, but also in handling input events and other places. For example, what do you think is a good category for getCookie-related sync calls (they are currently under 'script', AFAIK)?

Or maybe you are not talking about just the category names and the issue is about associating CPU cost to renderer when it's doing a sync call to the browser and thus over-stating CPU usage of the renderer?

**Comment by natduca** [comment]
I'd call them separately. Can we tell getCookie separately? Cookies category sounds good. Anything else, could be DOMBindings maybe. I'd love more examples so I could give specific repsonses to help you build a model indirectly... mental model here is "nat isn't sure on the overall rule to do here, but if you ask him to categorize N specific cases, for sufficiently big N, you'll start being able to see a pattern to his madness and then explain the rule to all of us."

**Comment by benshayden** [comment]
Feel free to reopen?
