### ISSUE TITLE
systrace_trace_viewer.html created from systrace.py calling location

### ISSUE THREAD

**Issue by ChrisCraik** [catapult-project/catapult#1621]
Would be preferable for it to be constructed at systrace.py's location, or some relative path.

This would mean the minified tracer contents wouldn't keep getting at your working directory. In e.g. the android tree or SDK, it would never need to be constructed, since it's checked in.

@wangzhen127 thoughts?

**Comment by wangzhen127** [comment]
You mean let update_systrace_trace_viewer.py create systrace_trace_viewer.html in the systrace.py location?

In Android, there is a wrapper chromium-trace/systrace.py, when we use that, we want to create systrace_trace_viewer.html in chromium-trace/ instead of catapult/systrace/systrace/, right? (Technically, chromium-trace/systrace_trace_viewer.html will not be updated because when we run chromium-trace/update.py, it uses no_auto_update=True)

**Comment by ChrisCraik** [comment]
Sorry, that wasn't clear - I meant the wrapper's location in the android tree. chromium-trace/systrace_trace_viewer.html

What does update_systrace_trace_viewer do if not update the chromium-trace/systrace_trace_viewer.html file?

**Comment by ChrisCraik** [comment]
How about an additional argument the wrapper could pass to specify where the systrace_trace_viewer.html's path is?

Then it can define it relative to itself, and we can just ship the wrapper in the Android SDK to solve the same problem there (in addition to warning about python3 not being supported).

**Comment by wangzhen127** [comment]
update_systrace_trace_viewer.py checks if systrace_trace_viewer.html contains NO_AUTO_UPDATE. 

In the case of Android, when you use the wrapper chromium-trace/systrace.py, systrace_trace_viewer.html will NOT be updated. Because when we use chromium-trace/update.py to manually update it, it puts NO_AUTO_UPDATE in it.

**Comment by wangzhen127** [comment]
In the case of Catapult, I do see that catapult/systrace/systrace/systrace.py creates systrace_trace_viewer.html in the calling location. And it would be preferable for it to be constructed at systrace.py's location.

**Comment by ChrisCraik** [comment]
Fixed with 4aaa445b7b1a252d60dfaa0c8be2e56022d69e0f
