### ISSUE TITLE
Write a design doc to clean-up metadata and querying

### ISSUE THREAD

**Issue by philippebeaudoin** [catapult-project/catapult#1675]
There seems to be some problems and limitations with the current way we handle metadata:
- Some metadata is in the trace, some is extracted from the file (date?)
- Filtering on metadata requires unzipping the trace
- The metadata is not the same if recorded via slow report versus manually

Pinging @natduca @fmeawad @vinterstum

**Comment by simonhatch** [comment]
Inconsistent metadata bug: http://crbug.com/544265

**Comment by natduca** [comment]
I think we should consider metadata-as-part-of-upload a bug, and instead switch to all metadata being in traces, and then figure out how to get pi server to extract metadata during upload [perhaps with cloud mapper?] and then cache it for faster /query handling.

**Comment by philippebeaudoin** [comment]
Ok, We need a design doc. Happy to start on this. I'll keep it very high level and ask the various experts on this thread to fill in the details.

**Comment by lpy** [comment]
Note that this blocks most of the trace metadata issues in chromium.

**Comment by natduca** [comment]
@lpy which ones get blocked? Lets try to figure out which ones in chromium are blocked, and whether we can be a bit pragmatic in unblocking them. Often times when we see a code mess, we have three options;
1. Ignore the mess. Land stuff.
2. Block on the code cleanup project completing
3. Wait until the design doc emerges for the code cleanup. But, instead of waiting for the cleanup to happen, land a bit more code debt. File and self-assign a cleanup bug to match the new design doc once lands.

It may be worth thinking through which bugs fall into which option above.... even option 1 is good somtimes.

**Comment by vinterstum** [comment]
Part of the problem right now is that using the metadata macros adds __metadata events to the tracelog, whereas the global metadata (showing up under the "M" thing in the trace-viewer) is a separate "metadata" JSON element outside of "trace_events", which is set using duplicate code in two different string trace sinks. Adding new metadata using the macro is trivial (like the HighResTimer stuff yesterday), but if we end up wanting this kind of stuff inside the global "metadata" JSON instead, rather than as a metadata event, it means changing parsing later. Which may not be a big deal, of course.

**Comment by lpy** [comment]
@natduca I am working on figuring out which can be done by ignoring the mess and we can visit back later.

**Comment by natduca** [comment]
@vinterstum good point. I think one missing piece is that M-phase events that are unrecognized right now are't added onto model.metadata.

Maybe we need a generic M-phase event name, e.g. ph: m cat: model-metadata name: whatever arg0: "blah" that when parsed, pushes the metadata to the model?

**Comment by philippebeaudoin** [comment]
I like the idea of an M-phase event that can be added anywhere. Spit out a
warning if we get incompatible ones.

**Comment by philippebeaudoin** [comment]
Very VERY preliminary skeleton of a design doc, with the ideas I collected around metadata. Please contribute, organize, clean-up... I'll get back to it soon:
https://docs.google.com/document/d/1dT_ULCiTsUzUMBr9OsXBP5juJ9CE_IT73Az-ocp9dMc/edit#

**Comment by philippebeaudoin** [comment]
That document is pretty much complete, closing.
