### ISSUE TITLE
Perf Dashboard: Alert incorrectly marked as recovered

### ISSUE THREAD

**Issue by tednakamura** [catapult-project/catapult#1693]
Chrome version: 48.0.2547.0 (Windows)
URL: https://chromeperf.appspot.com/report?sid=c9714bd5f5276cdce2dae647492d1c8eb118cfc6f8a2fc67c0a663e2456f9b7a&rev=355294

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):
N/A

Please describe the problem:
http://crbug.com/547661 (Note that the bug is view restricted) was filed because we received an alert that this graph changed from reporting values around +1.0ms to consistently returning -1.0ms. However, the dashboard has since reported that the alert has recovered, even though the graph is still reporting the invalid -1.0ms value.

**Comment by qyearsley** [comment]
Note, I started to try to debug this, and noticed that some details are logged when alerts are marked as "recovered":
https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/auto_triage.py#L187

I couldn't find the log for this particular case, but looking through the recent logs, one sees lots of cases like this:
```
D 03:27:06.720
Anomaly Key('Anomaly', 5252809707487232) recovered with measurements {'relative_change': 0.001144765084664453, 'min_relative_change': 0.10000000000000001, ...).```

Which makes it look like there's likely a bug that makes it so that min relative change isn't used or checked correctly?

@chrisphn fyi

**Comment by qyearsley** [comment]
Uploaded related CL 2 weeks ago: https://codereview.chromium.org/1415513009/
Planning to commit that after adding more tests.

**Comment by qyearsley** [comment]
No alerts have been marked as recovered since that was submitted -- maybe it's just very strict in what is considered recovered? Or maybe there's a bigger problem? This issue isn't really solved yet.

**Comment by qyearsley** [comment]
Note: after that patch in Dec 2015, we haven't had many alerts marked as "recovered"; it's possible that that _IsAnomalyRecovered should be made less strict so that it marks more alerts as recovered, but the original implementation of _IsAnomalyRecovered is probably more complex than we want here.
