### ISSUE TITLE
Remove 'map_' from function_handle and add JS impl

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1705]
When we have reducers we're going to need reducer handles too, so it'd be nice to just rename mapper handle up front.

**Comment by natduca** [comment]
Calling @eakuefner ...

**Comment by eakuefner** [comment]
Also, it turns out that we're going to be using this, instead of mapper names or filenames (since the new concept requires both, to accommodate the case where we might have multiple mappers defined in one file), so in addition to this rename, we're going to be providing a function_handle abstraction for the JS side as well.

**Comment by eakuefner** [comment]
This is done. Continuing the plumbing work in #1703.
