### ISSUE TITLE
RAIL IRs aren't right for traces generated by DevTools

### ISSUE THREAD

**Issue by paullewis** [catapult-project/catapult#1709]
Traces taken by DevTools don't seem to register IRs for Page Load except Idle. I'm not sure if we can infer Load from the DevTools categories as-is. The current DevTools categories are:

* `blink.console`
* `devtools.timeline`
* `toplevel`
* `disabled-by-default-devtools.timeline`
* `disabled-by-default-devtools.timeline.frame`

[Here's a sample trace](https://dl.dropboxusercontent.com/u/2272348/traces/timeline-ember.json), in case it's useful. This is from loading the TodoMVC Ember example on a Nexus 5.

**Comment by benshayden** [comment]
The RAIL IR Finder requires the navigation and benchmark categories in order to find Load IRs, which are defined in terms of RenderFrameImpl slices and benchmark paint markers. The current plan for Load IRs will also require other categories.
RAIL IR Finder requires the latencyInfo category in order to find Responses and Animations.
Perhaps at some point RAIL IR Finder will be able to find IRs with a minimum of categories.
Maybe RAIL IR Finder should issue warnings when the trace doesn't contain the required categories?
Lots of good things for me to think about and work on.

**Comment by natduca** [comment]
I'd prefer us to not be robust to missing data. Its hard to compute rail, even when you have the right categories.

IMO, If someone is expecting RAIL and it couldn't be computed we should show some information explaining what happened. Maybe the railscore span should say "RAIL: unavailable" and clicking/hovering it gives a tooltip or messagebox  explaining the issue? Similarly, maybe the rail side panel should explain the failures instead of greying out?

Originally I thought info-baring would be good. But, then I realized we need to be discrete: traces from non-chrome data sources like Android shouldn't shout that they're missing categories, for instance.

@paulirish we should figure out how to get devtools & tracing categories reconciled.

**Comment by benshayden** [comment]
https://github.com/catapult-project/catapult/issues/1776

**Comment by benshayden** [comment]
@natduca Should this be closed as a dup of #1776 ?

**Comment by natduca** [comment]
Not quite. I think the real issue here is that its vague what categories one needs to turn on in order to get RAILscore to work. It'd be good if it was just that "benchmark" always made RAIL work, for instance. But, it may be that RAIL is more intrusive than benchmark would permit [it has a 1% overhead goal iirw, @vinterstum @nedn can confirm]. In that latter case, then we'd need a separate category rail-required probes... we could call it rail, but i think given that we intend to rename rail to something else, we might want to close on that naming sutff first.

**Comment by nedn** [comment]
I don't know about the overhead of tracing categories required for computing RAIL, just the overhead of computing RAILs during importing phase.

**Comment by natduca** [comment]
This mostly seeems to be about picking a category that triggers railscoring tracing reliably. Making the overhead low is probably a separate issue for another day. To keep things clear, @benshayden  and I have filed #1818 to capture followup work here. I will now close this bug.
