### ISSUE TITLE
Add network cost of resources to the model

### ISSUE THREAD

**Issue by chiniforooshan** [catapult-project/catapult#1720]
We will need to:

1- Compute resource sizes from netlog: there is enough information in traces for this.

2- Link "requestResource" events from renderer to corresponding netlog events: an easy not-perfect solution is to associate a top level netlog slice to the first renderer "requestResource" event before it that has exactly the same URL parameter. A correct solution is through traits.

**Comment by natduca** [comment]
Is there a way we could do something a little less risky than traits and a little more sophisticated than just using first slice logic? E.g. have netlog and blink share some id? Iirw, csharrison@google had some ideas here.

I do agree long run that traits should do this, but I think v0.1 of traits may not support cross process traits. So that may mean we have to roll a custom solutuion for netlog...

**Comment by natduca** [comment]
Pulled the associating network requests together out to #1725. We can close this bug once we've got the byteCount patch landed....

**Comment by chiniforooshan** [comment]
byteCount patch landed 6 months ago: https://codereview.chromium.org/1403403012/
