### ISSUE TITLE
Perf dashboard dev server tests not run on CQ/waterfall

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#1734]
I was making some recipe changes and I realized the dev_server tests are not run on the waterfall/CQ, and one is currently failing.

@qyearsley @chrisphn

**Comment by qyearsley** [comment]
Quick question -- what do you think about running `catapult/bin/run_tests` in the catapult recipe?

Pros: Easy to change which tests are run by making a change in catapult instead of in the recipe
Cons: Different tests aren't separated into different steps in the buildbot job view.

Meanwhile, the test that's broken is the chart-legend test added in https://codereview.chromium.org/1414493005, so fixing that is the first task in fixing this bug.

**Comment by anniesullie** [comment]
I'd prefer to have the steps clearly separated out, so that's too much of a con for me. I wish we had a better way to deal with recipe changes though.

**Comment by qyearsley** [comment]
SGTM. Uploaded https://codereview.chromium.org/1407253008/.

**Comment by qyearsley** [comment]
Now fixed. Example build: https://build.chromium.org/p/client.catapult/builders/Catapult%20Mac/builds/623

**Comment by qyearsley** [comment]
Note, fixed by https://codereview.chromium.org/1434163002/
