### ISSUE TITLE
Extra space appears in sample_sub_view for samples that dont have method names

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1742]
![image](https://cloud.githubusercontent.com/assets/412396/11007614/f9059f58-847f-11e5-8b68-30448837e926.png)

Calling @lpy

**Comment by natduca** [comment]
@lpy fyi

**Comment by lpy** [comment]
I didn't find anything in catapult related to extra space, from the trace file, my guess is extra spaces are generated when we save the trace. So probably it is in C++.

**Comment by natduca** [comment]
Hahah is there a way you can be sure that this is happening, somehow? Is the extra space in the codemap for instance?

**Comment by lpy** [comment]
I found the extra space in the code map (it shows up in the code-generation entries) for all anonymous functions. We can either check if extra space exists and fix it from the UI side, or maybe we can file a bug for the C++ and fix it.

So I am closing this issue since it's not a JS issue, feel free to reopen it if you think otherwise.

**Comment by natduca** [comment]
Sounds good. Should we open a crbug.com/new and label it with Performance-Tracing to fix the c++ sidE?

**Comment by lpy** [comment]
I think we should. Eliminating extra spaces from JS side is a short term fix, will try to figure out from the C++ side.
