### ISSUE TITLE
RAIL: Recompute rail-score-span based on rangeOfInterest

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#1746]
Right now, rail-score-span runs for the whole model.

Sometimes you just want to see the rail score for these IRs in a specific time-window.

Fun fact: the time-window selection mark tool translates into the "rangeOfInterest" in the code.

If we make rail-score-span respond to rangeOfInterest updates, then when you highlight some IRs using the mark tool, then you can see the rail score just for the IRs that interest you.

The rail-score-side-panel suffers a similar issue, and would also benefit from a similar feature.

**Comment by natduca** [comment]
Awesome! Probably the way to this is to make RAILScore constructable with a Range object so that it can limit the range of the model that it considers.

The rail_score_sidE_pnael actually already has a rangeOfInterest setter that is called whenever the mark changes, so that one is going to be pretty easy to hook up.

The rail_score_span will need more work: we'll need to add a rangeOfInterest getter/setter on the span, and probably modify timeline_view so that every time rangeOfInterest changes, we tell the railScoreSpan about it.
