### ISSUE TITLE
PI Problem framework

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#1758]
We keep talking about finding "problems" that impact performance.
These might be bugs in chrome, or web pages, or javascript libraries, or hardware, or OSs, or some combination of them.
We keep finding interesting problems in perf parties and other discussions. Problems are found by expert humans.
Sometimes bugs are filed. Even when these bugs are filed, they often lie dormant due to lack of prioritizing data. How do we tell how important these problems are relative to other problems?

We need a framework to allow perf partiers et al. to data mine PI corpora for these problems.

This framework would be based on PI Mappers. Like PI Mappers, Problems would run on the PI infrastructure and use the tracing APIs such as InteractionRecords, UserFriendlyCategory, Traits, etc.

But Problems are different from metrics. Metrics measure something that is almost always there. Successful Loads always have a measurable time from navigation commit to first ready-to-meaningfully-paint. But Successful Loads might rarely exhibit the Problem where async scripts have higher latency than a sync script would. The interesting thing about a Problem is whether it is there or not. Its severity is secondary.

Problems should be associated with a crbug or catapult bug. That association can be enforced by the API. That association can also be used by the UI to allow linking from a bug directly to the PI dashboard analysis for the problem.

Depending on the nature of the bug, it might be just as important to note when the problem could have happened, but didn't. The Problem is missing when a feature such as async scripts is working correctly.

When a Problem is found in a trace, or found to be missing, further context could be logged to allow the PI dashboard to link directly to the interesting part of the trace.

The severity should be calculated to indicate the total cost of the problem, perhaps in milliseconds of latency. This could include own time and/or total latency due to the problem.

For example, a Problem could look something like this:

    pi.defineProblem('catapult:#424242', function(model, foundProblem, missingProblem) {
      // iterate over renderers, or IRs, or a type of event
      // If the problem is found:
      foundProblem(severity, context);
      // If the problem is missing:
      missingProblem(context);
    });

Severity should be reported whenever a problem is found, but what form should that information take?
Severity could be an enum like LOW, HIGH for a simple Problem.
More often, though, severity should indicate the total cost of the problem, in milliseconds of latency that is directly attributable to the problem.
The own-time of an event could also be logged as part of a structured severity field alongside total latency.
For example, the severity of a forced layout could look something like

    {total: {value: 42, unit: Units.timeDurationInMs},
     own: {value: 10, unit: Units.timeDurationInMs}

The more sophisticated the format of severity, the more sophisticated the analysis UI on the dashboard can be.

Based on bus discussion with @paulirish .

**Comment by natduca** [comment]
I agree this is where we want to go. Alerts should either become this, or alerts should go away, or we should understand the distinction between the two.

@paulirish is this the thing that we want to share between devtools and tracing?

**Comment by philippebeaudoin** [comment]
Interesting idea. It's basically a mapper where each trace has a binary output, right? Maybe with some extra info, like # of times the problem is encountered, context of the problem, severity of the problem (how much slow down can be attributed to it, etc.)

I think the most interesting aspect here is if to get many people thinking in terms of "problem predicates". ie. Here is a short test you can do on a trace to check if it exhibits a problem. Having a collection of such predicates sounds like a powerful tool not only for mappers, but maybe for trace viewer itself.

Hmmm... In a sense it feels a bit like "linter rules" for traces... Maybe I'm getting too far off the original idea though.

How do we encourage people to think like this? Some ideas:
- Make it trivial to generate a mapper given a predicate. ie.  maptraces --findall="my_problem.html"
- Have enough tools/utils to make writing typical predicates trivial. ie. has_slice('Foo').followed_by_slice('Bar').within_ms(20)
- Have tools to collect/list/organize user contributed predicates.

**Comment by benshayden** [comment]
Lint rules is a good analogy.

Those ecosystem ideas sound good.

Lots of other stuff needs to happen before PI would be ready for this, though.

**Comment by benshayden** [comment]
Should this move to the backlog?

**Comment by natduca** [comment]
Yeah, but maybe we could distill the ideas from this brainstorm into a doc when we close this?

**Comment by benshayden** [comment]
I added it to the BigData tab of the PI+SI Backlog with a link to the doc.
