### ISSUE TITLE
railScore & railScoreSidePanel rangeOfInterest seems to be a bit over-inclusive

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1763]
In the cats trace:
https://drive.google.com/file/d/0B2UAouCtyY6-Wkg1aExrcWNsUFU/view?usp=sharing

When I select this range:
![image](https://cloud.githubusercontent.com/assets/412396/11079059/71d362da-87be-11e5-960e-17af8d53a507.png)

The idle range to the left of the mark is also selected.

I think [,) is the typical rule that we want to use here, where rangeofInterest and IR ranges are both [,) intervals... I bet range doesn't work this way now.  Maybe we just need a second intersects that defines this more explicitly.

**Comment by natduca** [comment]
calling @benshayden

**Comment by benshayden** [comment]
Currently, Range.intersectsRange is defined as !this.findIntersection(range).isEmpty.
I'm trying to figure out if this is an issue with findIntersection, or isEmpty.
Currently, isEmpty indicates whether any value has been added to the range.

Should Range.isEmpty instead indicate whether at least two distinct values have been added to the range? i.e. min < max instead of min <= max.
You mentioned that there are clients that rely on the current inclusive [,] behavior of isEmpty. There are a bunch of tests that fail when I make intersectsRange exclusive (,), i.e. explicitly return intersection.min < intersection.max. I imagine that there would be more tests that would fail if I made isEmpty return min < max. However, if you want to say that this is a more correct conceptualization of either intersectsRange specifically or isEmpty generally, then I can update the tests. What I'm more worried about is manually inspecting each client to see if the new definition of either intersection or isEmpty would actually break something.
:-1: 

Or I could just add a new method like intersectsRangeExclusive. :-1: 

Or we could add two bools to Range like "isMinInclusive"/"isMaxInclusive", and formalize intersection and union (addRange) on top of that. :+1: 
These bools could default to true (or isMin/MaxExclusive default to false) to preserve current behavior for other clients. This would let us fix rail score rangeOfInterest without updating the entire world until we had a reason or the time to rethink all the other clients individually.
This would also let us handle all 4 variants `[,]` / `(,)` / `[,)` / `(,]` with a single method each for intersection and union, rather than eye-stabbers like intersectsRangeInclusiveExclusive / intersectsRangeExclusiveInclusive.
This would also let us define isEmpty such that (x,x) is empty but [x,x) and (x,x] and [x,x] are not empty.
We could even structure the API so that the inclusion quadrant is always explicit in the construction of the Range.
:+1: :+1: :+1:

**Comment by natduca** [comment]
I like there being function names with all the permutations ... one function for each one. Bonus points if we go back and rename intersects to be whatever its permutation is.

**Comment by benshayden** [comment]
I can do the method variants, but I just want to clarify that the reason why is performance, right? Mo' branches mo' problems wasting cycles, I know, but I just want to confirm that that's the reason.
Just out of curiosity, is there a rule-of-thumb for an acceptable level of speed regression for this sort of API generalization? 5%?

Would subclasses maintain performance? Like RangeExclusiveExclusive, RangeInclusiveInclusive, etc. would each implement findIntersection and other hot methods to minimize prototype chain searching. My javascript is fuzzy.

**Comment by natduca** [comment]
Backing up, the first thing to know is that our intersection check is horrible and it should be ripped out immediately and implemented properly. Typically, an intersection check is a few subtractions & comparisons together. E.g. y = blah; return a < b && b > y.

From there you can draw two conclusions:
1. we're creating new range objects every time we do an intersection test just do this substraction?! thats patently rediculuous.
2.  Changing it to exclusive or inclusive is just a matter of toggling the operators a bit. Just make the first one work, then c&p it a few times. It'll be fast, easy and we can move on.


As far as the performance question goes, its about whether the function appears in a tight inner loop that is of import to us. Interesection checks are in our tightest inner loops  --- we iterate the model routinely doing intersection checks. It should be as fast as we can make it, within reason.

Reason is typically defined as the intersection of our ability to code it up, relative to our ability to maintain the result that is produced. In this case, the intersection flavors are all quite similar so they're easy to code up, and they're all going to look very similar all pasted out in a nice neat row, so they'll be easy to hack on if we need to tweak them. But also, this is a relatively closed design space, so I wouldn't expect us to need to hack on the code in the future ... once it works, it works, and we'll not need to hack on it exhaustively.

That all implies that we should do the straightforward thing right from the beginning and get it done.
