### ISSUE TITLE
No longer able to zoom in and out when holding down control

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#1789]
Repro steps:

1. Open up a trace in trace viewer
2. Select the timing tool
2. Press and hold control
3. Click and hold down the mouse button and move the mouse vertically

Expected:
Trace viewer should zoom in and out on the trace as the mouse is moved.

Actual:
Nothing

**Comment by zeptonaut** [comment]
Looking deeper into this, it looks like this is directly caused by #1529.

@petrcermak, was it expected/intended that your change would break CTRL+drag to zoom?

**Comment by petrcermak** [comment]
Yes, that was definitely caused by c39649f. I changed the Ctrl behavior in the _selection_ mode and the _timing_ mode was affected as well.

Is this something that you do/did a lot (zoom with Ctrl)? I'm a little worried that the UI will become inconsistent if Ctrl sometimes switches mouse modes and sometimes doesn't.

**Comment by zeptonaut** [comment]
It was definitely something that I did a lot, but I'm in the majority here or not.

**Comment by petrcermak** [comment]
In that case, we should get it back (perhaps with a different key) so that you could use it :wink: Any ideas?

**Comment by zeptonaut** [comment]
Doh. Looks like alt+mousewheel does the same thing. I'll go ahead and close this :)
