### ISSUE TITLE
Remove “memory” checkbox from RecordSelectionDialog

### ISSUE THREAD

**Issue by ruud-v-a** [catapult-project/catapult#1804]
When the “memory” category is removed from chrome://tracing ([CL](https://crrev.com/1468883003), [bug](https://crbug.com/560300)), the checkbox for this category still remains in the selection dialog if it was encountered before, because the category name is kept in local storage.

Probably the way to address this is to have a piece of code that removes the category from local storage for a few releases.

Related: #1050.

**Comment by petrcermak** [comment]
The category names are loaded from local storage on [this line](https://github.com/catapult-project/catapult/blob/2091404475cbba9b786442979b6ec631305275a6/tracing/tracing/ui/extras/about_tracing/record_selection_dialog.html#L554). I think that the best approach would be not to do that at all — I don't see why we would ever want to display a category that was not returned by [<tt>TracingControllerClient</tt>](https://github.com/catapult-project/catapult/blob/2091404475cbba9b786442979b6ec631305275a6/tracing/tracing/ui/extras/about_tracing/tracing_controller_client.html) in [<tt>beginRecording</tt>](https://github.com/catapult-project/catapult/blob/2091404475cbba9b786442979b6ec631305275a6/tracing/tracing/ui/extras/about_tracing/record_and_capture_controller.html#L67).

I've done a bit of <tt>git blame</tt> archaeology and found that the code for including categories from local storage was introduced in 4239222b00e14a1e75bb28e70bfa6339c7bd0a02 ([this line](https://github.com/catapult-project/catapult/blob/4239222b00e14a1e75bb28e70bfa6339c7bd0a02/src/category_filter_dialog.js#L72)).

@dj2: Do you remember what the rationale was?

**Comment by petrcermak** [comment]
Speculative fix: https://codereview.chromium.org/1482743002/

**Comment by picksi** [comment]
Noob question: Does this relate in any way to memory option in the "time"/"memory" selector in results.html?

... Every time I see this selector I feel like fixing it to only appear if both categories have data in them, otherwise make it default to whichever has data. Maybe one day :)

**Comment by petrcermak** [comment]
@picksi: No, this is a different issue. The "memory" category used to be one of the tracing categories in Chrome (but it's not anymore since https://codereview.chromium.org/1468883003).

Having said that, I totally agree with your feeling about the time/memory selector in Telemetry results.html.

**Comment by fmeawad** [comment]
I beleive the reason we cache the category names is because we can only display what we have reached, so in case we are trying to record something that only happens based on some action, it will never show up.

I think the fix requires using UserFriendly categories or category groups that understands what we have seen and except what we have not.

**Comment by natduca** [comment]
As far as categories persisting, thats indeed a feature as Fadi mentioned. The original issue was that when you record, you'll only see categories for tracepoints that have been reached by your code up to that point. So if your tracepoint is something that is typically off, then you wouldn't see the category.

Maybe though this is just a bad feature: if someone were to complain about this today, I'd just tell them to GetCategory during an init function. This having been said, if we want to undo this feature, since the code is so fragile, I'd encourage us to just embark on a fresh implementation of the dialog: We know we need it anyway, and the dialog is a horrible evil nasty mess of code whose time really should have come long ago...

**Comment by petrcermak** [comment]
I agree that if we want to get rid of the persistence, we should do it as part of a complete dialog overhaul.

I would personally wait with removing the "memory" category from the dialog until the aforementioned overhaul. I don't like the idea of hard-coding this for a single category (unless it's really necessary).

**Comment by natduca** [comment]
Sgtm. Should we close this bug since we have the overhaul item in the backlog?

**Comment by petrcermak** [comment]
Yes... Done :smile:
