### ISSUE TITLE
Non-chromium committers can't give commitable lgtms

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1813]
In https://codereview.chromium.org/1469203002/#msg19 @martijncoenen lgtmd' but the cq rejected his lgtm because he's not a committer. I assume thats because he's not a chromium committer? Or maybe I'm confuss...

How do we fix it s.t. @martijncoenen and our other android contribs can land patches?

**Comment by natduca** [comment]
Calling @anniesullie

**Comment by anniesullie** [comment]
We have our own committers list. Committers need to be added at https://chrome-infra-auth.appspot.com/auth/groups#project-catapult-committers by a project admin (you and I are both admins).

I added @martijncoenen. @natduca can you check the list there for other omissions?

**Comment by natduca** [comment]
Oh, interesting. When we add someone to the project do we add them to both the github commiters list and also this one too?

**Comment by anniesullie** [comment]
Yeah, sorry it's messy. We can't auto-sync the CQ committers list and the GitHub committers list because the CQ one uses emails and the GitHub API does not expose email addresses. So you need to add people to both :(

**GitHub contributors** can add bug labels, milestones, etc.
**CQ committers** are recognized by rietveld, CQ, etc.
