### ISSUE TITLE
Store benchmark_name in Test entities, and use it when constructing bisect command.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1839]
Background:
The perf dashboard uses the third part of the test path to guess the command to use when starting a bisect job. In the past, when benchmark names are changed and test data is migrated, this has meant that the wrong Telemetry test was used, e.g.: http://crbug.com/564163.

However, after http://crbug.com/525220, perezju had the idea to send test suite name separately and have the dashboard determine the test path from that. This decouples the Telemetry benchmark name and the test suite name in the test path -- these two can be two different strings.

Proposed change:
 * When creating Test entities, optionally add a property called benchmark_name (only applicable to data received using the Dashboard JSON v1 format).
 * When starting a bisect job, check whether the test has that property, and use it when constructing the command if it is available.

This will make it so that future test name migrations won't affect the benchmark name used when bisecting.

**Comment by natduca** [comment]
This reminds me a lot of the "trace" button --- there we need to know the command to run to generate a trace. Can we find some underlyign infrastructure throughout *all* of catapult for representing this stuff perhaps (plz?). @simonhatch @eakuefner

**Comment by anniesullie** [comment]
We've been using chartjson for these issues, which enables telemetry, perf dashboard, and bisect all to access the data.

Currently perf dashboard keeps the data in its own app-engine-datastore-backed classes instead of sharing code for representing objects, but all the data types are simple enough that this hasn't caused us issues. I imagine there is some solution where we can map those data types into a shared python class, but we haven't had a clear need for it yet.

**Comment by anniesullie** [comment]
I think we want the benchmark name to be consistent between telemetry and perf dashboard, so WontFix-ing.
