### ISSUE TITLE
Dashboard fails to update issues with bisect results if the culprit owner is @google.com

### ISSUE THREAD

**Issue by vuppalapu** [catapult-project/catapult#1845]
Eg: crbug.com/551487, dashboard is continuously trying update the issue with bisect results, but for some reason issue tracker api is throwing 500 error code.

**Comment by qyearsley** [comment]
Alright, so the most obvious change to make would be to add a check to see specifically if the author is @google.com, and only CC them but don't set them as owner.

Another possible option: don't auto-assign owner at all; maybe I think it's better to wait until the author personally responds to the bug thread before setting them as owner. A CL author will be more likely to "take ownership" and actually do something about a performance regression if they're not just auto-assigned. WDYT?

**Comment by anniesullie** [comment]
Two things:

1. I think the problem is assigning to an owner without editbugs access, and this just happens to be a google.com account that hit it. I think trying to auto-assign and falling back to cc-ing should fix the problem.

2. We changed from cc to assign after a regression fell through the cracks because the author was cc-ed and not marked as owner. So I'd prefer to mark as owner, but of course continue our work on accuracy.

**Comment by qyearsley** [comment]
@chrisphn After https://codereview.chromium.org/1761783006, I think the dashboard should fall back to not setting an owner if adding a comment while setting an owner fails. It would be good to verify that this issue is resolved (i.e. re-kick a bisect for https://chromeperf.appspot.com/group_report?keys=agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDApa72pAoM and verify that a post is successfully made) after that CL is committed.

**Comment by qyearsley** [comment]
Correction to the above comment: I meant to say that after https://codereview.chromium.org/1749423003, I think the dashboard should retry if it got a response indicating that the owner is invalid or nonexistent.

**Comment by vuppalapu** [comment]
I think as per the above comment, this is fixed. We didn't see any similar issue in the recent time.
Closing this assuming the issue is resolved.
