### ISSUE TITLE
Show Triaged results in 500 error

### ISSUE THREAD

**Issue by mattto** [catapult-project/catapult#1846]
1) Go to https://chromeperf.appspot.com/alerts?sheriff=Service+Worker+Perf+Sheriff
2) Click Show Triaged
3) Results in https://chromeperf.appspot.com/alerts?sheriff=Service%2BWorker%2BPerf%2BSheriff&triaged=true

This page is just 500 Internal Service Error.

**Comment by anniesullie** [comment]
@chrisphn @qyearsley

**Comment by qyearsley** [comment]
Thanks for reporting!

I can reproduce this when not logged in -- Looking in the logs, I see:

```
NeedIndexError: no matching index found.
The suggested index for this query is:
- kind: StoppageAlert
  properties:
  - name: internal_only
  - name: sheriff
  - name: timestamp
    direction: desc
```
So, another index is required for fetching recent stoppage alerts for a particular sheriff, including triaged alerts, but not including any internal-only alerts (i.e. when the user is not logged in with a google account).

This index should be added. Meanwhile, that page is not a 500 error if you're logged in -- but for some reason I'm seeing no alerts at all on the triaged=true page, which seems incorrect since I see some without triaged=true, and the triaged=true page is supposed to include both triaged and untriaged.

**Comment by qyearsley** [comment]
Hi matto, so viewing the triaged stoppage alerts when logged out now works!
https://chromeperf.appspot.com/alerts?sheriff=Service%20Worker%20Perf%20Sheriff&triaged=true

But there's a separate bug here: + characters in URLs are encoded as %2B (URL-encoding of literal plus), but they should be interpreted as space characters and then encoded as %20. This is #1851.
