### ISSUE TITLE
Visual glitches in event boundaries at high zoom levels in Trace-Viewer

### ISSUE THREAD

**Issue by benthaman** [catapult-project/catapult#1865]
I've noticed three bugs that appear around the boundaries of events at high zoom levels. I'm reporting as one issue only since I guess that they all stem from the same miscalculation (rounding errors?) of event boundaries.

The glitches are demonstrated in the following video:
http://beta.suse.com/private/bpoirier/tv-bug/mini.mp4
Times between brackets below refer to the video.
1. When panning, the time scale and tick marks move fluidly but event boundaries jump. [00:00-00:23]
2. When zooming in, event boundaries jump. [00:24-00:35]
3. When selecting, the selection box may be over the end of an event (as it is displayed) but the resulting selection does not include the event. Conversely, the selection box may not be over the end of an event but the resulting selection includes the event. [00:41-00:53]

The impact of these problems is made worse by the fact that the drawing errors are not the same for two events that have a different start time but a duration such that the two events have the same end time. The two events used to demonstrate the glitches in the previous video have the following properties:

```
start 5609.031ms
duration 1572.869ms

start 5609.037ms
duration 1572.863ms
```

Hence they end at the same time and should be displayed as such. This is what initially tipped me off to these problems.

The trace data is available here
http://beta.suse.com/private/bpoirier/tv-bug/mini.json

It was exported to html using trace2html from git 417f85b
http://beta.suse.com/private/bpoirier/tv-bug/mini.html

**Comment by natduca** [comment]
Hmm yeah our behavior beyond a certain zoom level is known busted, and possibly unfixable in any reasonable amount of time.... I could imagine us clamping the zoom level so you can't get into this situation, but the underlying issue is that at these scales, we start bumping into numeric precision problems...

At least this is my instant read. I'd be curious about your reaction ... maybe I mistake what is going on here, or the clamping is a non starter?

**Comment by benthaman** [comment]
It seems to me like event boundaries are calculated differently for selection and for drawing; and that the former is right and the latter is troublesome. I'm not familiar with the code but I'd have a look at the two relevant sections and see if it's possible to reuse the implementation from the selection code in the drawing code.

**Comment by petrcermak** [comment]
I think that this is the same as #625: _"It seems that this issue could be solved completely by drawing the plot manually (call <tt>dt.xWorldToView(x)</tt> repeatedly) rather than using transforms (call <tt>dt.applyTransformToCanvas(ctx)</tt> once). While the change appears to have no impact on performance when applied to counter tracks, someone would need to confirm this for the other tracks as well."_

#633 fixed the issue for counter tracks: _"Note that this change completely fixes #625 (for counter tracks) as we draw the plot manually in view coordinates (to ensure constant line width) and thereby avoid using canvas transforms."_

**Comment by martinboehme** [comment]
Agree that this appears to be the same as #625 -- see my comments there.

**Comment by martinboehme** [comment]
Fixed by https://codereview.chromium.org/2917083002/.

Can someone close this issue?

**Comment by benshayden** [comment]
Thanks!

**Comment by benthaman** [comment]
For the record, I've tested again using the trace data from the first comment and can confirm the issue is resolved. Thanks.
