### ISSUE TITLE
ChromiumPerfStatus (i.e. Firefighter) is down. 

### ISSUE THREAD

**Issue by fmeawad** [catapult-project/catapult#1887]
https://chromiumperfstats.appspot.com shows the trace-viewer interface, and after it loads the data, nothing is displayed. The console is also empty.

**Comment by dave-2** [comment]
Fixed.

There were multiple problems:
1. Using http instead of https led to a redirect, causing App Engine to throw "Too many redirects." Now using https directly.
2. Mystery error where the updater stopped working mid-run, without any error in the App Engine log. This went away on its own ??
3. The backlog caused the URL size to hit the 2048 character urlfetch limit. Reduced the maximum backlog to 100 builds.
3. AppEngine outage caused gcloud deployments to be missing files. That's been fixed.
