### ISSUE TITLE
Unable to get a trace on my Pixel 2 (30mb trace uses 1.4gb RAM!)

### ISSUE THREAD

**Issue by rschoen** [catapult-project/catapult#1894]
I'm having various issues with tracing on my Pixel 2.

1. While tracing, the buffer % never goes above 0. Not an issue in itself, but seems to be indicative of an issue.
2. Tracing for more than a few seconds causes an OOM after finishing the traces.
3. Not 100% repro-able, but several times now I've successfully taken a trace only to have it be completely blank.

Stable Chrome 47.0.2526.110. I've heard of at least 1 and 2 happening to others with a Chromebook.

**Comment by fmeawad** [comment]
I was able to repro that issue,
Categories: *,-disabled-by-default-*
Config: SystemTracing:on, StateSampling:off
ChromeVersion: 47.0.2526.110 (same as described)

It creates a blank trace, but the trace includes all the process and thread information, investigating if it is a display issue or not.

Console errors:
Uncaught (in promise) Error: Error occured at /json/get_buffer_percent_full
    at chrome://tracing/tracing.js:308:255

P.S. Concerning the 0% while recording I think this is due to the intentional removal of communication between the tracing threads, we should update the UI to reflect that accordingly.

**Comment by fmeawad** [comment]
The trace is 13MB, so I doubt that it is empty, maybe a display issue then.

**Comment by natduca** [comment]
We need an owner to triage. @anniesullie any ideas?

**Comment by natduca** [comment]
@petrcermak could you look at the trace in this bug and do an analysis like you did in #1639 to help us understand the main culprits of what is causing oom?

**Comment by petrcermak** [comment]
Unfortunately, I don't have a Pixel 2.

@rschoen, @fmeawad: Could either of you please send me your trace so that I could investigate it?

**Comment by natduca** [comment]
@fmeawad can you file a fresh bug that is "this trace [attached] uses a gazillion bytes when loaded, wat". WE can then assign that to Petr, and close this bug.

**Comment by fmeawad** [comment]
Will do.

**Comment by fmeawad** [comment]
A new issue created to investigate the memory usage in trace-viewer.
