### ISSUE TITLE
Calculate differences in alerting with recent steppiness change

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#1898]
@qyearsley can you fix bench_find_anomalies and run it so we can look through alerting diffs? (filing this so we don't forget)

**Comment by anniesullie** [comment]
ping? we really need to make sure we're not missing important regressions with the new algorithm.

**Comment by qyearsley** [comment]
Blocked on #1414 (fixing bench_find_anomalies)

**Comment by qyearsley** [comment]
Putting results in this doc:

https://docs.google.com/document/d/1Qn2S4IM_od7wHKITuLhDjUeBv26aQeraYcLVTcunCxE/edit#

In the first run (started on Friday), there appears to only have been 18 alerts in the test bench data, so I'll I'll run the experiments once more before taking a look and deciding whether any change in default steppiness threshold would be good.

**Comment by qyearsley** [comment]
After running `bench_find_anomalies.BenchFindChangePoints` again, no results appeared and the following error was found in the logs:

```
Could not resolve arguments for pipeline.common.List#f5f1b9e49d584302bf0b60897852b495. Most likely this means there is a bug in the Pipeline runtime or some intermediate data has been deleted from the Datastore. Giving up.
Traceback (most recent call last):
  File ".../pipeline/pipeline.py", line 2050, in evaluate
    _pipeline_record=pipeline_record)
  File ".../pipeline/pipeline.py", line 589, in from_id
    pipeline_record.class_path, params['args'], params['kwargs'])
  File ".../pipeline/pipeline.py", line 1298, in _dereference_args
    (key, pipeline_name, _short_repr(args), _short_repr(kwargs)))
SlotNotFilledError: Slot "agxzfmNocm9tZXBlcmZyNwsSEV9BRV9QaXBlbGluZV9TbG90IiBhZjlmZGJiNDg2MTM0ZjBhODY0MWJkZmNhYmU2ZTkxYQw" missing its value. From pipeline.common.List(*args=[{u'slot_key': u'agxzfmNocm9tZXBlcmZyNwsSEV9BRV9QaXBlbGluZV9TbG90IiAwMmM5ODA4NWE2ZmE0YTRhODAzYTIwNzA3ZmI5ODdjMQw', u'type': u'slot'}, {u'slot_key': u'agxzfmNocm9tZXBlcmZyNwsSEV9BRV9QaXBlbGluZV9TbG90Ii... (133000 bytes), **kwargs={})
```

The error message suggests "Most likely this means there is a bug in the Pipeline runtime or some intermediate data has been deleted from the Datastore." It's possible that something went wrong this time but it's not a consistent failure? Trying again after decreasing the number of tests to gather sample data from by running:

```python
from dashboard import bench_find_anomalies
bench_find_anomalies.DeleteAllTestBenchEntities()
bench_find_anomalies._NUM_TEST_TO_BENCH = 1000
bench_find_anomalies.SetupBaseDataForBench()
```

**Comment by qyearsley** [comment]
Latest run is not succeeding either, and I'm seeing the error:

**Comment by qyearsley** [comment]
Update: after deleting all TestBench entities again (and deleting all _AE_Pipeline_Slot entities), I tried again, and I am again seeing the same error as before: SlotNotFilledError.

**Comment by qyearsley** [comment]
Update: After trying with only 10 tests, everything worked! But the results aren't very helpful.
I ran it again and finally noticed the following error in /_ah/pipeline/run:

```
Generator dashboard.bench_find_anomalies.SimulateAlertProcessingPipeline(*(u'steppiness_0_3', 5333159038681088L), **{})#98e4fc162b28452f81ad7eff33b665ef raised exception. AssertionError: 
Traceback (most recent call last):
  File ".../pipeline/pipeline/pipeline.py", line 2144, in evaluate
    self, pipeline_key, root_pipeline_key, caller_output)
  File ".../pipeline/pipeline/pipeline.py", line 1110, in _run_internal
    return self.run(*self.args, **self.kwargs)
  File ".../dashboard/bench_find_anomalies.py", line 146, in run
    test = test_bench.test.get()
  File ".../google/appengine/ext/ndb/key.py", line 572, in get
    return self.get_async(**ctx_options).get_result()
  File ".../dashboard/models/internal_only_model.py", line 26, in _post_get_hook
    assert False
AssertionError
```

This is most likely the cause of the failures before -- /_ah/pipeline/run isn't considered a privileged request, but the initial request for tests (when creating the TestBench entities) *is* privileged, and so it's fetching internal tests (which can not be gotten later).

Two possible easy fixes:
 - make all requests to /_ah/pipeline privileged. In this case we probably want to make /get_logs admin-only just in case internal test names are listed when viewing the bench_find_anomalies results.
 - make bench_find_anomalies only look at public data.

**Comment by anniesullie** [comment]
I like the first approach (making all requests privileged, with proper admin-only) best

**Comment by qyearsley** [comment]
I made the first change above; then we realized that the entire /get_logs endpoint shouldn't be made admin only because then people can't see bisect results. At most, GET requests to view /get_logs page should make sure the user is internal-only and only show results in that case.

**Comment by qyearsley** [comment]
Alright, now we have proper results from running the experiment in this doc:

https://docs.google.com/document/d/1Qn2S4IM_od7wHKITuLhDjUeBv26aQeraYcLVTcunCxE/edit#

A few quick conclusions from the results:
 * If we switched to min_steppiness = 0.4 we'd have about 20% more alerts than now, if we switched back to min_steppiness = 0.3 we'd have about 50% more alerts than now.
 * Many of the alerts in the lists of "unconfirmed" and "extra" alerts are the same when running the experiment with min_steppiness = 0.3, 0.4, 0.5; this is because it's comparing alerts found by running debug_alert.SimulateAlertProcessing with alerts in the datastore. There may be inconsistency there because the monitored tests or custom threshold configs could have changed, and debug_alert.SimulateAlertProcessing doesn't take into account alerts that shouldn't be fired because the ref build results move at the same time.

When looking at these results, the main thing we want to do is to check the "extra" alerts list of the steppiness = 0.3 and steppiness = 0.4 results to try to find any alerts that look like legit alerts that we missed due to the change.

Upon my examination, I found two types of "extra alerts":
 1. Noisy graphs, where it's good that we didn't fire alerts (e.g. https://chromeperf.appspot.com/report?sid=9e2b34d51657e4b3c9a4f7039c3a09c577d7f60086713e07c988cfa556ae9659&rev=380232)
 2. Jumps that occurred at the same time that we introduced ref build results on android (e.g. https://chromeperf.appspot.com/report?sid=1fc14d95ff7e1ff21e454b050920bf863889ce37ef6ce45df87b30f9277252d8&rev=377952). I'm not sure why no alert was fired there before, but in that particular case not having an alert was OK because the change that happened when ref build results were introduced is likely not a perf regression in Chrome.

Based on this, I haven't seen a compelling reason to change from min_steppiness = 0.5 back to min_steppiness = 0.3 (or 0.4), and it's still clear that the volume of alerts is much lower after that change.

@anniesullie, @rschoen, I'll be un-assigning myself from this in preparation for travel -- could you take a look at the results and then make a decision regarding this issue?
