### ISSUE TITLE
Catapult presubmit should only run pylint on projects with files in the change list.

### ISSUE THREAD

**Issue by Apeliotes** [catapult-project/catapult#1907]
Catapult presubmit should only run pylint on projects with files in the change list.

A change in telemetry should not run pylint on perf_insights for example.

**Comment by qyearsley** [comment]
SGTM -- I think the call to `input_api.canned_checks.RunPylint` can be passed parameter `white_list=input_api.AffectedFiles(file_filter='*.py').AbsoluteLocalPaths()`

**Comment by dave-2** [comment]
That may not be sufficient. The pylint code in depot_tools is commented with this:
  # We cannot use AffectedFiles here because we want to test every python
  # file on each single python change. It's because a change in a python file
  # can break another unmodified file.

My current plan is to add a separate PRESUBMIT.py for each project. An added benefit is that each project can customize which pylint checks they want to disable.

**Comment by dave-2** [comment]
OTOH having so many `pylintrc`s is pretty complex, and Pylint would miss cases where someone changes one project and it breaks another.

**Comment by qyearsley** [comment]
That's true, extra PRESUBMITs might be unnecessarily complex. They could potentially all use the same pylintrc.

If I understand correctly, the possible things that pylint won't catch if it only looks at some files are when you change/remove a function/class in one module, and there's another module (not changed in that CL) that depends on it that then breaks?

For the sake of having a faster PRESUBMIT, are we willing to accept that the PRESUBMIT pylint won't be able to catch this kind of problem, and we have to assume there are unit tests?

Also: Maybe we could also compromise, and say we want pylint to include all files that are in the same subdir as the modified files?

**Comment by dave-2** [comment]
Oh, I see. Some background was unsaid in this bug.

Quinten, I didn't know you were already working on whittling down the disabled checks in issue #1888. I do think we can be more ambitious than this, though -- the config files I saw internally at Google were significantly more strict than anything we see in Catapult or Chromium.

What Kari didn't mention in this issue is that the runtime of Pylint was blocking the CQ -- when Telemetry landed in to Catapult, it caused the lint time to exceed the 20-minute timeout. So this bug wasn't a suggestion, but rather an emergency -- that's why I rushed a patch through.

**Comment by qyearsley** [comment]
Makes sense! I'm definitely in favor of stricter checks in general. If presubmit time is increased by that much then I think per-subdir PRESUBMITs or a global presubmit that only runs pylint on a small subset of files are good solutions.

**Comment by dave-2** [comment]
Closing, use #1888 for stricter lint checks.
