### ISSUE TITLE
Clicking column headers to sort does not work within alert groups on /group_report.

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#1915]
Example:

https://chromeperf.appspot.com/group_report?bug_id=536126

Click "Test Suite", "Delta %", etc.

@chrisphn @qyearsley

**Comment by qyearsley** [comment]
Yep, it doesn't work within alert group (and it never has), but this would be really helpful. It would be a change [here](https://github.com/catapult-project/catapult/blob/7117fb020c410458330a49c601b8336e6aa5582a/dashboard/dashboard/elements/alerts-table.html#L690).

Currently, when sort() in alerts-table is called, it adds only group headers; in order to handle sorting within groups, I think we want it to sort within each group and then sort the groups.

**Comment by natduca** [comment]
Would it be useful to use tracing/ui/base/table and/or grouping_table in more parts of our code? Just random food for thought.

**Comment by jessimb** [comment]
Resolved in #2774
