### ISSUE TITLE
Perf Dashboard: use crrev.com to construct "git hash range" URLs? (WebRTC revisions don't have proper change log links)

### ISSUE THREAD

**Issue by tednakamura** [catapult-project/catapult#1922]
Chrome version: 49.0.2623.23 (Windows)
URL: https://chromeperf.appspot.com/report?sid=b5e61e4662b84c63656b7eb129ecafaadf8c796cebd29586310e7bdff0116372&rev=11384

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):
N/A

Please describe the problem:
The "Chromium Git Hash range" URL for the alerting graph point is https://chromium.googlesource.com/chromium/src/+log/7fd881743ce1bae98e79f57d30c6f6f2b72fc541..a2c55235cae5f16715911bff6109fe915a8085bf, which currently 404s. This is "expected" in the sense that the hashes refer to WebRTC commits, not Chromium commits. The individual hashes are visible via crrev.com, i.e. 
http://crrev.com/7fd881743ce1bae98e79f57d30c6f6f2b72fc541 and
http://crrev.com/a2c55235cae5f16715911bff6109fe915a8085bf

Is it possible to somehow use the crrev.com API to construct range URLs for the relevant repo instead of always pointing to https://chromium.googlesource.com/chromium/src/+log/?

**Comment by anniesullie** [comment]
@chrisphn @qyearsley

**Comment by qyearsley** [comment]
Currently, the dashboard handles revision range links by depending on the received data to say what repository the git hash belongs to (since for one test run the sender can report multiple revision types).

There's currently a bug in the way that the revision data is collected and sent for the client.webrtc waterfall -- it's sending `{"supplemental_columns": {"r_chromium": "919ff753760ccb2f80c8120f808586ff9214a9f1", ...}, ...}` -- that's why the link text is saying "Chromium Git Hash Range" instead of "WebRTC Git Hash Range".

When runtest.py is run for webrtc, it is passed `{"git_revision":  919ff753760ccb2f80c8120f808586ff9214a9f1}` in the build properties. In the past, it looks like runtest.py was assuming that the webrtc revision would be passed as "got_webrtc_revision" in the build properties (See [the place in runtest.py where this is checked](https://code.google.com/p/chromium/codesearch#chromium/build/scripts/slave/runtest.py&q=runtest.py&sq=package:chromium&type=cs&l=529)).

Do you know if using "git_revision" is correct there? I could also update runtest.py to use "git_revision" for webrtc rev if the "project" property is "webrtc". WDYT Ted?

**Comment by tednakamura** [comment]
Hmm, I'll bring this up at my next 1x1 with @hkjellander and one of us will reply back.

**Comment by hkjellander** [comment]
I'll see if I can fix this on the recipe side, stay tuned.

**Comment by qyearsley** [comment]
Sounds good :-) Once the WebRTC commit hash is sent using a different key like "r_webrtc", I'll update the associated URL so that the change log viewer is correct.

**Comment by qyearsley** [comment]
@hkjellander, any updates about the way WebRTC versions are/will be sent to the perf dashboard?

**Comment by hkjellander** [comment]
Sorry for the slow response. It should be doable to make sure the standalone WebRTC bots just include the "r_webrtc" key in the uploaded JSON. I filed https://bugs.chromium.org/p/chromium/issues/detail?id=596883 to track this since it's a change on our end (and I don't want to have even more bug trackers to keep track of).

**Comment by qyearsley** [comment]
Sounds good, let's track this there.
