### ISSUE TITLE
14MB Trace takes 1.4GB ram to load in trace-viewer

### ISSUE THREAD

**Issue by fmeawad** [catapult-project/catapult#1930]
https://drive.google.com/open?id=0B3PSJY916EOjYVpnbklHekU4VDg

This trace peeks at ~1.4GB to load and stabilizes at ~1.2GB, it fails to load on low memory devices or when there is memory pressure.

(Originally incorrectly reported as an issue with Pixel 2 in #1894)

**Comment by petrcermak** [comment]
I analyzed the memory used by Trace Viewer on @fmeawad's trace and found that the total size of the __V8 heap after import was 676 MiB__:

![with_alerts](https://cloud.githubusercontent.com/assets/2546601/12723630/225ef342-c902-11e5-9693-abf7a387f78b.png)

I suspect this is due to the fact that the model contains __446,423 <tt>ThreadSlice</tt> events and 227,754 <tt>CounterSample</tt> objects__. Consequently, the thread slices retain 367 MiB (54% of the heap).

Given the large number of events, the huge memory footprint seems pretty much unavoidable. Nevertheless, I investigated the issue a little further and dived into the structure of the thread slices. They have the following fields:

  * Timing information (5 numbers, each 16 bytes in size, most probably cannot be removed, random thought: store default values on the prototype)
  * Category string (not an issue because it's shared across thousands of slices)
  * Title string (clearly cannot be removed)
  * Links to in-flow events, out-flow events, parent slice, sub-slices and parent container (removal would probably make the UI unusable due to extra computations)
  * Args (these can very rarely be quite large, e.g. 1024 characters for base64 encoded image urls)
  * Associated alerts (empty <tt>EventSet</tt> objects)

In fact, __<tt>EventSet</tt> instances occupied 164 MiB (24% of the heap) even though the vast majority of them was empty__ (namely the associated alerts of all events). To determine the impact of associated alerts on the heap size, I commented out the <tt>associatedAlerts</tt> field in <tt>tr.model.Event</tt> and measured the V8 heap size after import again. __Without associated alerts__, the total was __515 MiB (24% improvement)__:

![without_alerts](https://cloud.githubusercontent.com/assets/2546601/12725555/440a02da-c90b-11e5-8e93-08cfc5d46371.png)

I'm not suggesting that we completely remove associated alerts from all events, but it might be worth _not_ setting the field at all if there are no alerts (rather than create lots of empty <tt>EventSet</tt> objects). This potentially applies to other parts of Trace Viewer.

@fmeawad, @natduca: WDYT?

**Comment by fmeawad** [comment]
Hey @petrcermak, Great analysis, I wonder if there is other Objects like the `EventSet` objects that can be eliminated as well? I am curious tho on why this trace has more `ThreadSlice`s and/or generates more objects than any other trace we have. Let me know if you have any insights on that.

**Comment by petrcermak** [comment]
I assume there will be lots of other objects like <tt>EventSet</tt> (that take up non-negligible amount of memory despite being empty), but the challenge will be to determine __whether it's worth the extra code complexity__ (checks for undefined value, lazy construction, etc.). I think it's all about determining how often the object is indeed empty.

For example, is it really the case that events hardly ever have associated alerts? If the answer is "yes" (which seems to be the case), then it's probably worth the extra complexity. Moreover, it turns out that __the <tt>associatedEvents</tt> field is accessed/modified in only 5 places__ in Trace Viewer, so I'll give this a go...

**Comment by petrcermak** [comment]
__Lazy initialization of <tt>tr.model.Event.associatedAlerts</tt>__ indeed reduces Trace Viewer's memory usage (https://codereview.chromium.org/1657253002/), namely __from 676 MiB to 519 MiB (23% improvement)__ on the above trace:

![lazy_initialization](https://cloud.githubusercontent.com/assets/2546601/12747509/4752bfa4-c99c-11e5-9030-1c883a5cdd6c.png)

**Comment by natduca** [comment]
Should we mark it closed, or leave it open and available for other folks to do more triage?
