### ISSUE TITLE
Many style issues and UTF-8 errors preventing uploading of minor change

### ISSUE THREAD

**Issue by picksi** [catapult-project/catapult#1982]
I have made a small change to results-template.html. This file contains a JS string that contains '&plusmn;'  (line 1317) which is too long (at >90 chars).

When running git cl upload the pre-submit-check reports the over-long line error, but at some point the &plusmn; has been expanded to the non-UTF-8 character (±). This makes the join statement on line 172 of js_checks.py fail:

  File "/usr/local/google/code/catapult/catapult/catapult_build/js_checks.py", line 172, in RunChecks
    _MakeErrorOrWarning(self.output_api, '\n'.join(error_lines)))
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb1 in position 73: invalid start byte

So the upload is aborted.

If the &plusmn; is replaced with String.fromCharCode(0x00b1) the cl upload doesn't crash, but reports about ~100 errors.

I will try to find time to clean up this file if it is as error-full as the pre-submit suggests, but I am worried that this issue may be present in other new catapult'd files.

**Comment by picksi** [comment]
Rather wonderfully GitHub has expanded the HTML entity into the symbol in the above bug report.

The first line should read:

This file contains a JS srting that contains '& p l u s m n ;' ... but without the spaces :)

**Comment by qyearsley** [comment]
The UnicodeDecodeError seems like a bug in /catapult_build/js_checks.py that should be patched -- https://codereview.chromium.org/1673353002 would fix that.

Meanwhile, the reason why results_template.html has so many JS lint errors is because previously (in Telemetry there was no JS linting run on presubmit, but now that it's in catapult there is.

I'd be happy to clean up that file in particular, although it's certainly true that touching other HTML files in catapult/telemetry may result in presubmit warnings unrelated to the CL.

**Comment by natduca** [comment]
The results_template.html is a horror show. We've long wanted to get rid of it in favor of a better output format for telemetry. @nedn and I have talked about this in the past. I think as we contemplate system health benchmark and dashboard and such, we should come up with a better solution to this whole space. (eventually, given that we're all swamped)

**Comment by qyearsley** [comment]
Alright -- given that, is it OK to just add that particular file to the presubmit check blacklist?

**Comment by qyearsley** [comment]
That file was added to the blacklist; AFAIK there are no more planned action items for this bug, so I'll close it now.
