### ISSUE TITLE
Add update_d8_version.py script

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2]
We should have a script that fetches the right binaries from the buildbots and patches them in, or just syncs the v8 code at the given revision and builds them itself.

We could either run this regularly as a cron job (see https://code.google.com/p/chromium/codesearch#chromium/build/scripts/slave/recipes/catapult_cron.py) or make it so that we can run these as a tryjob on an as-needed basis.

We already have linux, windows, and mac slaves, so the buildbot part of this is not blocked, but I think ideally we would also have d8_runner use the new binary dependency system @Apeliotes is working on.

@nedn @natduca

**Comment by zeptonaut** [comment]
I'd love to keep D8 up-to-date to enable us to use ES6 features as they roll out. I'm going to look into how difficult this is.

**Comment by nedn** [comment]
Keeping as up-to-date as possible is not our strategy. Generated trace-viewer files has to support browsers up to stable, so we want d8 to be as up-to-date as stable chrome.

**Comment by zeptonaut** [comment]
Yep! Sorry - that was a really poor use of the phrase "up to date". "Up to stable" was more what I meant.

**Comment by anniesullie** [comment]
Some technical notes:

1. [Here](https://github.com/catapult-project/catapult/blob/master/catapult_build/run_dev_server_tests.py#L128) is some example code that finds out current chrome stable version
2. You can run your script on a nightly cron job [here](https://code.google.com/p/chromium/codesearch#chromium/build/scripts/slave/recipes/catapult_cron.py) (currently linux-only)
3. Adding other platforms to run cron jobs can be done [here](https://code.google.com/p/chromium/codesearch#chromium/build/masters/master.client.catapult/builders.pyl&l=31) -- you'd reuse `mac_slave_pool` and `win_slave_pool`

**Comment by zeptonaut** [comment]
After chatting with @anniesullie about this yesterday, it sounds like we could do this in a few logical steps:

1. Fetch the version number of Chrome stable from Omahaproxy
2. Fetch the version number of v8 that corresponds to Chrome stable from Omahaproxy
3. Clone the v8 git repository with a git tag matching the version number that we just fetched
4. Build v8 using `depot_tools`. This will require being on whatever platform you're building v8 for.
5. Check in to Catapult the binary that you just built.
6. Repeat for other two platforms.

After I have something like this working, I'll talk to @Apeliotes about how to go about working this into the dependency management framework that she's building, as well as how to use the slaves to do the builds rather than having to repeat this process on three operating systems.
