### ISSUE TITLE
Spammy warning messages for missing interaction record labels

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#2025]
The logs of benchmarks using timeline based metrics are getting littered with too many spammy warnings about: 'TimelineBasedMetric should create the interaction record label for the value themselves'.

**Comment by anniesullie** [comment]
@eakuefner @nedn

**Comment by nedn** [comment]
Sorry, this is the left over from crbug.com/539381 :p

**Comment by eakuefner** [comment]
@perezju As you've seen by now https://codereview.chromium.org/1709053002/ kicked up quite the storm :)

I'm fine with the changing the wording of the message part of the CL, but modifying smoothness requires a bit more discussion.

Let me ask one question that probably won't make sense first, and then attempt to provide the context for what's happening here.

Are you using the smoothness metric outside of the context of the Smoothness Measurement in `tools/perf`? If so, that explains why you are seeing these IR label warnings. My guess is that you have a benchmark that doesn't call `SetLegacyTimelineBasedMetrics`, so all metrics, including smoothness, are being run.

Back story as promised:

TimelineBasedMeasurement uses a concept called a results wrapper, which nedn@ above is correct that we were in the process of removing. Roughly, a results wrapper wraps a results object and intercepts values before they are added to the results. The default results wrapper, `timeline_based_measurement._TBMResultWrapper`, adds the interaction record label to the value if and only if the value does not itself specify a label, and we added the warning after the fact to let us be able to grep for any values that did not add an interaction record label. Once all values specify their own interaction records, we no longer need `_TBMResultsWrapper`.

The Smoothness TimelineBasedMetric is used primarily by the Smoothness Measurement, which is distinct from TimelineBasedMeasurement for legacy reasons.

Because smoothness is mature enough that a lot of people are interested in it, we wanted to be sure that the metric names wouldn't change when we landed the TBM Everywhere project that puts interaction record labels onto the dashboard for benchmarks that use TimelineBasedMeasurement. The way that we did this was by implementing a custom results wrapper that does _not_ insert the interaction record label. That is why you will see that the smoothness measurement constructs TimelineBasedMeasurement with the SmoothnessResultsWrapper, here: https://code.google.com/p/chromium/codesearch#chromium/src/tools/perf/measurements/smoothness.py&l=56

**Comment by perezju** [comment]
> Are you using the smoothness metric outside of the context of the Smoothness Measurement in `tools/perf`? If so, that explains why you are seeing these IR label warnings. My guess is that you have a benchmark that doesn't call `SetLegacyTimelineBasedMetrics`, so all metrics, including smoothness, are being run.

Got it. Yes. This is not intended, but probably happening as a side effect of #2126. I'll write up a new CL to fix both of these issues, and *not* touching the existing smoothness metric.

**Comment by perezju** [comment]
I think there is nothing else to fix on the telemetry side, but please see: https://codereview.chromium.org/1785683002/

Closing this one.
