### ISSUE TITLE
Dashboard bug filing not working with monorail

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2032]
I deployed https://codereview.chromium.org/1663603002/ at https://dev-sullivan-49cd0cfd-dot-chromeperf.appspot.com/ but bug filing isn't working properly. Details on code review.

**Comment by anniesullie** [comment]
I changed the server on https://codereview.chromium.org/1663603002/ to monorail-prod and deployed. I successfully filed a bug, but I'm concerned about the presubmit error on that cl (see comments in cl). Quinten, can you take a look? Also, what is the test plan for the integration?

**Comment by qyearsley** [comment]
So, when testing/experimenting last week, I was hoping that we would have the flow using user credentials (filing new bugs) and the flow using service account credentials (posting updates) both working -- this week, working with Sheng, we found that the service account credentials would work so I changed issue_tracker_service to always use that -- but file_bug_test is still making the assumption that user credentials are used.

I *believe* that this is just an issue of the tests, and deploying should work for filing bugs etc.; the errors that are logged after deploying your CL could be (mostly?) related to the post-bisect-results-to-dashboard change, which went in yesterday.

**Comment by qyearsley** [comment]
Current status: Bug filing is now working, and there's a CL to make it use user credentials (https://codereview.chromium.org/1712423002); I'll wait on closing this bug until that CL is committed.

Bug filing didn't work originally after deploying the CL on Feb 19 morning because that CL was set up to post to the staging instance of monorail.

Regarding test plan for integration: Besides verifying that bugs can be filed (by filing bugs via the UI on improvement alerts) and checking that updating bugs with bisect results works, I didn't have a plan; what would a better test plan for integration have been?

**Comment by anniesullie** [comment]
Thanks, Quinten! I think it's okay to close this but everything would be much cleaner if we quickly implemented the follow up work in #2042.

As far as a test plan for integration, I think a couple of things would have made this go more smoothly:
  * An actual list of things that need to be tested (every place the dashboard integrates with crbug, so we know whether all of it works, or just part, and it's written down so that I could have looked at it while I was working on getting the dashboard bug integration back up outside of PST working hours)
  * A clear plan for when we would update the dashboard after the monorail migration, announced to users. It was awkward for us that the monorail migration was scheduled to finish after PST working hours, which meant that if we waited until working hours all APAC and EMEA sheriffs would have experienced a day-long outage. We should have either: 1) planned for someone to finish the migration outside of business hours or 2) clearly announced that we are having planned downtime because of the timing of the migration.
  * Picked a different date for turning on posting results from bisect directly from perf dashboard, since it would be easier to figure out which problems were caused by which change that way.

Note that while I'm making these suggestions for how we could do better in the future, as a reviewer on both the monorail CL and the post results CL, I take full responsibility for not bringing up these points **before** the monorail migration date. Apologies for not being more proactive!

**Comment by qyearsley** [comment]
Aye --

1. In retrospect, if I had formally made a list of things that were to be tested, maybe I would have remembered that the issue tracker was used for other things (getting last bug comment time for bisect_fyi, getting lists of bugs for associate_alerts, and main page)

2. I was actually unaware how/when the infra team were going to do the migration, because I only glanced at the first post in [the chrome-team mailing list post](https://groups.google.com/a/google.com/forum/#!topic/chromebrowser/jQ75G2dgu2Y), but didn't fully read [the FAQ document](https://docs.google.com/document/d/1Jwm6oMRYJI4LSVnxkTHpp3xnpBu687IBDeAZTmyjzQs/edit#).

3. Definitely -- in retrospect, allowing the post-bisect-results change to go in on Thursday was a big oversight, since I knew that the monorail change was on Thursday too.
