### ISSUE TITLE
Report page tooltips not working after report page de-jinjafication

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#2091]
This started after https://codereview.chromium.org/1709073003/.

To reproduce:

1. Navigate to: https://clean-qyearsley-7c659faa-dot-chromeperf.appspot.com/report?sid=46b8933cd612c134400b73001067c3fe9eac70eb82d651c56030d85b4b1ca48d
2. Hover over any point; note no tooltip
3. Hover over alert icon; note JS error in console

At first, the revision info was not being set on the report-page element as expected because of a minor typo, which was fixed in https://codereview.chromium.org/1757633002/. Now the revision info is set on report-page, but apparently not on chart-container.

@anniesullie I couldn't figure out what was wrong before going home today -- could you take a look in the morning?

**Comment by anniesullie** [comment]
Thanks for the detailed bug report, Quinten! It turned out to be an issue where the tooltips only work in certain cases (on /group_report, on /report if you manually add charts) and not in others (on /report when you load a chart from sid param) so it was very helpful to have an exact repo.

Fix in https://codereview.chromium.org/1756153002/

**Comment by anniesullie** [comment]
This is now **fixed**
