### ISSUE TITLE
Alerts page shows infinite spinner when user can't access alert rotation

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2153]
Steps to reproduce:
1. Open an incognito window, do not log in
2. Go to https://chromeperf.appspot.com/alerts?sheriff=WebRTC%20Perf%20Sheriff&sortby=test&sortdirection=down&improvements=true

You'll see the spinner spins forever. If you go into the net panel, you'll see a request to /alerts with the content:
`{"error": "Sheriff \"WebRTC Perf Sheriff\" not found."}`

This content should be surfaced in the UI.

@chrisphn @qyearsley can either of you take a look? Also maybe add something to the error message about "Please check that you are logged in"?

**Comment by qyearsley** [comment]
Ah, excellent, now I can reproduce it too. Definitely should be surfaced to the UI

Furthermore, after alerts-page gets a response from the XHR to /alerts, it does set the `error` property at [alerts-page.html:239](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/elements/alerts-page.html#L239).

But, the error message isn't shown now because it's hidden inside of `<template if="{{loaded}}"></template>` If `loaded` is set to true when the error is received, then the error message should be shown. Will deploy a demo to test.

**Comment by qyearsley** [comment]
Tried just setting loaded = true when an error response was received.

https://dev-qyearsley-eed7429a-dot-chromeperf.appspot.com/alerts?sheriff=WebRTC%20Perf%20Sheriff

In that version, the error is shown, but some other useless UI elements are also shown and there's no clear suggestion to log in.

**Comment by anniesullie** [comment]
I think it's fine to move the error message so that we can separate it from the useless UI elements better. Suggestion to log in should just be a string change?

**Comment by chrisphn** [comment]
Same error on local instance without any alerts.

**Comment by qyearsley** [comment]
Fix verified (by following the steps to reproduce in the bug report).
