### ISSUE TITLE
ChromeRendererHelper is unable to find renderer thread for minimal traces w/o cat "cc" enabled

### ISSUE THREAD

**Issue by nyaxt** [catapult-project/catapult#2178]
Blocking #2081

We would not want to require "cc" category in order to run FirstPaintMetric.
However, `ChromeRendererHelper.isRenderProcess` currently returns false when "Compositor" thread is not found.
If we code FirstPaintMetric using ```chromeHelper.rendererHelpers[]```, it can't find the renderer processes if the "cc" category is disabled.

Is this intended? or can I simply drop the "Compositor" requirement from `ChromeRendererHelper.isRenderProcess`?

**Comment by nedn** [comment]
@benshayden

**Comment by benshayden** [comment]
This code precedes me, so I'll be doing a bit of guessing and consulting Nat.

I can see how it might be convenient for ChromeRendererHelper to guarantee that it always has both a main thread and a compositor thread.

I can also see how there might be situations where we want to be able to use the helper even if we didn't trace cc (because it's super noisy), or if we only traced cc so that we don't have the main thread.

It seems to me like we need to make ChromeRendererHelper more flexible, and make sure that all of the users of ChromeRendererHelper check that the thread that interests them actually exists.

For example, it looks like InputLatencyAsyncSlice is the only user of ChromeRendererHelper.compositorThread. Funnily enough, it already checks that the compositor thread exists before it uses it, suggesting that the guarantee that ChromeRendererHelper always has both a main thread and a compositor thread was unintentional.

Started https://codereview.chromium.org/1839673002

**Comment by benshayden** [comment]
If you want, in the mean time, you can bypass the helpers and use the model and its processes and threads directly. The helpers are designed such that it should eventually be trivial to switch code from using the model directly to using the model helpers.

Eventually, though, we need to reconcile your metrics with the LoadExpectation, though that can happen after you land your metrics.

**Comment by benshayden** [comment]
@nyaxt Can you close this issue if that commit helps, or let me know if there's anything else needed here?

**Comment by nyaxt** [comment]
Thanks! The commit fixed my issue!
