### ISSUE TITLE
Refactor oodles of values into diagnostics

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#2183]
Currently, the SH metrics generate lots and lots of values: per-UE values, throughput, smoothness in addition to the per-trace responsiveness and efficiency. Soon, long-idle-tasks.

After discussion with @natduca and @eakuefner , these metrics should be refactored to only output the per-trace responsiveness, efficiency, and hazard values. These values' diagnostic dictionaries should include the per-UE values, animation metrics, long-idle-tasks, etc. structured in such a way that the dashboard could, in a debug mode, extract and graph the sub-metrics as Values. So a debug-mode dashboard could value-ify the sub-metrics.

Does that sound right?

**Comment by benshayden** [comment]
Related: #2180 .

**Comment by eakuefner** [comment]
In a word: yes.

I intend to write a lot more about this and link it from the TBMv2 best practices doc (which I may end up splitting from the migration guide since with our close work on V8 we're seeing a lot of best practices emerge), but I think your description is a good summary of what we arrived at earlier.
