### ISSUE TITLE
Research javascript asynchronous event testing frameworks

### ISSUE THREAD

**Issue by Apeliotes** [catapult-project/catapult#2241]
Consider whether there are asynchronous event testing frameworks that make sense for dashboard testing.

See https://codereview.chromium.org/1880283003/ for an example that could use one.

**Comment by Apeliotes** [comment]
Possible option: [Jasmine](http://jasmine.github.io/)

**Comment by Apeliotes** [comment]
(It may be overkill and might not work with our current testing setup though. Should be looked into further.)

**Comment by anniesullie** [comment]
@natduca @zeptonaut: does trace-viewer have a pattern for unit testing asynchronous events?

**Comment by eakuefner** [comment]
It seems like there are two separate issues here:

1. How to write an asynchronous test, which is a functionality issue, and
2. A framework that provides a convenient way to assert things about callbacks without manually invoking them (e.g. by chaining and resolving promises), which is an ergo issue.

For 1., Charlie and Nat probably know more, but off the cuff here, thinking through what I would do if I wanted to make something like `/mre/function_handle.html` async and unit tested, I'd probably fake out `/tracing/base/xhr.html` and then do what Fowler describes in http://martinfowler.com/articles/asyncJS.html using promises.

The parts where I can see this differing for what we'd want to do on the dashboard side are

a. Dashboard probably does XHRs a different way, though as long as there's a wrapper mocking should work
b. If Dashboard has a different browser support expectation than tracing (which we've been saying is Stable for ES6 purposes), promises might not be available.

It seems like Sinon is a standard mock extension for Chai which might make it easier to write fakes if people like that. Personally I think it looks useful. http://sinonjs.org/

For 2., we're already using Chai and we had talked about switching to Karma in the past. Two more things Fowler mentions in the article are that [`chai-as-promised`](https://github.com/domenic/chai-as-promised/) exists, so we could probably check that into `third_party` and start using it immediately, and that Mocha currently natively supports promises, so you can do away with all of this stuff totally!

Of course, switching to Mocha is a longer-term project that we've talked about in the past; one thing about Mocha is that 

Probably we'd want Chai+(optionally Sinon)+Mocha because Jasmine only supports the BDD style of description/assertion (`describe(it(expect().toBe()...)`) where we prefer the TDD style which Chai supports (`suite(test(assert.equal()))`).

**Comment by zeptonaut** [comment]
I don't know of any asynchronous testing that we do in trace viewer. Because everything's on the client, it just doesn't come up that much.

**Comment by benshayden** [comment]
tracing's unit testing system already allows tests to return Promises, which have a bit of a learning curve (I had to fix some broken Promise-based tests in find_controller_test recently), but [async/await](https://github.com/catapult-project/catapult/issues/3417) makes async js very easy. See histogram_set_table_test.html in [this CL](https://codereview.chromium.org/2747453003) for example.

**Comment by eakuefner** [comment]
Yup, I think this bug is an antique.
