### ISSUE TITLE
Perf Dashboard: Test & other search boxes don't respect "." and "_"

### ISSUE THREAD

**Issue by vmiura** [catapult-project/catapult#2253]
Chrome version: 49.0.2623.108 (Linux)
URL: https://chromeperf.appspot.com/report

It's difficult to search for our benchmarks that have a format such as "smoothness.gpu_rasterization.top_25_smooth".

Examples:
- Typing "smoothness.gpu" will show results matching either "smoothness" or "gpu", for example "smoothness.maps" and "gpu_perftests".
- Typing "gpu_raster" will similarly show results that match either "gpu" or "raster", for example "rasterize_and_record_micro...".

**Comment by anniesullie** [comment]
@Apeliotes another one to look at. This is done on purpose here, I have no idea why: https://github.com/catapult-project/catapult/blob/a8a6fb7ea065c2df8ae129ad05ac80ba6ae7cc3a/dashboard/dashboard/static/autocomplete.html#L15

If you can't find a reason or regression, should definitely remove at least ._- from that regex. I think the space allows you to search for multiple things? Still seems pretty unexpected to me. @dave-2 as well, since he usually has good feedback on UI issues. Anyone have a use case for this feature?

**Comment by benshayden** [comment]
This seems to have been fixed.
