### ISSUE TITLE
py_vulcanize should not depend on Polymer 0.5

### ISSUE THREAD

**Issue by Apeliotes** [catapult-project/catapult#2265]
GetInlineScriptContentWithPolymerizingApplied relies on use of the polymer-element tag (specific to Polymer 0.5). This is hacky, and blocking the polymer migration to 1.0.

**Comment by Apeliotes** [comment]
@anniesullie

**Comment by nedn** [comment]
@natduca 
py_vulcanize should not know anything about polymer.

**Comment by eakuefner** [comment]
(Can we switch to using vulcanize if we make Node work on win?)

**Comment by nedn** [comment]
Ethan: that's a different experimental effort, which I think we shouldn't block this effort on it.

**Comment by eakuefner** [comment]
Fair enough, just thinking out loud :smiley:

**Comment by anniesullie** [comment]
Looks like this is the commit where it's added: https://github.com/catapult-project/catapult/commit/2a631e13d6ec3077b421589de1f69346db379a3d

Since Nat is out, @nedn do you have context on the high-level of what this is trying to accomplish?

**Comment by nedn** [comment]
I think this is required to deal with polymer 0.5, in which you don't have to explicitly specify the name of the template you want to register with "Polymer({...})". Since py_vulcanize strips out all the script tags of html files & put all the js content together in one file or one giant <script></script> tag, there gotta be some logic to automatically add the template name to the Polymer element registration.

With polymer 1.0, specifying the template name is required, so this is no longer a problem.

**Comment by Apeliotes** [comment]
This should be done on the polymer10-migration branch as part of the current hackathon.

**Comment by anniesullie** [comment]
This was done on the branch in https://codereview.chromium.org/1924283002/
