### ISSUE TITLE
Document and organize trace events required by metrics

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#2306]
Ideally, all metrics would document which tracing categories they require, and the requirements would make sense, and the categories would not contain too many events for the metrics. Are those the goals? Are they *all* the goals? Are they the *right* goals? @vinterstum 

The responsiveness metric, in particular, requires the input category if the trace might contain user input, [navigation, blink.user_timing] if the trace might contain a Load, and blink if the trace might contain a CSS animation. These categories are required to find UserExpectations, so they are also required by other metrics that use UEs, such as hazard/input-readiness.

The efficiency metric requires the top-level category in addition to the categories required by the responsiveness metric. Currently, it also requires toplevel.flow and ipc.flow (both disabled-by-default) in order to find Response/Animation associatedEvents, though that might change when Frameblamr is done.

Should there be a single category that captures everything that UEs (fka RAIL) might need, or would that be too spammy in some situations?

What else should be done here?

**Comment by vinterstum** [comment]
My current thinking is, coming out of the TBMv2 filters / tracing pre-filtering discussions:

I think we want the TBMv2 metrics to be explicit about all of the category:event pairs they rely on. Then this could be used for a built-in constraint in the Catapult importer, and could also be used to generate categoryfilters/pre-filters TraceConfigs, for use with Telemetry and Slow Reports.

Orthogonally: It feels subtly wrong to me to switch categories etc around because they're too "chatty", but maybe it's what we're stuck with for practical reasons, since we don't have any kind of level-of-detail system (yet?).

**Comment by benshayden** [comment]
#1818
