### ISSUE TITLE
EventSet shouldn't be an object that acts like an array

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2314]
`EventSet` is in a really strange state: outwardly, it presents itself as both an `Array` and an `Object`. 

It does this by having numeric properties, like:

``` javascript
{
  0: new PowerSample(1, 1),
  1: new PowerSample(2, 2)
  // etc.
}
```

and, because you can use the bracket operators to get a Javascript property, doing eventSet[1] returns something reasonable.

The weird result of this is that, even though it allows array indexing into it, it offers only the Array-like methods that it implements itself (`indexOf`, `push`, etc.). 

Probably what it makes sense to do is to have an inner `events_` array, allow others to call push() on the `EventSet` which in turn pushes onto the inner `events_` array, and allow returning that inner `events_` array for anyone that needs to perform some action on it (probably with a strongly worded warning to please not modify it).

I previously raised all of this in #1015, but we never fixed the problem because we were short on time :(

**Comment by zeptonaut** [comment]
@Alex319, would you be willing to take a look at this?

**Comment by Alex319** [comment]
Okay. I assigned it to myself

**Comment by Alex319** [comment]
The real question here is: is there a way to make this change which preserves the existing interface, or will we have to go back and change all the callers?

**Comment by benshayden** [comment]
While you're at it, do you want to split the set-like functionality into a base class, and the event-specific functionality into a subclass? ValueList might want to use the Set base class. @eakuefner

**Comment by Alex319** [comment]
That might make sense; what do you mean by the event-specific functionality? I can certainly see that things like getEventsOrganizedByType and such would be event-specific functionality and things like equals and intersectionIsEmpty would not be. But one thing that I'm not sure about is whether the GUID related stuff - like pushing only unique events where "uniqueness" is defined by GUID - would be considered event-specific. I'll look at the ValueList more and try to put together a design doc for this.

**Comment by benshayden** [comment]
Yeah, we're going to be added GUIDs to Values, so the GUID-defined uniqueness would be on the base Set class.

**Comment by zeptonaut** [comment]
A clarification: `Array` used to not be subclassable, but I believe it's completely fine to subclass an array in ES6.

Question: what is it that makes `EventSet` need to provide random access to its underlying array (`[]` operator)? Looking at [its usage](https://code.google.com/p/chromium/codesearch#search/&q=f:catapult/tracing%20selection%5C%5B%20f:.html&p=3&sq=package:chromium&type=cs), I see a few instances where the first element of the array is accessed, a few instances where we're just using the random access operators and an index to iterate, and that's about it. 

Another really nasty thing about `EventSet` is that it's near impossible to tell where it's used, though, which makes these type of refactorings pretty difficult. [This code search](https://code.google.com/p/chromium/codesearch#search/&q=indexof%20f:catapult/tracing%20%20selection%20-f:polymer%20-f:min%20-f:test_data&p=3&sq=package:chromium&type=cs) suggests that the `indexOf`, another one of `EventSet`'s array-like methods, might not even be used.

Maybe what it makes sense to do is to go through `EventSet`'s methods and try to grok why each one is there and, if it's unnecessary, to get rid of it. `indexOf` might provide a good starting point for one to potentially look at axing. @benshayden @Alex319 what are your thoughts?

**Comment by Alex319** [comment]
Thank you. I think that would be a useful thing to do.

**Comment by benshayden** [comment]
I don't have an informed opinion about subclassing Array or most of the other design decisions in Alex's doc. I don't know if anybody has the bandwidth to redesign Set/EventSet from the ground up. An iterative approach might be easiest. Removing indexOf might be a good second or third step, but I think that a good first step would be to split the guid-based unordered set functionality into a base class without changing the APIs, both to unblock TBMv2.1 and to make it easier to see and reason about the set functionality separately from the event-specific functionality as you go about the other parts of the refactor. ValueSet doesn't need order, though it's currently implemented as an array.

If I were going to write it (not trying to be prescriptive, just descriptive of another half-baked design :-), I'd have the base UnorderedSet use a dict to map from guid to element, and implement

 * add(element)
 * addSet(set)
 * get length
 * find(id) so that ValueSets can patch up value_refs (think id_refs for Values)
 * contains(element)
 * intersection(set)
 * toArray() with comments that the order may not be stable, and modifying the returned array will not modify the set

An OrderedSet subclass can add an array field to maintain the order (maybe implementing array-like methods as necessary, maybe toArray() returns the array field directly with a warning to not modify it, idk), then EventSet can subclass OrderedSet (implementing bounds and event organization).

Implementing OrderedSet as a hash map (aka UnorderedSet) plus an array is standard CS (except in languages named "Lisp"). EventSet is just weird in that it tries to be the array (which it fails to do), and only stores booleans in the hash map. Being the array and only storing booleans in the map seem to me to be the fundamental design flaws, though I imagine they weren't design decisions, it just evolved that way. Subclassing Array would solve the failure to be an array, but EventSet might not really need to be an array, as you're seeing when you suggest getting rid of indexOf(). The standard design is standard for some good reasons.

Huh, I guess I do have some opinions. Sorry about that. :-}

**Comment by Alex319** [comment]
I think that makes sense as a first step. It seems pretty clear that we can split off the event specific functionality from the general unordered set functionality.

**Comment by zeptonaut** [comment]
Is there any reason that we can't just make it an [ES6 `Set`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) with some extra functionality on top of it? Rolling our own `Set`/`UnorderedSet` base class seems like it'd just be creating some extra work for ourselves, especially given the fact that the ES6 `Set` already contains almost all of the methods described above.

**Comment by Alex319** [comment]
There actually is one place where the EventSet ordering is used. It is used in find_controller.html, where it stores the list of hits on the search box as an EventSet, and this is ordered (you can step through them one at a time with the arrow keys)

**Comment by Alex319** [comment]
Currently, the EventSet uses GUIDs as the "key" to determine if two Events are identical. Are there any places in the code where we actually have two copies of the same EventSet with the same GUID? If not, then we don't need to use GUIDs as a key in the firs tplace, and can just use reference equality for the comparison (what Set does by default).

**Comment by benshayden** [comment]
I didn't see any places where two different objects have the same guid, but guids are used when importing flow events, and as a fall-back sort key. I would believe that a better flow event importer would not need to use guids like that, but redesigning that seems tricky. Using reference equality instead of guids would seem to be a significant departure from the guarantees and assumptions of the current API, if not the method names.

I had thought that using the standard hash map + array would let you basically copy code from the web. No?

**Comment by zeptonaut** [comment]
As discussed in code review, I think my favorite option would be to not provide any random access operator at all. Providing one for a Set seems strange.
