### ISSUE TITLE
Trace file from android doesn't open on Trace viewer

### ISSUE THREAD

**Issue by ssiddhartha** [catapult-project/catapult#2315]
I got this trace from android with heap profiling enabled.
Trace viewer only shows empty page on this trace, but in reality it contains hundreds of trace events and tens of memory dumps.
I removed first 400 events from the file and it seems to display correctly.
[corrupt_trace.txt](https://github.com/catapult-project/catapult/files/249728/corrupt_trace.txt)

+primiano@chromium.org +petrcermak@chromium.org

**Comment by petrcermak** [comment]
I'm __unable to reproduce__ the issue. I can import the trace with ToT Trace Viewer without any problems (even if I go several hundred commits back).

Are you referring to the fact that all events in the trace are squashed on the right hand side of the timeline:

![screenshot from 2016-05-05 11 01 13](https://cloud.githubusercontent.com/assets/2546601/15041008/ce73dc68-12b0-11e6-9987-a485c25c86f9.png)

This is __working as intended__: Rather than being a Trace Viewer bug, this is due to the duration of the <tt>Startup.BrowserMessageLoopStartTimeFromMainEntry</tt> async event (something's telling me it did _not_ really run for 46 years!). The problem is that the start time of the async event is negative:

```
{
  'name': 'Startup.BrowserMessageLoopStartTimeFromMainEntry',
  'tts': 506851,
  'args': {'Temperature': 4},
  'pid': 2011,
  'ts': -1461972216707720,    <-- Should not be negative!!!
  'cat': 'startup',
  'tid': 2011,
  'ph': 'S',                  <-- Async slice start event
  'id': '0x0'
},
{
  'name': 'Startup.BrowserMessageLoopStartTimeFromMainEntry',
  'tts': 506882,
  'args': {'Temperature': 4},
  'pid': 2011,
  'ts': 214670024524,
  'cat': 'startup',
  'tid': 2011,
  'ph': 'F',                  <-- Async slice end event
  'id': '0x0'
}
```

@ssiddhartha: Could you please file a Chromium bug against the owner/author of [code that emits this trace event](https://code.google.com/p/chromium/codesearch#chromium/src/components/startup_metric_utils/browser/startup_metric_utils.cc&l=585), attach the trace there and descibe how you got the trace? Thanks!

Anyway, you can __work around__ this issue by manually selecting all the memory dumps and pressing "f" on your keyboard.

*Please re-open this bug if this is not the issue (i.e. if your timeline is different from the screenshot above).*

**Comment by anniesullie** [comment]
@natduca @nedn I think Petr's comment also explains the problem we are seeing in the start_with_url test.

**Comment by nedn** [comment]
Seem like we have an overflow bug with tracing timestamp? Hmhh

**Comment by nedn** [comment]
First found in https://bugs.chromium.org/p/chromium/issues/detail?id=608724
