### ISSUE TITLE
Dashboard add_point_queue 47 hours behind

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2340]
We got some reports that data is not being added to the dashboard, and upon investigation found that the [add_point_queue](http://go/add_point_queue) is 48 hours behind. I tried speeding up the queue, but we got increased [data contention errors](https://cloud.google.com/appengine/articles/scaling/contention) and the queue did not slow down.

**Comment by anniesullie** [comment]
The number of requests to the perf dashboard has remained steady for the past 2 weeks. I am wondering if something like tbmv2 memory metrics could have caused an increase in the amount of data added to the point where the queue gets backed up?

**Comment by anniesullie** [comment]
I figured out how to get a chart in stackdriver. Looks like this problem started to really pick up over the weekend.

![screen shot 2016-05-17 at 4 51 46 pm](https://cloud.githubusercontent.com/assets/4331931/15338894/d7ac3b1a-1c4f-11e6-81a2-f7f4f251deb2.png)

**Comment by anniesullie** [comment]
First thing we need to do is get additional graphs for:
* Rate at which we add tasks to the queue
* How long tasks run in the queue

I think we want to use stackdriver [custom metrics](https://cloud.google.com/monitoring/custom-metrics/using-custom-metrics) or [log metrics](https://cloud.google.com/logging/docs/view/logs_based_metrics) for this.

**Comment by anniesullie** [comment]
We are going to try turning off data processing for alerts until we can get the task queue under control: https://codereview.chromium.org/1985013003

The alerts will still fire when it gets turned back on.

**Comment by eakuefner** [comment]
The times are just close enough that we have a hypothesis that this may be due to the memory system health benchmarks, which uploads are about 8x bigger than say, smoothness.top_25_smooth, around 10 megs. We're going to try disabling the benchmark and see what happens overnight.

@petrcermak This is probably an issue on our end, rather than the benchmark -- we want the dashboard to be able to accept results of this magnitude, which BigTable should help us with.

**Comment by petrcermak** [comment]
I'm really sorry for causing this. What shall we do now that [<tt>system_health.memory_*</tt> has been disabled](https://codereview.chromium.org/1987103002/)? Does this mean that:

1. the benchmarks need to be modified/simplified/merged?
2. we need to wait for the transition to Bigtable?
3. we need dedicated bots for system health benchmarks?

The disabled benchmarks were only a part (namely "Load Cases") of the [full plan](https://goo.gl/Jek2NL). We expect the total run time of the full benchmark (with all user stories run in _sequence_) to be almost one hour (when run sequentially). However, if I understand the concept of swarming correctly, we should be able to make the benchmark run much faster because each of our many user stories is independent.

@natduca, @primiano, @perezju: FYI

**Comment by anniesullie** [comment]
I don't think the benchmark runtime is a problem for this bug, just the amount of data sent to the perf dashboard. We've seen a huge increase in data processing time, without a corresponding increase in number of requests. We are not 100% sure yet how to resolve the problem, we're currently in firefighting mode trying to get the dashboard processing the data it receives again.

We'll give a clearer update as soon as we can, I think it's some combination of sending less data in the short term and migrating to bigtable in the medium term.

**Comment by anniesullie** [comment]
Link to [tracking doc](https://docs.google.com/document/d/1dr0HtssUMuWNkvoVXHXM5G3YlvMVhIrwjwFJub3EOVg/edit#) which is slowly being turned into postmortem

**Comment by anniesullie** [comment]
Update: we've got the queue back to a manageable size and turned back on alerting and storing unmonitored data. It's been stable for 2 hours.

**Comment by anniesullie** [comment]
After fixing #2351, we are reasonably sure this won't recur.
