### ISSUE TITLE
Perf dashboard: Find a way to understand what is running in the task queue

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2349]
(See [recent postmortem](https://docs.google.com/document/d/1dr0HtssUMuWNkvoVXHXM5G3YlvMVhIrwjwFJub3EOVg/edit#) for background)

We don't have a great way of knowing what's causing additional load on the task queue when things go wrong. There are two parts to this problem:
- Figure out what we want to monitor. Do we want some notion of the masters and test suites that are sending the most data? Or do we want something like [API keys](https://docs.google.com/document/d/1ZZCx9RwtMKPFySHudHEprWVAeuR1EuUkGpZSoPOvEXs/edit) where we give each dashboard user a token to send data with, and we can revoke it if they use too many resources?
- Figure out how to monitor. We tried [stackdriver custom variables](https://codereview.chromium.org/1991843004/), but we blew through our quota in 20 minutes, and weren't able to find a way to graph the data helpfully. Should we try [logs-based metrics](https://cloud.google.com/logging/docs/view/logs_based_metrics)? Something else?

@Apeliotes @dave-2 @eakuefner

**Comment by benshayden** [comment]
I just set up a logs-based metric for the new api alerts handler and found it to be a very good experience. Its Distributions and Labels are very similar to TBM2 Histograms and Diagnostics, with semantic units and customizable bins. The documentation is pretty good, too. However, instead of writing code to measure features of traces as in TBM2, you can only write regexes to extract numbers from log lines, so the dashboard backend needs to log exactly the data that you want to monitor. I would guess that that would be cheaper and easier overall than using the Monitoring API, but maybe somebody else would be better at interpreting the [new stackdriver pricing policy](https://cloud.google.com/stackdriver/pricing_v2).

@eakuefner @simonhatch Would you be interested in trying to add some logs-based metrics to add_histograms and add_histograms_queue with me? It should only take a few minutes to add a logging.info() call, fill out the Create Metric form, and Add Chart on a stackdriver dashboard.

**Comment by simonhatch** [comment]
Maybe let's sync up when Ethan is around and you can walk us through it, sounds really interesting.

**Comment by eakuefner** [comment]
@benshayden Want to put something on the calendar tomorrow or next week for us to do this interactively?

**Comment by benshayden** [comment]
To summarize the meeting, logs-based metrics look easy enough to use that we should experiment with them. #4507

**Comment by eakuefner** [comment]
Moreover, have a CL from @simonhatch https://chromium-review.googlesource.com/c/catapult/+/1070311 that I'm going to try to clean up and land; we'll be able to use this to facilitate starting to use logs-based metrics to look at /add_histograms.

**Comment by eakuefner** [comment]
Archiving; tsmon is supported.
