### ISSUE TITLE
Merge Scalar with histogram Numeric?

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#2354]
Can we use the [Freedman–Diaconis](https://en.wikipedia.org/wiki/Freedman%E2%80%93Diaconis_rule) rule to dynamically adjust the number of bins as samples are added to Numerics and as Numerics are merged throughout Summarization? @eakuefner

**Comment by anniesullie** [comment]
@dave-2

**Comment by eakuefner** [comment]
Talked to Ben offline about this. Some points we raised:

- I pointed out that it might be surprising to metric authors who are already using preconfigured histograms if their buckets change. @benshayden suggested that we could update the builder so that if no range is passed, the result is a `Numeric` which is configured to use the rule.
- There are a number of alternatives to the Freedman-Diaconis rule for adaptive histograms, so we might be able to evaluate them using trial and error.

I'm in favor of this plan though I'd like to hear if @dave-2 has any thoughts.

**Comment by benshayden** [comment]
Right, so there are some metrics that want to build histograms and want static ranges and bin counts (smoothness?). Then there are metrics that want to build histograms but do not know what good ranges and bin counts would be (power?). Then there are metrics that want to record one number, and see histograms magically emerge after summarization (first_paint_metric?). Some sort of adaptive binning can facilitate the latter two use-cases, without hindering the first case.

**Comment by benshayden** [comment]
There's been some more thought on this when I implemented NumericValue.merge() and NumericBase.merge(). See those methods.

I noticed that lots of places in tracing/ui/ use ScalarNumerics as a simple unitted number, so, even though Numeric's summary ScalarNumerics will disappear when Numerics-everywhere happens, and we'll discourage metrics from producing ScalarNumerics (which are difficult to merge as cleanly as histogram Numerics), we will still need simple ScalarNumerics for the many tracing/ui/ use-cases.

So I'll close this bug.
