### ISSUE TITLE
discardable shows 0 effective size both on both sides

### ISSUE THREAD

**Issue by primiano** [catapult-project/catapult#2358]
Something has regressed in the effective size calculation: discardable shows always 0 effective size on both browser and renderer size. The actual sizes seem properly present.

Trace: https://drive.google.com/a/google.com/file/d/0B1oJWfrTOXwxZm8yUGhkNlM4WFE/view?usp=sharing

@petrcermak

**Comment by petrcermak** [comment]
It turns out that this is __working as intended__: The reason why the effective size is 0 is that there are other components within the process sub-allocating from the segments, e.g.:

![screenshot from 2016-05-23 15 15 41](https://cloud.githubusercontent.com/assets/2546601/15473698/3d478abc-20f9-11e6-945c-b81513b79a3e.png)

@primiano: I understand that this might be confusing. Let me know if you can think of a way to make it less confusing.

**Comment by primiano** [comment]
Ahh right, essentially all the discardable memory is being properly blamed, I see.
Sorry I didn't realize.
Don't have an obvious way to make it clear, but, yup, at first it can be confusing (even for me).
Should figure out something UI-wise, but, right, this is not a bug.
Thanks for the investigation
