### ISSUE TITLE
Show "memory per component" using stacked bars

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2360]
This is safe to do since the track is showing [effective size](https://docs.google.com/document/d/1GvzDP-tTLmJ0myRhUAfTYWs3ZUFilUICg8psNHyccwQ/edit#heading=h.9coro6q5ziyf), which is cumulative.

__Current UI__ (non-stacked line chart)

![screenshot from 2016-05-23 17 46 49](https://cloud.githubusercontent.com/assets/2546601/15477881/181b713e-210f-11e6-8574-a1e1dafc3d03.png)

__Rationale:__ To use the same chart as the one used in the [Renderer's Memory Visualization](https://docs.google.com/document/d/1JfnW6RpRDuuZITQ3xuFUIRBfC_KOG5xXUuW8U_UePJU/edit?usp=sharing) document:

![screenshot from 2016-05-23 17 45 24](https://cloud.githubusercontent.com/assets/2546601/15477727/26260718-210e-11e6-834a-f2632949fb5e.png)

@natduca, @primiano: FYI

**Comment by primiano** [comment]
To be honest, since you opened the topic, I was actually thinking to ditch the memory-per-component track.
It steals lot of real estate and (regardless of the additivity or not) is too small to be useful. On top of thta, the colors are too similar to each other and every time I try to use it I give up.
I'd support to ditch in favor of having, in a separate future iteration, a proper chart like the one below, maybe in a separate pane (not inline with the tracks), or maybe a track which by default is compressed and when clicked expands to a large and useful chart.

**Comment by petrcermak** [comment]
I agree that the existing chart is pretty much useless. I've just written a patch that uses the stacked bars instead (https://codereview.chromium.org/2004853003). It's still not perfect, but it gives a much better idea of how much memory each component allocates (note that now the order of components on the chart matches the order of columns in the memory-infra analysis view):

![screenshot from 2016-05-23 18 08 57](https://cloud.githubusercontent.com/assets/2546601/15478345/9b6fc7ea-2111-11e6-9537-f5c7a6c2b92e.png)

**Comment by nedn** [comment]
@eakuefner @benshayden

**Comment by natduca** [comment]
Lets try to make the inline chart better. The track view is not as good as it could be :)

**Comment by bashi** [comment]
@tasak FYI

**Comment by nedn** [comment]
@ZiqiXiong @wangzhen127

**Comment by petrcermak** [comment]
__Done__ ✅
