### ISSUE TITLE
timeout_retry error messages are spammy and not very useful

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#2396]
Upon failure, the timeout_retry wrapper, specially as used in device utils, tends to be extremely spammy and, more often than not, disappointingly useless: just gives a call stack full of shell-and-timeout-retry-thingies that finally ends up in a call to `timeout_retry.Run`. Who called that? Who knows.

Also, the most common form of retry seems to come from cases where a shell command was correctly executed on a device but (because e.g. a file does not exist) it returned a non-zero exit status. On very few occasions those retries actually make sense: files that don't exist (usually) do not magically appear.

As a first measure to reduce the spam for adb.Shell, I would suggest to use different exceptions for "failed because I couldn't find the exit status" and "the command ran OK, but the exit status is not 0"; and then whitelist the second kind of exception so we don't retry on that one.

Thoughts?

@jbudorick @case540

**Comment by picksi** [comment]
Is there any way to analyse old logs to determine which re-tries will
sometimes work, and which will always fail?

Simon

**Comment by jbudorick** [comment]
Really need to work on my github email filters.

I've typically seen something like:

  try failure 1: call stack up to `timeout_retry.Run` (mostly useless)
  try failure 2: call stack up to `timeout_retry.Run` (mostly useless)
  try failure 3: call stack up to `timeout_retry.Run` (mostly useless)
  overall call stack (useful)

I might be in favor of removing the intermediate stack traces.

As for adb.Shell and intentional nonzero exit codes:
 - AdbWrapper.Shell has a `expect_status` kwarg that we could conceivably tweak to permit multiple status codes, not sure if that'd be useful here
 - AdbWrapper.Shell will raise an AdbShellCommandFailedError in both cases, but will have a non-None status if a command ran but terminated with a nonzero code.

**Comment by perezju** [comment]
I saw that there is now a [WithTimeoutAndConditionalRetries](https://cs.chromium.org/chromium/src/third_party/catapult/devil/devil/android/decorators.py?l=82) decorator, but I feel that introduces more complexity because it expects the caller to know which kinds of exceptions might be raised and determine which should/shouldn't trigger a retry.

I think it would be better if we defined a "default" action (either retry/not-retry), and then allow _exceptions_ to override that behavior. I'm leaning a bit towards making all exceptions skip retries, except for some which we could mark, essentially, as "flaky" and only those should trigger retries.

Anyway, as Simon suggested, perhaps we do need a more careful study of existing logs and use cases in the code before making bigger changes here.

**Comment by jbudorick** [comment]
We currently only retry on exceptions anyway.

What you describe sounds like a behavior that WithTimeoutAndConditionalRetries could support -- `retry_if_func` takes the exception as its own parameter and returns whether, given the exception, the call should be retried. I think we currently only use it in [one place](https://codesearch.chromium.org/chromium/src/third_party/catapult/devil/devil/android/sdk/adb_wrapper.py?rcl=0&l=222), though, and that's for retrying `adb` commands that fail because they don't have `adb`.

**Comment by perezju** [comment]
Yes, but what I'm suggesting is that perhaps we should go to the other extreme: *most exceptions should not cause a retry*; retrying only makes sense on a small set of exceptions (mostly: "adb did something weird/unexpected").

**Comment by jbudorick** [comment]
That sounds like a reasonable end state, but the transition is tricky. I'd rather retry exceptions we shouldn't, which merely costs us time, than not retry exceptions we should, which costs us stability, and I don't think we currently know enough about which exceptions fall into which categories. (We also don't make an effort to distinguish between the two.)

WDYT about:
 - adding optional retry exception reporting that we enable from the bots
 - adding some support for a recovery action between retries

**Comment by perezju** [comment]
Sounds good. I'm thinking some info we could report (and don't do already) is the name of the function being retried. I could add that info and then, scraping through the logs, I think we could get a good picture of which sorts of things are causing retries and which of those could be skipped.

Anything else you think we should report in the logs?

**Comment by perezju** [comment]
This work was completed.
