### ISSUE TITLE
adb.Forward do not pass down the --no-rebind to the adb forward command line

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2397]
According to @gabadie,  
https://github.com/catapult-project/catapult/blob/master/telemetry/telemetry/internal/platform/android_platform_backend.py#L469 is buggy because adb.Forward do not pass down the --no-rebind to the adb forward command line. That could lead to bug where if telemetry is performing benchmark on 2 different devices from the same host, then it could be opening telemetry devtool connection on the wrong device.

@perezju @jbudorick thoughts?

**Comment by jbudorick** [comment]
Not sure I follow. Can you elaborate a bit more?

**Comment by gabadie** [comment]
Just found the issue today in our project Sandwich:

You have two instance of telemetry t1 and t2 running on different device d1 and d2 respectively on the same host.

1) t1 and t2 both allocate a same port X by the PortKeeper() (sadly possible if done sequenctially): 
https://cs.chromium.org/chromium/src/third_party/catapult/telemetry/telemetry/internal/backends/chrome/android_browser_backend.py?q=DevToolsClientBackend&sq=package:chromium&dr=C&l=109
2) t1 create the forwarder from host's X to t1's chrome devtool listening port
3) t2 create the forwarder from host's X to t2's chrome devtool listening port as well
4) t1 open the HTTP devtool connection: https://cs.chromium.org/chromium/src/third_party/catapult/telemetry/telemetry/internal/backends/chrome_inspector/devtools_client_backend.py?q=DevToolsClientBackend&sq=package:chromium&l=78&dr=CSs

then here, t1 would be controling chrome on t2 instead of t1.

The fix is to passdown --no-rebind to adb forward command. Out fix example is right here:
https://codereview.chromium.org/2044703005/diff/1/tools/android/loading/device_setup.py

This way stage 3) would fail, and t1 would be opening HTTP devtool connection on t1 as expected.

Note: if you guys are changing the API for AdbWrapper.Forward in catapult to expose the --no-rebind in an option, I would be glad to use it as well instead of doing my hack in the CL linked right above. =)

**Comment by nedn** [comment]
I think --no-rebind is a sane default option to  be enabled in https://github.com/catapult-project/catapult/blob/master/devil/devil/android/sdk/adb_wrapper.py#L537

**Comment by perezju** [comment]
Sounds reasonable. If there are no strong objections I'll write a patch to expose that option and expose it as default.
