### ISSUE TITLE
Webview startup metric is not shown on metric side panel

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2408]
To reproduce:
Click on Metrics side panel, then select "webviewStartupMetric" from the drop down in
https://console.developers.google.com/m/cloudstorage/b/chrome-telemetry-output/o/trace-file-id_0-2016-06-12_11-32-19-96918.html

@Alex319

**Comment by Alex319** [comment]
When I look at this trace, none of the metrics show up. Maybe there's something else wrong with this trace, not related to the webview startup metric specifically?

**Comment by Alex319** [comment]
Okay, it looks like the problem doesn't have anything to do with the webview startup metric. It looks like the problem is that the **updateContents_** function in metric_side_panel is being called without initializing the side panel's **model_** parameter. I'm not sure why that's happening - when I put a breakpoint in the **updateContents_** function it doesn't look like it's being called from anything (updateContents_ is the only item in the stack trace.) I'll keep looking into this.

**Comment by benshayden** [comment]
This appears to be fixed?
