### ISSUE TITLE
Re-enable telemetry.internal.backends.chrome_inspector.tracing_backend_unittest.TracingBackendTest.testDumpMemorySuccess on win-reference

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2409]
Log: https://build.chromium.org/p/tryserver.client.catapult/builders/Catapult%20Windows%20Tryserver/builds/3370/steps/Telemetry%20Tests%20with%20Stable%20Browser/logs/stdio

Probably we just need to disable this on reference.

**Comment by petrcermak** [comment]
Let's follow the Chromium approach and re-purpose this issue for re-enabling the test once it doesn't flake. Assuming this is due to https://bugs.chromium.org/p/chromium/issues/detail?id=619106, the flakiness should disappear in a couple of weeks (once the fix makes its way to the reference builds).

**Comment by petrcermak** [comment]
The reference builds were [rolled](https://codereview.chromium.org/2189533003) to 5**2**.0.2743.91 yesterday. However, the [fix](https://codereview.chromium.org/2061953002) for the suspected issue is available from 5**3**.0.2768.0 onwards. Therefore, we need to wait for a few more weeks before re-enabling :disappointed:

**Comment by petrcermak** [comment]
Still blocked on #2533.

**Comment by zeptonaut** [comment]
Closing this, as #2409 is now closed. However, this test is staying disabled on windows-reference and getting disabled on windows due to #3131
