### ISSUE TITLE
Plumb CanonicalUrl through telemetry into TelemetryInfo

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2431]
Before diagnostics were typed, we added the canonicalUrl to the diagnostics. We should reintroduce this functionality so we can use the CanonicalUrl diagnostic to surface trace links (or especially, collections of trace links for summary values) on the perf dashboard.

Mutliple people have been confused about the fact that traces don't display for summary values, and coming up with a mergeable CanonicalUrl diagnostic would help us fix this problem for TBMv2 benchmarks.

@anniesullie @benshayden

**Comment by benshayden** [comment]
Why not a field on IterationInfo?

**Comment by benshayden** [comment]
So telemetry plumbs IterationInfo into trace metadata (model.metadata[]), which metric_map_function copies to IterationInfo diagnostic javascript objects on Values. So, instead of setting canonicalUrl on model, it can be serialized into the trace metadata, and be copied to diagnostics from there.

The deeper issue is that TraceValues need to be uploaded in a more principled way. There should be some lifetime guarantee that each trace is uploaded before IterationInfo is modified (WillRunStory()). Maybe IterationInfo.WillRunStory() should reserve a cloud_url, plumb it through TracingControllerBackend as II is currently, then DidRunStory() should do the upload of the most recent TraceValue.

We can factor the remote_path calculation from TraceValue into IterationInfo.ReserveUrl(), and have TracingControllerBackend pass that to TraceValue.UploadToCloud() in StopTracing().

plumb bucket from story_runner into IterationInfo if options.upload_results.

Leave UploadProfilingFilesToCloud alone for now, but maybe eventually fix it up like this.

Whether IterationInfo should be split to separate generic diagnostics is a separate design question that can be iterated later.

**Comment by benshayden** [comment]
CollectedRelatedEventSet needs model.canonicalUrl, which is set by RunMetricOnTraces, so it needs to be plumbed through there regardless of whether it's plumbed through the TelemetryInfo in the trace metadata.

**Comment by benshayden** [comment]
@eakuefner Mind if I take this?

We also need to make sure that traceUrls show up in CSVs.

**Comment by benshayden** [comment]
I think this is done. Plumbing the urls through RelatedEventSets is a separate issue.
