### ISSUE TITLE
Animation stage is not detected correctly in webgl animation benchmark

### ISSUE THREAD

**Issue by ulan** [catapult-project/catapult#2446]
While porting ooronline_tbm benchmark to TBMv2 I noticed that there is no Animation stage in the trace.

Instead, there are Idle and Response stages, but the benchmark is actually doing animation.

Steps to reproduce:
1. Apply https://codereview.chromium.org/2104303002/ in catapult.
2. Apply https://codereview.chromium.org/2106133002/ in chromium.
3. Add code to log user expectations in reponsiveness_metric.html
4. tools/perf/run_benchmark oortonline_tbmv2

Expected log: Animation and Response.
Actual log: Idle and Response.

**Comment by nedn** [comment]
@zeptonaut @benshayden

**Comment by benshayden** [comment]
Yep. #1146 #1145 
I'll talk with @zeptonaut about adding findScriptAnimations to UserModelBuilder.

**Comment by petrcermak** [comment]
This is __blocking__ https://codereview.chromium.org/2106133002/, which in turn is __blocking__ [deprecating & removing the TBMv1 memory metric](https://bugs.chromium.org/p/chromium/issues/detail?id=621037).

**Comment by nedn** [comment]
@zeptonaut @Alex319 Ben is out. Can any of you take this bug?

**Comment by zeptonaut** [comment]
Ping @Alex319, who I know spent some time investigating how animations are working in the user model.

**Comment by Alex319** [comment]
I will look into this.

**Comment by Alex319** [comment]
It looks like the animations in the user model only are getting things like in-page navigation (scrolling, pinching, etc) and CSS animations (and soon to include video playback). This benchmark does an animation through WebGL so it is not detected by any of the existing detectors.

**Comment by nedn** [comment]
WebGL is an important class of animation to cover. 
@kenrussell can anyone on gpu team help Alex with detecting webgl based animation on tracing timeline?

**Comment by kenrussell** [comment]
@nedn @Alex319 I'd be happy to help or try to find someone else to do so. It would be most productive if we could have a real-time conversation since I don't know anything about these kinds of Telemetry benchmarks.

**Comment by zeptonaut** [comment]
Thanks @kenrussell. I went ahead and threw something on your calendar for tomorrow so that the three of us can talk.

**Comment by kenrussell** [comment]
https://codereview.chromium.org/2163373005/ is adding an event for DrawingBuffer::prepareMailbox which is a good indicator that WebGL work was done in the current frame. That, combined with looking for (for example) PageAnimator::serviceScriptedAnimations, should be a good indicator that WebGL is animating.

**Comment by zeptonaut** [comment]
@Alex319, is this bug resolved? It looks like @ulan is blocked on this for https://bugs.chromium.org/p/chromium/issues/detail?id=621037

**Comment by Alex319** [comment]
I have a CL for this, still waiting on code review:

https://codereview.chromium.org/2169963002

**Comment by ulan** [comment]
@Alex319, I tested chrome at r408608, which includes the CL. It shows only "idle" stage for the whole 
oortonline run. Is it expected?

The steps I did:
1. git cl patch 2106133002
2. build chrome
3. tools/perf/run_benchmark oortonline_tbmv2 --browser-executable=$(pwd)/out/Release/chrome --output-format=json --reset-results
4. open ./tools/perf/http___oortonline_gl__run0.html
Expected: "Interactions" row at the top contains "Animation".
Actual: "Interactions" row at the top contains only "Idle".

**Comment by nedn** [comment]
Is that because you haven't set up the tracing config right?

**Comment by Alex319** [comment]
I tried to do git cl patch 2106133002 after updating chrome to the newest
version, but I got an error while patching:

*TypeError: sequence item 2: expected string, NoneType found*

Can you send me the trace? That way I can see if the problem is with the
code that generates the RAILS stages, or if the problem is that the
required trace event isn't in the trace.

Does your current checkout of Chrome have the patch
2163373005 <https://codereview.chromium.org/2163373005>

in it? This is the patch that adds the DrawingBuffer::prepareMailbox trace
event. If not, that would explain why it is not working. (I don't
understand what is going on with this patch: it appears to have landed but
that line isn't showing up in code search.)

-Alexander Mont

**Comment by kenrussell** [comment]
It's there:
https://cs.chromium.org/chromium/src/third_party/WebKit/Source/platform/graphics/gpu/DrawingBuffer.cpp?rcl=0&l=255

**Comment by ulan** [comment]
Thank you!

I added 'blink' category to 2106133002 and rebase to include 2163373005.

With that I get Animation interactions (attached a trace). Some of them are very short (about 19ms) and don't have associated frame events. So the responsiveness metric is throwing at (https://cs.chromium.org/chromium/src/third_party/catapult/tracing/tracing/metrics/system_health/responsiveness_metric.html?rcl=0&l=34)

Is this expected? If so, I will adjust the responsiveness metric to handle Animation that do not have frame events.

[http___oortonline_gl__run0.html.tar.gz](https://github.com/catapult-project/catapult/files/393714/http___oortonline_gl__run0.html.tar.gz)

**Comment by nedn** [comment]
I think that sound about right. If the animation is too short, probably should be skipped. Though I think we should first understand whether those short animations are correct.

**Comment by Alex319** [comment]
I think I have an idea of what's going on in this trace.

The part with all the really short Animations is the beginning, which is
when oortonline is loading. This is the place at the beginning when
oortonline is loading the animation (and is displaying the "Loading" bar).
You see all the short animations because it loads, then animates the
loading bar to move to the new position, then loads some more, then
animates the loading bar some more, and so on. These are very short
animations because it takes longer to load than to animate, so the
animation keeps starting and stopping. Then once you get in the main part
of the test, where it's actually rendering in 3D, you will now notice lots
of animations about 1 second long separated by extremely short idle periods
about 0.05-0.1 second long. If you run oortonline and watch carefully you
can see this is what is actually happening - the animation does have very
short "hiccups".

So it looks like the RAILS stages are correctly displaying what's
happening; I would think that it's up to the metric how it wants to handle
these cases.

-Alexander Mont

**Comment by kenrussell** [comment]
Good investigation Alex. If any of you dig into the traces more deeply and find that there would be better places to add trace events to detect WebGL animations, please let me know and we'll make the necessary code changes.

**Comment by ulan** [comment]
Thanks a lot for fixing this issue, Alex and Ken!

I uploaded CL that handles empty animation stages in metrics: https://codereview.chromium.org/2201043002/
