### ISSUE TITLE
No alert raised in benchmark "ChromiumPerf/chromium-rel-win7-x64-dual/speedometer/Total"

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#2457]
There was no alert raised in the mentioned benchmark: https://chromeperf.appspot.com/report?sid=bff61233fabaf775e35820a9b17937ebeb85e5cc99dcbc4d966553c187732a02&start_rev=395448&end_rev=404101. I would have expected an alert around revision 402379. I couldn't create an alert via debug alert either.

Debug alert: https://chromeperf.appspot.com/debug_alert?test_path=ChromiumPerf%2Fchromium-rel-win7-x64-dual%2Fspeedometer%2FTotal&rev=+402379&num_before=1000&num_after=1000&config=%7B%0D%0A++%22max_window_size%22%3A+8%2C+%0D%0A++%22min_relative_change%22%3A+0.029999999999999999%2C+%0D%0A++%22min_segment_size%22%3A+3%0D%0A%7D

**Comment by anniesullie** [comment]
The problem here is that it's an increase over many revisions. If you remove the 'max_window_size' from the V8-speedometer configuration, it does detect the alert:

https://chromeperf.appspot.com/debug_alert?test_path=ChromiumPerf%2Fchromium-rel-win7-x64-dual%2Fspeedometer%2FTotal&rev=+402379&num_before=1000&num_after=1000&config=%7B%0D%0A++%22min_relative_change%22%3A+0.029999999999999999%2C+%0D%0A++%22min_segment_size%22%3A+3%0D%0A%7D

The segment size is the minimum number of data points between alerts. With the way the graph steadily climbs up, it can't find a good place to alert with a segment size of 8. If you remove the segment size requirement, you'll get more alerts (as you see in the debugger, you end up with 2 alerts over the increase).

**Comment by natorion** [comment]
Thanks. Just to clarify: When you talk about segment size in your second paragraph you mean max_window_size, right?

**Comment by anniesullie** [comment]
I mean min_segment_size. See documentation here:
https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/find_change_points.py

**Comment by natorion** [comment]
Thanks Annie
