### ISSUE TITLE
Cannot triage a large number of alerts simultaneously on dashboard (alert page page)

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2536]
![screen shot 2016-07-25 at 18 41 06](https://cloud.githubusercontent.com/assets/2546601/17109228/6db28f88-5297-11e6-862a-000e73d242fa.png)

I would like to assign several hundred alerts (from https://chromeperf.appspot.com/alerts?sheriff=System%20Health%20Perf%20Sheriff) to the same bug (https://bugs.chromium.org/p/chromium/issues/detail?id=631079). Unfortunately, whenever I try to do this (either via "new bug" or "existing bug"), I get a 500 error in the end and only a handful alerts (~10) get actually assigned.

**Comment by anniesullie** [comment]
To solve this, we need to be able to do one of the following:
* Save 500 alerts at once (we should check that we're calling `put_multi` on the backend and look at the trace)
* Limit the number of alerts you can check/save in the UI
* Update asynchronously (this is a little fraught because it's hard to give the user feedback to let them know it worked)

@Apeliotes

**Comment by benshayden** [comment]
(This looks like a straight-up Perf Dashboard bug, not a System Health bug.)

**Comment by anniesullie** [comment]
Agreed. But should we have a hotlist for bugs that make it hard to triage system health bugs, like we have Hotlist:v8? @petrcermak let me know what you think.

**Comment by petrcermak** [comment]
My interpretation of GitHub labels is _"related to"_, _"affects"_ or _"blocks"_, which is why I labelled this bug as "System Health".

**Comment by anniesullie** [comment]
A lot of work in this area has fixed the root issue.
