### ISSUE TITLE
Chrome/Telemetry trace able to successfully import without Chrome clock sync markers

### ISSUE THREAD

**Issue by Alex319** [catapult-project/catapult#2547]
To reproduce:
1. Apply patch https://codereview.chromium.org/2182223002. This adds additional events to the Telemetry trace. (Normally, this bug is not visible because there are no events other than clock sync markers in the Telemetry trace.)
2. Run a TBMv2 benchmark that generates a trace and open the trace up using dev server.
3. What is expected is that you will see the trace. However, actually, you will see a "blank" trace. 
4. Open up the JavaScript console. You will see an error saying "The trace is too long or the CPU usage counter interval is too small, leading to too many CPU usage intervals.
5. If desired, put a breakpoint here and re-run it to inspect the interval. You will see that the total interval for the trace is extremely long (e.g. many millions of ms). This is because the telemetry trace is not being synced to the start of the interval, so that the raw timestamps are what is being used for the trace.

**Comment by zeptonaut** [comment]
This is very confusing. After some investigation, there seem to be (at least) three things going on here:

1. There's been some regression where Chrome is no longer adding clock sync markers into its trace. This is bad.
2. I would have expected 1) to break a regression test with a clock sync error, but apparently *everything still seems to be working fine*. Need to investigate this further. Recording a trace with ToT Chrome and ToT Catapult works perfectly. This doesn't make sense, because *Chrome and Telemetry are supposed to be on different clock domains*. How are we not throwing an import error when this happens?
3. Some of the timestamps in the Telemetry trace are wacky. For a roughly 10 second trace, the first timestamp is 1469661779.115583 and the last timestamp is 17500309181.801: the two timestamps are about 9 years apart. The former seems to be a unix timestamp from today. I'm not sure, but I'm guessing that the latter is a `mach_absolute_time()` output, which is how Chrome keeps track of time on Mac. It looks like something is reinitializing the current trace_time in the middle of a Telemetry run. Alternatively, something is writing a trace event but isn't using py_trace_event.trace_time as its time source.

Lots of follow-up work from this investigation.

**Comment by zeptonaut** [comment]
I'm splitting this bug into each of its three buggy components. This particular bug is going to track the fact that no Telemetry benchmarks caught this breakage.

**Comment by zeptonaut** [comment]
The reason that the import succeeded even without clock sync markers is due to the fact that we were never shifting to the model time in the `TraceEventImporter`. Most of the time, this was a no-op due to the fact that we prefer to use the trace event (Chrome) clock domain as the model one. However, this also meant that we never checked that all clock domains (e.g. Telemetry and Chrome) were connected. I have a CL drafted up that fixes this.
