### ISSUE TITLE
Each bar in the stacked column chart produced by results2.html don't have distinct coloring

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2567]
![color](https://cloud.githubusercontent.com/assets/911877/17193317/7cb7d9b8-5420-11e6-8366-a0379a604e7d.png)

**Comment by eakuefner** [comment]
Thanks for reporting this, Ned. Part of the problem here is that the way we determine these bar colors is by hashing the legend keys, which is not such a good way to go.

I think for the demo, I'm going to ape the routines in https://github.com/catapult-project/catapult/blob/master/experimental/heatmap/color.js to make the colors a lot less bad. This should probably trickle up to tracing proper, but that's a conversation we can wait to have.

@dave-2

**Comment by nedn** [comment]
@benshayden

**Comment by benshayden** [comment]
ChartBase uses ColorScheme.getColorIdForGeneralPurposeString(), which uses getStringHash().

The reason that we use hash colors here is so that each category is always the same color. This makes reading many bar charts easier because you don't need to stop and read each legend.

The problem as we're seeing here is that many strings can hash to very similar colors.

The solution that tracing uses is to hard-code specific colors for specific strings using reservedColorsByName in base/color_scheme.html.

It might be time to reserve specific colors for the UserFriendlyCategory strings. That rainbow would probably work fine if it looks good to you as a generating function for the reserved colors. We might want color_scheme.html to statically generate the rainbow (as opposed to generating the rainbow for the current UFC set and hard-coding the colors) in case UFCs are added/removed/re-ordered.

I think that the architecturally cleanest way to make ChartBase use those colors would be to add a method like customizeColors() to allow composition-span to use getColorForReservedNameAsString(). Then Composition would need a boolean flag to indicate that its keys are UserFriendlyCategories, so that composition-span can fall back to getColorIdForGeneralPurposeString() when the keys are not UFCs. Simple enough :-)

How does that sound?

**Comment by nedn** [comment]
@benshayden that solution works. 

Another approach we can take is to make the algorithm of generating colors for labels be specific to each bar chart or stacked bar charts, i.e: it ensures that for a given bar chart, or stacked bars chart, all the bars that are next to each other must have very different color.

**Comment by eakuefner** [comment]
What @benshayden has said sounds good to me, although I pointed out offline that we may want to add an additional getColorIdForGeneralPurposeString that uses the sinebow/memoization technique I lay out in https://codereview.chromium.org/2202953002 so that users (e.g. BarChart) are free to choose either scheme depending on what works best for their needs.
