### ISSUE TITLE
Update system health memory links to new names

### ISSUE THREAD

**Issue by rschoen** [catapult-project/catapult#2570]
go/chrome-system-health-metrics

Memory metrics are reporting no data since July 4th. Probably need to be updated post-rename.

**Comment by rschoen** [comment]
We should also triple-check that the monitoring is still on the correct graphs.

**Comment by petrcermak** [comment]
Should we use SH benchmarks for this? Note that they're currently running _upstream only_.

@perezju

**Comment by perezju** [comment]
I guess the answer is "yes", since this is about the chrome-wide effort to track system health, right?

We could provide links with charts for memory (each of: browser, renderer, total) for one or two "represntative" products for each of Windows and Mac. Like we do today for Android (one "high-end", and one "low-end").

Suggestions as what to choose for representative? It seems that we currently have:
* chromium-rel-mac-hdd
* chromium-rel-mac-retina
* chromium-rel-mac10
* chromium-rel-mac11
* chromium-rel-win10
* chromium-rel-win7-dual
* chromium-rel-win7-gpu-ati
* chromium-rel-win7-gpu-intel
* chromium-rel-win7-gpu-nvidia
* chromium-rel-win7-single
* chromium-rel-win7-x64-dual
* chromium-rel-win8-dual
* linux-release
* win-zenbook

**Comment by anniesullie** [comment]
@petrcermak Can you clarify which benchmarks and metrics we should be tracking? We currently list:

browser memory:
memory.top_10_mobile/memory_mmaps_overall_pss_browser/foreground
memory.top_10_mobile/memory_mmaps_overall_pss_browser/background

renderer memory:
memory.top_10_mobile/memory_mmaps_overall_pss_renderer/foreground

total memory:
memory.top_10_mobile/memory_mmaps_overall_pss_total/foreground

**Comment by petrcermak** [comment]
I suggest we use the <tt>system\_health.memory\_**mobile**</tt> and <tt>system\_health.memory\_**desktop**</tt> benchmarks with the following values:

browser memory: <tt>memory:chrome:**browser**\_process:reported\_by\_os:proportional\_resident\_size</tt>
renderer memory: <tt>memory:chrome:**renderer**\_processes:reported\_by\_os:proportional\_resident\_size</tt>
total memory: <tt>memory:chrome:**all**\_processes:reported\_by\_os:proportional\_resident\_size</tt>

Note that the values above all include PSS of the GPU memory. If we want to exclude it (status quo), then the values should instead be:

browser memory: <tt>memory:chrome:browser\_process:reported\_by\_os:**system\_memory**:proportional\_resident\_size</tt>
renderer memory: <tt>memory:chrome:renderer\_processes:reported\_by\_os:**system\_memory**:proportional\_resident\_size</tt>
total memory: <tt>memory:chrome:all\_processes:reported\_by\_os:**system\_memory**:proportional\_resident\_size</tt>

**Comment by anniesullie** [comment]
Did I get this right? I'm seeing all zeros for desktop:
https://chromeperf.appspot.com/report?sid=c99f010e8e87fc871d631f46c98399f163e536b041aa6ec5530f438ac6642c34

**Comment by petrcermak** [comment]
Apologies, I completely forgot that we currently have PSS on Android and desktop Linux only. I suppose we'll need to track the following as well (always available on all platforms):

browser memory: <tt>memory:chrome:**browser**\_process:reporter\_by\_chrome:effective\_size</tt>
renderer memory: <tt>memory:chrome:**renderer**\_processes:reporter\_by\_chrome:effective\_size</tt>
total memory: <tt>memory:chrome:**all**\_processes:reporter\_by\_chrome:effective\_size</tt>

**Comment by anniesullie** [comment]
Thanks, @petrcermak! I updated the desktop charts in the spreadsheet to use those metrics.
