### ISSUE TITLE
Systrace unit tests should disable platforms per-test rather than globally disabling a platform

### ISSUE THREAD

**Issue by peterwashington** [catapult-project/catapult#2603]
The unit tests for systrace and profile_chrome do not currently run on Android: https://github.com/catapult-project/catapult/blob/master/catapult_build/build_steps.py. However, most of the tests should also run on Android. To fix this, we need to dynamically specify the platforms that each the tests should run on (rather than limiting the platform for all tests in the Catapult build configs). This will allow some tests to run on Windows/Mac/Linux and others to run on Android (in future CLs). In other words, this will set the groundwork for writing Android-specific tests in the future.

**Comment by anniesullie** [comment]
@wangzhen127 asked me about this yesterday and my initial feedback was to use [unittest.skip](https://docs.python.org/2/library/unittest.html#skipping-tests-and-expected-failures) instead of trying to share the decorator code with telemetry. Then I thought about it some more, and I realized that if we do something like this:

```
@unittest.skip(sys.platform == 'android')
```

It doesn't make any sense, because both the linux tests and the android tests actually run on linux (with attached devices for the android tests), and `sys.platform` will always be something like `linux2`. So we'd want to change `build_steps.py` to add a platform argument to the tests it runs.

All this is still pretty simple, but at this point I'm not sure if we just want to re-use what telemetry does since it is diverging more and more.

@nedn WDYT?

**Comment by nedn** [comment]
Reusing telemetry's decorator is not simple, because telemetry determine the target platform as the platform of the browser, through commandline passed to telemetry's run_tests script.

Divergent here is the right call. The run_test script of systrace & profile_chrome should be passed in --device=<device id> and have the concept of target_device anyway, otherwise it will be ambiguous which device is picked when the host connects with like test 7 devices.

**Comment by anniesullie** [comment]
Thanks, @nedn! Using --device sgtm.

**Comment by peterwashington** [comment]
@anniesullie @nedn Thanks for this! I will go ahead and implement --device for the run_tests script and then pass in the device as an additional_arg for the Systrace tests.

FWIW, it looks like Python developers are looking into (eventually, one day) providing Android platform detection in Python: https://mail.python.org/pipermail/python-dev/2014-August/135616.html

**Comment by nedn** [comment]
Is that python running directly on your android device or running on a host computer connecting to the remote device?

**Comment by peterwashington** [comment]
Fixed in https://codereview.chromium.org/2208943003/
