### ISSUE TITLE
Bisect output sometimes incomplete on failure

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2626]
Example: https://bugs.chromium.org/p/chromium/issues/detail?id=635513#c3

```
===== BISECT JOB RESULTS =====
Status: failed


===== TESTED REVISIONS =====
Revision         Mean     Std Dev    N  Good?
chromium@409796  4.0431   0.0280426  5  good
chromium@409804  4.03511  0.109318   8  good
chromium@409805  4.06369  0.0826172  5  good
chromium@409806  3.60221  0.169349   5  bad
chromium@409808  3.75538  0.0575883  8  bad
chromium@409811  3.72238  0.0346838  5  bad
...
```

Problems with this output:
- It doesn't give any failure reason.
- It doesn't clarify that it may just have partial results
- It's pretty clear that r409806 is the culprit, but it doesn't cc the author, give confidence, print the CL info, etc.

**Comment by anniesullie** [comment]
Another example: https://bugs.chromium.org/p/chromium/issues/detail?id=635464#c3

**Comment by petrcermak** [comment]
I've seen this happen at least once when the bisect should have descended into a __Skia roll__: https://bugs.chromium.org/p/chromium/issues/detail?id=633941#c5

**Comment by vuppalapu** [comment]
The failure reason for the both the jobs mentioned in this issue are due to the exception in remore_run_recipe step. https://build.chromium.org/p/tryserver.chromium.perf/builders/mac_10_10_perf_bisect/builds/2278
But I totally agree that there should be detailed desciption about the bisect failure.

Also seen remote_run_recipe step exception on Android bot https://build.chromium.org/p/tryserver.chromium.perf/builders/android_s5_perf_bisect/builds/898

**Comment by simonhatch** [comment]
Going to close this, output has changed significantly since this was filed.
