### ISSUE TITLE
Changing subtest dropdown resets following subtests

### ISSUE THREAD

**Issue by camillobruni** [catapult-project/catapult#2639]
We used to be able to change subtest without the following path segments to change.
This currently breaks the use-case of browsing through a deep set of subtests as we currently have with the RuntimeStats, reselecting several subtests for changing one parameter is rather cumbersome.
## Steps to reproduce:
1. Select "v8.todomvc" / "linux-release" /  "v8_execution_cpu_total_sum" / "AngularJS"
2. Change the subtest from "v8_execution_cpu_total_sum" to "v8_execution_cpu_total_avg"
3. Observe how the following subtest is reset even though there are valid entries

**Comment by simonhatch** [comment]
FYI: From discussion, the fix here is to retain as much of the old picker path as is still valid after switching a subset of it.

**Comment by simonhatch** [comment]
So poking at this a bit, so there's a bunch of complexity around supporting multi-select, but the last multi-select menu was disabled by @anniesullie in https://codereview.chromium.org/2595133002/.

Speake to @eakuefner earlier this week, we talked about potentially stripping out a lot of this complexity to make his work on the subtestdict optimization easier. Would help here too, since this does a bunch of unnecessary deselects before selecting items again and losing the original path. Did a quick demo where I assume it doesn't support multi-select and just watch for when a new item is selected and the path is retained:

Demo: https://dev-simonhatch-4ed4d71e-dot-chromeperf.appspot.com/report?sid=808fd6086822f9e1e1e41190bc15ebe061ea77be7955152cd883093725535556

**Comment by anniesullie** [comment]
Awesome! Let's definitely remove multi-select!

**Comment by simonhatch** [comment]
@eakuefner have you had a chance to do this? Otherwise I can grab strip that out now.

**Comment by eakuefner** [comment]
I haven't; was planning to follow up after the core case is landed. Fine by me for you to take a look.

**Comment by simonhatch** [comment]
Ok let's parallelize then! I'll grab this.

**Comment by simonhatch** [comment]
This should be fixed, stripping out the multi-select support had the side effect of removing the need to watch for deselects, which in turn was clearing out the picker path before the next selection event was fired off. I added a test in the landed CL that tests the feature and should prevent it from regressing.

Demo: https://dev-simonhatch-c61be460-dot-chromeperf.appspot.com/report?sid=94456b7e1abb3ce7666e04adbde6f60d53372e7219612996b81bc65475585647
