### ISSUE TITLE
Catapult roll failing telemetry_perf_unittests on Windows

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2653]
@peterwashington, the catapult roll into chromium has been failing since https://codereview.chromium.org/2172213004 landed. Here is the first failing roll:
https://codereview.chromium.org/2229213004

telemetry_perf_unittests are failing on Windows:
https://build.chromium.org/p/tryserver.chromium.win/builders/win_chromium_x64_rel_ng/builds/259683

The logs seem to indicate a windows crash, and not the actual catapult roll at fault.

@petrcermak @nedn Can one of you take a deeper look tomorrow morning and decide whether to revert https://codereview.chromium.org/2172213004 or whether the problem is a Chrome crash?

**Comment by petrcermak** [comment]
All of the failures have the following stack:

```
debug::BreakDebugger+0xd
chrome_7feee2e0000!logging::InitChromeLogging+0x406
chrome_7feee2e0000!logging::LogMessage::~LogMessage+0x20e
chrome_7feee2e0000!metrics::MetricsStateManager::LoadClientInfoAndMaybeMigrate+0x257
chrome_7feee2e0000!metrics::MetricsStateManager::ForceClientIdCreation+0x117
chrome_7feee2e0000!metrics::MetricsService::EnableRecording+0x8c
chrome_7feee2e0000!metrics::MetricsService::StartRecordingForTests+0x15
chrome_7feee2e0000!metrics_services_manager::MetricsServicesManager::UpdateRunningServices+0x86
chrome_7feee2e0000!ChromeBrowserMainParts::StartMetricsRecording+0xba
chrome_7feee2e0000!ChromeBrowserMainParts::PreMainMessageLoopRunImpl+0x39f
chrome_7feee2e0000!ChromeBrowserMainParts::PreMainMessageLoopRun+0xf8
chrome_7feee2e0000!content::BrowserMainLoop::PreMainMessageLoopRun+0x9b
chrome_7feee2e0000!content::StartupTaskRunner::RunAllTasksNow+0x29
chrome_7feee2e0000!content::BrowserMainLoop::CreateStartupTasks+0x259
chrome_7feee2e0000!content::BrowserMainRunnerImpl::Initialize+0x32b
chrome_7feee2e0000!content::BrowserMain+0xfc
chrome_7feee2e0000!content::RunNamedProcessTypeMain+0x1c0
chrome_7feee2e0000!content::ContentMainRunnerImpl::Run+0x166
chrome_7feee2e0000!content::ContentMain+0x30
chrome_7feee2e0000!ChromeMain+0xc6
chrome!MainDllLoader::Launch+0x346
chrome!wWinMain+0x1ec
chrome!invoke_main+0x21
chrome!__scrt_common_main_seh+0x11e
kernel32!BaseThreadInitThunk+0xd
ntdll!RtlUserThreadStart+0x21
```

This issue is tracked in https://bugs.chromium.org/p/chromium/issues/detail?id=635255. They're suggesting [disabling "the tests"](https://bugs.chromium.org/p/chromium/issues/detail?id=635255#c21) (I assume they mean "telemetry_perf_unittests") until Friday, when asvitkine@ will be able to look into the problem.

**Comment by petrcermak** [comment]
I've gone through the log of the failing step (https://build.chromium.org/p/tryserver.chromium.win/builders/win_chromium_x64_rel_ng/builds/259683/steps/telemetry_perf_unittests%20%28with%20patch%29%20on%20Windows-7-SP1/logs/stdio) and all of the failures were due to the crash described in my previous comment. Therefore, I don't think there's anything we should do on the Catapult side. The only question is whether telemetry_perf_unittests should be temporarily disabled on Windows or not.

**Comment by nedn** [comment]
Disabling the whole telemetry_perf_unittests is too extreme. Looks like this is a flaky failure & gab@ already submitted a workaround.

**Comment by nedn** [comment]
If the catapult roll got stuck, we can just do a manual roll.

**Comment by nedn** [comment]
Looks like this is no longer a problem.
