### ISSUE TITLE
Standardize Units conversions

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#2688]
Ok, it's starting to get ridiculous how we have literal 1000 everywhere, some places comment that they are converting ms to s, most don't, and a few places define constants like MS_PER_S.

Let's add a function msToS(ms) to unit.html that just divides by 1000.0 so nobody ever needs to wonder if they should add a comment.

power metric can maybe use a similar function for converting mJ to J.

memory-infra can maybe use similar functions for converting B, KB, MB, GB.

**Comment by petrcermak** [comment]
Let's integrate this with [<tt>tr.v.UnitScale</tt>](https://github.com/catapult-project/catapult/blob/1383b507de4f08c136c893397664c1469e21010c/tracing/tracing/value/unit_scale.html). Rather than having many methods <tt>msToS</tt>, <tt>sToMs</tt>, <tt>mjToJ</tt>, <tt>jToMj</tt>, etc, let's have a generic method <tt>convertUnit(value, from, to)</tt>. <tt>msToS(ms)</tt> would then become <tt>convertUnit(value, MILLI, NONE)</tt>.

**Comment by benshayden** [comment]
:+1:

**Comment by benshayden** [comment]
This is done. :-)
