### ISSUE TITLE
Trace link missing on one battor.power_cases time series

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#2742]
I was looking at battor.power_cases results on mac:
https://chromeperf.appspot.com/report?sid=799db8af4df85d732a125648ee32c8fa37f79508cd629dcf2a34d41008ee33f1

One of the time series, the youtube ref case, is missing trace links. All the others have trace links.
This is the series missing links:
https://chromeperf.appspot.com/report?sid=39f9661ad1bad810ff3996477cc727ece95a447f25e0b4bdac50802479d59aac

**Comment by natduca** [comment]
Calling @zeptonaut

**Comment by zeptonaut** [comment]
Looking at the graph, I think that this might be a case of confusing UI rather than a bug. 

Each data point on the line for the specific user stories (e.g. about_blank, YouTube, poster circle) should have a trace associated with it. However, the data points that aggregate those three stories (_avg and _avg_ref) don't because there are actually three separate traces that each of those data points summarize.

**Comment by natduca** [comment]
I guess I'm confused though. about_blank_ref has a trace.

**Comment by zeptonaut** [comment]
Ahhh, yes. Annie's right. See #2701, but it looks like there's a bug in the dashboard that causes the wrong data series to be shown. The bug wasn't that the YouTube ref points didn't have traces associated with them, but that it was showing the aggregate data points and mislabeling them as the YouTube ref points. You should be able to verify this by going to the second link that you posted above that you said didn't have traces associated with it. At least on my computer, those data points have traces associated with them when opened in a fresh tab.

**Comment by natduca** [comment]
Makes sense. SO should we close this?

**Comment by zeptonaut** [comment]
Yep. Think that #2701 already tracks the real bug.
