### ISSUE TITLE
Related event set URL is not clickable

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2795]
Clicking on the related event set URL doesn't show anything. To reproduce:
Patch https://codereview.chromium.org/2324973002/
Open the [trace-file-id_0-2016-08-29_02-16-38-27532.html.zip](https://github.com/catapult-project/catapult/files/470913/trace-file-id_0-2016-08-29_02-16-38-27532.html.zip) in dev_server's trace-view.
Open loadingMetric in metric side panel.
Click on firstMeaningfulPaint row.
Click on "firstMeaningfulPaintCandidate 0.000 ms" event.

Expect:
The firstMeaningfulPaint event is selected.
Actual:
No event is selected.

[trace-file-id_0-2016-08-29_02-16-38-27532.html.zip](https://github.com/catapult-project/catapult/files/470913/trace-file-id_0-2016-08-29_02-16-38-27532.html.zip)

**Comment by benshayden** [comment]
The problem is that metrics-side-panel uses metricMapFunction (which converts the RelatedEventSets to dicts) then addValuesFromDicts (which converts the dicts back to RelatedEventSet diagnostics, but the RelatedEventSets only contain EventRefs), but it doesn't call resolve() on the RelatedEventSets (which would convert the EventRefs back to the real events), so related-event-set-span is stuffing EventRefs into analysis-links, and timeline-view doesn't know how to select EventRefs.

Ideally, metrics-side-panel wouldn't convert the Values to dicts and back. I think I'd like to split a function like runMetrics() out of metricMapFunction, so that metrics-side-panel can get the ValueSet that it wants directly. WDYT?

**Comment by nedn** [comment]
That sounds good to me. Though I am lost on what EventRefs is meant to use for?

**Comment by benshayden** [comment]
In results2.html and the dashboard, which can only load Values from dicts, RelatedEventSets always contain only EventRefs. EventRefs contain stableIds (along with useful info such as title, start, duration), so when you click a related-event-set-span in results2.html or the dashboard, it should eventually open the trace by its canonicalUrl and select the events by their stableId.

**Comment by nedn** [comment]
Ah, for this case, theoretically we can also tell metrics-side-panel to call RelatedEventSets.resolve(), but your proposal is to add runMetrics() so so we can avoid unnecessary serializing & unserializing operations?

**Comment by benshayden** [comment]
Exactly. https://codereview.chromium.org/2347693002
