### ISSUE TITLE
Scalar span taller in delta mode unnecessarily

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2805]
Non-delta mode:
![screenshot from 2016-09-15 15 50 16](https://cloud.githubusercontent.com/assets/2546601/18554482/53788e36-7b5c-11e6-81f7-632fd012ed57.png)

Delta mode:
![screenshot from 2016-09-15 15 50 03](https://cloud.githubusercontent.com/assets/2546601/18554499/60320b70-7b5c-11e6-88b3-635be0a829d4.png)

It turns out that the increased height is due to the <tt>#significance</tt> span element (the one that contains smileys for significant and insignificant changes) [_not_ being hidden](https://github.com/catapult-project/catapult/blob/3cc40b37372927435ed69f91aec2117488b0825c/tracing/tracing/value/ui/scalar_span.html#L425) (<tt>display: none</tt>) in delta mode. In particular, it's because of its [increased font size](https://github.com/catapult-project/catapult/blob/3cc40b37372927435ed69f91aec2117488b0825c/tracing/tracing/value/ui/scalar_span.html#L145). Note that it affects the height even when it's empty (no smiley).

Possible solutions:

1. _(partial)_ Hide the span when there's no smiley.
2. Reduce the font size of <tt>#significance</tt>.
3. Somehow crop the height of <tt>#significance</tt> (the smileys don't use the full height anyway).

@benshayden

**Comment by benshayden** [comment]
IIRC, I needed to increase the font size so that the emoji were distinguishable on my linux devicePixelRatio=1 monitor, but they're still diffificult to discern on mac, which uses cartoony emoji that look completely different.

Maybe using unicode emoji was a bad idea. If we hand-roll SVG emoji, then we can ensure that they look good on devicePixelRatio=1 monitors and on all platforms, and take up the correct amount of space, at the risk of having to hand-roll more emoji if/when there are more emotions that we want to convey about significances (doubtful).

I enjoy writing SVG, so I can do that if that sgty?

**Comment by petrcermak** [comment]
It would actually be nice to replace _all_ Unicode symbols with SVGs. It would give us way more flexibility and consistency across platforms. So definitely sgtm :wink:

**Comment by benshayden** [comment]
Petr can review on Thursday.
https://codereview.chromium.org/2349703003

**Comment by petrcermak** [comment]
I can confirm that this is now __fixed__ :white_check_mark:
