### ISSUE TITLE
Telemetry devtools clock sync fails silently

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2808]
One of the problems we ran into for #2804 was that we were trying to use the new-style devtools clock sync between Telemetry and Chrome on a version where that API isn't available. Strangely, though, there was no error logged when that request from Telemetry to Chrome for a clock sync failed.

@wangzhen127, do you know if it's possible to check for an ack or something from devtools that verifies that it processed the clock sync request?

@nedn

**Comment by wangzhen127** [comment]
The communication between Telemetry and Devtools should be able to report error if the call to RecordClockSyncMarker fail.
- [tracing_backend.py error handling](https://cs.chromium.org/chromium/src/third_party/catapult/telemetry/telemetry/internal/backends/chrome_inspector/tracing_backend.py?l=153-155)
- [tracing_handler.cc error handling](https://cs.chromium.org/chromium/src/content/browser/devtools/protocol/tracing_handler.cc?l=294)

But as you may notice, we currently [have no way of knowing if calling to tracing controller would fail or not](https://cs.chromium.org/chromium/src/content/browser/devtools/protocol/tracing_handler.cc?l=296-298).

For your case, if the API is not available, I believe devtools will [report error](https://cs.chromium.org/chromium/src/content/browser/devtools/devtools_protocol_handler.cc?l=135-137) instead of silently swallowing it. @caseq may confirm.

**Comment by wangzhen127** [comment]
Closing this as it is obsolete.
