### ISSUE TITLE
Revision pro/con list

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#2834]
jkummerow mentioned that sometimes they know that a change regressed some metrics but improved others, and it would be useful to be able to see them all together to figure out if the regressions are worth it, instead of just the regression alerts. Might be a job for results2.html? :-)

@fmeawad @lpy @eakuefner @Apeliotes

**Comment by anniesullie** [comment]
Currently, we accomplish this on the dashboard through a totally different codepath: /group_report?rev=xxxx, where xxxx can be a v8 rev. Right now, it only lists alerts, and v8 team would like finer-tuned data. We had discussed making a fake sheriff rotation that is way more sensitive than the actively monitored one in order to generate deeper alerts for this page.

I'm not sure what the long-term solution looks like, ideally it uses results2, and we have some sane way to just check the data points at every revision. But there are lots and lots and lots of tests for a revision, so it would be hard to just type in a revision and generate a results2 on the fly for all the tests.

**Comment by benshayden** [comment]
I think we have an eye on this feature without this issue.
