### ISSUE TITLE
Stoppage alert emails have broken stdio links

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2923]
Links to stdio in stoppage alert emails all target `none`. This indicates that there's some issue with plumbing `stdio_link`, as seen here: https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/send_stoppage_alert_emails.py#L31 through.

@Apeliotes

**Comment by CalebRouleau** [comment]
Any idea when this could get fixed? My team is still affected. 

Thanks for the help.

**Comment by anniesullie** [comment]
Notes on debugging: try taking an example alert from Caleb's rotation, and making a unit test that tries to write the email with it.

One thing I think is likely is that there are problems in recipes where `a_stdio_uri` gets uploaded to dashboard as `a_a_stdio_uri` and someone worked around it in some places instead of correcting it in add_point.py. send_stoppage_alert_emails does not work around this issue.

**Comment by CalebRouleau** [comment]
Any timeline for the fix for this bug? My team is still affected and it got worse because the switch to swarming made the workaround more convoluted.

**Comment by ehanley324** [comment]
So in swarming these are broken due to the mismatch between test name and step name.  results_dashboard.py forms the results dashboard stdio link from just the test name, but swarming appends several suffixes to the step name which causes the mismatch.  

martiniss@ is working on getting this naming fixed so I will reassign him to this for the short term.  The chromium bug for the stdio links is here: crbug.com/663901 which martiniss is assigned to.

It isn't clear to me that the fix to this bug is the same as the swarming stdio fix since this pre-dates swarming, but Stephen's fix should make the original workaround work.  Stephen can reassign this once the other bug is complete to someone who can handle this on the telemetry side.

**Comment by CalebRouleau** [comment]
Any update on this? We are still affected.

Thanks!

**Comment by anniesullie** [comment]
Sorry for the slow pace here. WIP CL:
https://codereview.chromium.org/2682173004

@martiniss: Any progress on the step names? My CL adds the buildbot status page, but we really need to fix the step names as well.
