### ISSUE TITLE
multi-event-sub-view Usability improvements

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#2928]
@lpy 
- Please use `<label>` instead of `<div>` to label the radio buttons and set `label.htmlFor`, so that we can click on the labels to select the radio buttons.
- set display:none on the histogram-span when histogram.numValues === 0 so that you don't show a trivial statistics table `count: 0; min: inf; max: -inf`.
- In buildDiagnostics_: keep the selectedKey in the diagnostics for consistency. Also, if you select Start time, then the start time of each event is not displayed anywhere, but duration is displayed in both the `duration` column and the `event` column.

Separately, I will fix histogram-span's setting the left margin, and format the underflow bin's bar name using Unit.format() for consistency.

**Comment by lpy** [comment]
I have some dumb questions:

* Do you mean set `htmlFor` to the `id` of radio button? Just a little confused since we don't have `id` for radio button.
* Do you mean also add `diagnostics['selectedKey'] = new xxxx;` in `buildDiagnostics_`?

Yes, if you select `start` as the key, then that field won't show up in the detail table, the reason `duration` show up in event column is because of the nature of how we name a slice. Do you think it's useful to show all the fields no matter which filed we choose as the key?

**Comment by benshayden** [comment]
input.id = e.label
var label = document.createElement('label');
label.htmlFor = e.label

Alternatively, define a new tr-ui-b-labelled-radio-button polymer class with <input id=radio ...> <label for=radio ....>

To the second question, maybe not 'selectedKey', but just build the sample diagnostics the same way regardless of what the selectedKey is?

**Comment by lpy** [comment]
<img width="719" alt="screen shot 2016-11-04 at 2 25 24 pm" src="https://cloud.githubusercontent.com/assets/1453861/20023029/954d7fe6-a29a-11e6-915a-942d283cbe86.png">

**Comment by lpy** [comment]
I think I finished my part, thus deassign myself from this. Are we done here?

**Comment by benshayden** [comment]
Thanks!
