### ISSUE TITLE
Get rid of == and != in dashboard/ code

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2932]
It's not completely clear that this should be done, but I think it certainly merits a discussion.

It's long been the trace viewer standard to avoid `==` and `!=` in favor of `===` and `!==`. It's also the recommendation from the [airbnb style guide](https://github.com/airbnb/javascript#comparison--eqeqeq), which we've generally been using as a guide for our ES6 integration.

With that being said, it's worth considering _why_ we avoid `==` and `!=`: it's because they produce unexpected behavior to programmers not familiar with Javascript, which describes many programmers contributing to the trace viewer codebase. 

This makes the decision about whether we should apply this same rule to dashboard code difficult: the programmers contributing to dashboard generally understand Javascript better. Complicating the situation is the fact that dashboard has many (~100?) existing cases where `==` and `!=` are used _correctly_, and would have to be carefully migrated to use triple equals.

My personal opinion is that we should allow double equals in dashboard code for now, but aim to migrate to triple equals in the long-term, if only for the sake of consistency.

I know @anniesullie likes `==` and `!=`, but didn't go as far as to express an opinion on whether we should keep them around long-term.

@anniesullie @eakuefner @benshayden what do you all think?

**Comment by anniesullie** [comment]
@natduca has opinions too, I'm sure!

Interestingly, using == and != used to be part of the [Google style guide](https://google.github.io/styleguide/javascriptguide.xml), but it is now silent on this point. I personally prefer != and == after using them so long, but it's more habit than something I think should be put directly into a style guide. My thoughts:

Novice JS programmers often use `null` and `undefined` interchangeably, so that you end up with code like this (writing as a function with an optional argument, since it's an easy example, but I see variants of this all over the place):

```
function f(opt_arg) {
  if (opt_arg === undefined) {
    // set to default
    ...
  }
}

var foo = null
f(foo);
```
The opt_arg check is tricksy!

1. If you use `===`, you **must** always ensure callers pass `undefined` and not `null`, and have a clear convention throughout the code. We should have a clear convention, but it is difficult to enforce programatically.
2. If you use `==`, you can accept `null` and `undefined` interchangeably. But then, it's not great that we're doing that. However, it's hard to suss out where in the code we may be doing that already.
3. If you use `if (!opt_arg)`, you slip right through our lint checks, but this is the worst option, since 0 or "" are likely valid values for many optional arguments.

A lot of style guides and JavaScript programming articles advocate always using `===` and `!==`, but I think that papers over the bigger issue here, that no matter which one you choose you need everyone to understand strict/loose equality and truthiness/falsiness in JavaScript, and that's a tall order for a codebase mostly contributed to by programmers of other languages. I don't see anything about this in the airbnb guide, unfortunately. But maybe we should be aiming to have some clear conventions (enforced in code review if not automatically) around null vs undefined?

**Comment by zeptonaut** [comment]
> but I think that papers over the bigger issue here, that no matter which one you choose you need everyone to understand strict/loose equality and truthiness/falsiness in JavaScript, and that's a tall order for a codebase mostly contributed to by programmers of other languages

Totally agree. Not sure there's an easy way to do this, other than just education through code review.

> 
But maybe we should be aiming to have some clear conventions (enforced in code review if not automatically) around `null` vs `undefined`?

At least for trace viewer, we already [mention this in the style guide](https://github.com/catapult-project/catapult/blob/master/docs/style-guide.md#undefined-and-null), but there are still [100 or so places where we still use null](https://cs.corp.google.com/search/?q=p:github+f:%5Ecatapult-project/catapult/+f:tracing+null&m=100&det=matsel&type=cs).

I'm not sure of the exact grounds behind the aversion to `null`, but I've always assumed that we have similar reasoning to [this Stackoverflow response](http://stackoverflow.com/a/28825847).

**Comment by zeptonaut** [comment]
Going to close this as WontFix, given that it doesn't seem like we have consensus that this is a good idea.
