### ISSUE TITLE
Add RelatedHistogramBreakdown diagnostics to memoryMetric.

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#2933]
Memory metric produces an overwhelming number of histograms. value-set-table can hide the less important ones if you tell it which ones are broken down into which other ones.

[memory graphical model](https://docs.google.com/document/d/1EK2fc3UuXWl1TAhqikXBlpxkHN96d9KONUd0FyP2vGs/edit)

[how-to-write-metrics](https://github.com/catapult-project/catapult/blob/master/docs/how-to-write-metrics.md)

@chromy @nedn

**Comment by nedn** [comment]
@perezju

**Comment by chromy** [comment]
I have a CL which adds a `RelatedHistogramBreakdown` to each `all_processes` histogram explaining how that histogram breaks down by process.
In the metrics pane it looks like this: https://screenshot.googleplex.com/0WkGMJoJ8uR
is that what we were aiming for?

**Comment by benshayden** [comment]
It looks like you're using RelatedHistogramBreakdown.*add*(histogram) --
the legend keys look like histogram names, which are quite long in your
case.
I'm working on a CL to show the full legend keys instead of truncating
them, but I wonder if you might still rather use
RelatedHistogramBreakdown.*set(name,
histogram)* instead so that you can make the legend keys
"browser"/"renderer" etc.
WDYT?

**Comment by chromy** [comment]
Awesome glad to know I was along the right lines :)

That sgtm, I had it using `set` for a while I was a bit confused by this error message: https://github.com/catapult-project/catapult/blob/f5d3b3605c72ff72fce258c4d78a66e137688226/tracing/tracing/value/diagnostics/related_histogram_breakdown.html#L50

It seemed kind of awkward to make the legend keys a suffix of the histogram name in this case since at the moment all the names look like:
memory:chrome:all_processes:reported_by_chrome
memory:chrome:renderer_processes:reported_by_chrome
so the bit we are interested in for the legend key is buried right in the middle :(

Do the names have to be a suffix of the histogram names for some reason, or is it just a sanity check?

**Comment by benshayden** [comment]
@nedn originally requested enforcing that suffix check in [msg32 of this CL](https://codereview.chromium.org/2133963002#msg32). (You have to Show older messages and Expand all to see it...)

Ned, do you think it would be ok to allow RelatedHistogramBreakdown keys to be arbitrary strings instead of strictly suffixes of Histogram names?

**Comment by nedn** [comment]
I worry that people may be confused when they click on link "X" & metric "Y" is displayed. Maybe we can compromise this by displaying the full metric name when people hover over the link?

**Comment by benshayden** [comment]
https://codereview.chromium.org/2452983003

**Comment by benshayden** [comment]
These have since been changed to RelatedNameMap+Breakdown
