### ISSUE TITLE
CPU usage track memory limit breaks loading of large traces

### ISSUE THREAD

**Issue by borman** [catapult-project/catapult#2935]
The bug is introduced with "CPU usage track" feature and this exact change: https://github.com/catapult-project/catapult/commit/4bad393177e652465f903239ce1fb8e71021abda#diff-f3b34f1e22557e679c8ba24540b85c84R71

If a trace file is large enough to trigger this exception, it aborts loading of trace file altogether. This is a regression, because older versions would load such trace files just fine.

Suggested fix: if this limit is triggered, do not generate CPU usage track, but still load the trace file.

**Comment by anniesullie** [comment]
@natduca @nedn @zeptonaut @Alex319

**Comment by zeptonaut** [comment]
@borman, do you have an example trace that you can give us that triggers the bad behavior?

The reason I'm hesitant to not generate the CPU track is that we generally have a policy w/in trace viewer of failing catastrophically when something goes wrong. This guarantees that we fix things like this when they break rather than accidentally letting the errors go on indefinitely.

**Comment by borman** [comment]
You can use this python script to generate a trace file that triggers the failure in question:
```py
def main():
    print '['
    ts = 0
    tts = 0
    scale = 1000
    for i in xrange(110000):
        dt = scale * 10
        dtt = scale * (1 + 5 * (i % 2))
        print '{"ts": %d, "tts": %d, "dur": %d, "tdur": %d, "pid": 319504, "tid": 123456, "cat": "test", "ph": "X", "name": "Sample"},' % (ts, tts, dt, dtt)
        ts += dt * 2
        tts += dtt

main()
```

**Comment by danw** [comment]
I'm still hitting this even with the latest change, as I use http://github.com/nico/ninjatracing to generate traces from our android builds. In some cases, those are well over 5000 seconds (extra-large builds, slow machines, something hanging due to a bad machine, etc).

It's annoying that this was a silent error for the user, just showing up in the console log. If there's going to be a limit, there should be some user-visible indication that the file failed to load due to that limit.

**Comment by zeptonaut** [comment]
Hi @danw,

Sorry for the frustration. Could you attach the trace causing the problems?

**Comment by danw** [comment]
Here's one of our traces that is about 7700 seconds long: [ninja_log.json.gz](https://github.com/catapult-project/catapult/files/582319/ninja_log.json.gz). It loads fine with trace2html if I disable the CpuUsageTrack.

**Comment by zeptonaut** [comment]
@danw, @randomascii

I think that https://codereview.chromium.org/2468883002/ should have fixed any problem with running into the CPU track's size limit. To view an already-HTMLified trace that has this problem, you can get a Catapult checkout at head and do:

```
tracing/bin/trace2html <your_old_trace>
```

this will generate <your_old_trace>.html, which should be an HTMLified version of your old trace created with the latest version of trace viewer.

Sorry that this is a pain: we now have tests in place that should prevent this particular problem from cropping up again.

**Comment by randomascii** [comment]
I just tested with canary (still broken) and then with a local build (works) so I guess the fix rolled after the last canary build. Anyway, looks good. Thanks.

**Comment by zeptonaut** [comment]
Good to hear! Thanks for checking.

**Comment by randomascii** [comment]
Canary just updated to 57.0.2942.0 and the fix is now live in canary. Confirmed fixed.
