### ISSUE TITLE
Perf dashboard charts should, by default, end at the present time rather than the last data point

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2940]
This would help make it clear that new data for a benchmark isn't available, like in this case:

![4ktfs8jhnwh](https://cloud.githubusercontent.com/assets/1407397/19362925/7181381e-9156-11e6-9c0f-58be5f1ee2ba.png)

The current date is 10/13 and the last data available is from 10/11. However, because the X-axis of the chart ends at the time that the last data point was generated rather than the time that the chart was generated, it looks like new data is still coming in, which is misleading to users.

**Comment by eakuefner** [comment]
@zeptonaut are you working on this atm? i think the most appropriate solution here involves polling gitiles for the current HEAD rev/timestamp. i'm super happy to pick this up if you're not planning on doing it in the near future.

**Comment by zeptonaut** [comment]
Nope, I'm not, and would be thrilled if you were willing to pick it up.

**Comment by eakuefner** [comment]
I did some looking into this and it turns out to be more complicated than anticipated, actually. We have tests that are keyed by Chromium revision number, by git hash, and by Chrome version, so it's not necessarily easy to figure out 1. what the end point should be and 2. how many steps should be between the last data point and the actual end of the graph.

It seems like the right area of focus to address this usability concern might be in improving how we surface stoppage alerts on the report page. That's not something I want to pick up right now, but it does seem like it would be a workable approach.

**Comment by anniesullie** [comment]
@natduca @Apeliotes I think there's a longer-term concern with the way we display the x-axis. Right now we fix the axis so that each point is equidistant, regardless of value, because the differences between some of the x-axis types are meaningless and confusing. But we may want to consider making upload time the x-axis value, since it does have a basic meaning, and would make it easy to do things like this.

**Comment by zeptonaut** [comment]
+1 to @anniesullie's concern

I've seen countless conversations about performance derailed by a simple confusion about the x-axis on the perf dashboard.

**Comment by benshayden** [comment]
Archiving. V2SPA allows toggling "fixed" x-axis, and the medium-term goal of switching the x-axis from commit positions to revision timestamps should improve clarity further.
