### ISSUE TITLE
Create a V8 Benchmark for Runtime call stats.

### ISSUE THREAD

**Issue by fmeawad** [catapult-project/catapult#2949]
Currently the runtime call stats [benchmarks](https://chromeperf.appspot.com/report?https://chromeperf.appspot.com/report?sid=1be638d9f575cfb937fab7d6ea8c133704cf8b2b1a5929a722ac21baf7cec8ad&start_rev=36493&end_rev=10000000000000) are not using telemetry, we have recently landed a [metric](https://codereview.chromium.org/2436193002/) that would allow us to run the runtime time stats using a TBMv2 benchmark instead.

This issue is to track the progress on creating and landing that benchmark.

@camillobruni @nedn

**Comment by nedn** [comment]
This should be a crbug since majority of patch work gonna be in chromium side

**Comment by natorion** [comment]
For completeness sake, what is the chromium tracking bug?

**Comment by fmeawad** [comment]
http://crbug.com/664318

Since a benchmark is up and running, I will mark that bug as fixed.

**Comment by natorion** [comment]
What is missing in order to activate it for all platforms?

**Comment by anniesullie** [comment]
@fmeawad who is the current owner?

**Comment by fmeawad** [comment]
For Android, the pages recorded are not android friendly, there was suggestions that we use a different android page set. 
I believe this is going to be a none-issue once we migrate to the new metric/benchmarks by @mythrialle

**Comment by fmeawad** [comment]
@mythrialle Adding you as owner here, feel free to bounce it back.

**Comment by natorion** [comment]
So technically we are "only" missing the pageset. The metric collection etc should work? Mythri is AFAIK working on doing RCS for non-startup phases, so I am not sure if the pageset she is creating is going to be suitable.

cc @rmcilroy @camillobruni

**Comment by fmeawad** [comment]
AFAIK: Mythri is not excluding startup phase, it is going to be one of 4 phases (RAIL)

cc @nedn for suggestions on whether we should add more platforms to the current metric or wait for the new one.

**Comment by rmcilroy** [comment]
re #9 I don't think Mythri's benchmarks are going to be a replacement for the benchmark - I think we still want to measure top25 in addition to v8.browsing (correct me if I'm wrong Camillo).

**Comment by rmcilroy** [comment]
Fadi's comment is right, Mythri's benchmarks don't exclude startup, but they are a different behavior and do measure additional interaction other than startup. As such, I think we want to have top25 for startup, and it would be great if we could enable this for Android too.

**Comment by nedn** [comment]
The system_health's browsing stories doesn't wait long enough after loading, so I agree that it may not be the best candidate for top25 startup.

Though on the topic of optmizing top X pages for loading startup, I wonder whether V8 team should just switch to use the same top Y pages used by loading-dev team.

The mobile version is in https://cs.chromium.org/chromium/src/tools/perf/page_sets/loading_mobile.py?q=loading.mobile&dr=C&l=30 & we're working on adding the desktop version.

@randalnephew @nyaxt

**Comment by mythrialle** [comment]
Yes, I think the loading_mobile page set would be good to measure startup time on Android.
 
I can add a new benchmark to measure startup time on the page suggested by nedn ( https://cs.chromium.org/chromium/src/tools/perf/page_sets/loading_mobile.py?q=loading.mobile&dr=C&l=30) for the Android devices.

**Comment by natorion** [comment]
That would be a sensible solution. +1

**Comment by camillobruni** [comment]
Why do we need the google landing page 4 times in the mobile pageset, that seems like wasting resources on generating duplicate information? Other than that I don't have strong opinion on what we exactly measure on mobile as long as we cover something.

Again, requirements for blink might be different than for V8. I agree with ross on this and I'd like to have the exactly same page running on android (and that's independent of tracking mobile pages) to get a proper estimate of the impact of a single CL. If the pages behave differently this is quite difficult to guess.

**As for top25:** On desktop I added several pages based on their framework as this has the biggest influence on JS usage pattern, maybe that's not necessarily a requirement for blink, but it is very important for V8.

**Comment by nedn** [comment]
@camillobruni the reason we have google landing page 4 times is because they have different characteristic:
https://www.google.com/search?q=flower#q=flower+delivery --> search result include image & in English

https://www.google.co.in/search?q=%E0%A4%AB%E0%A5%82%E0%A4%B2&rct=j#q=%E0%A4%AB%E0%A5%82%E0%A4%B2+%E0%A4%B5%E0%A4%BF%E0%A4%A4%E0%A4%B0%E0%A4%A3 --> search results are in Indian

https://www.google.com.br/search?q=flor#q=Entrega+de+flores&start=10 --> google search in BRIMM

https://www.google.co.id/#q=pengiriman+bunga --> google search results in BRIMM

Also the loading page sets are not blink specific but about anything that's interesting in term of page load, including JS startup time. So with that, I expect them to be a superset of which pages v8 cares about in term of startup.

If you want, we can add some pages your team like that are not already in that list & tag them with "javascript" tag & have v8 team only use the stories that have interesting js workload. Sharing the stories here is important because Chrome is very crashy on these real world pages, so the more page we share, the less crashy bugs we have to deal with in total.

@nyaxt your thoughts?
