### ISSUE TITLE
centralBins is blocking binless mode

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#2956]
We don't use centralBins in any salient place and it's not a super useful concept: underflow and overflow bins are not special; they're just bins that have a lower bound of Number.MIN_VALUE and an upper bound of Number.MAX_VALUE. Further, this is blocking binless mode (@benshayden why?).

@nedn

**Comment by nedn** [comment]
+1 to bins with lower bound of -inf & upper bound of +inf

**Comment by benshayden** [comment]
I was a bit vague on that CL because centralBins isn't a hard-blocker for binless mode. It would be technically possible to have a binless mode with the current architecture if people really want to keep it, but the easiest way that I see to have binless mode would be if there were a single array of bins. But the current architecture assumes that underflowBin !== overflowBin, and that neither are in centralBins, so the current architecture assumes that there are always at least 2 bins.

**Comment by benshayden** [comment]
As an aside, it seems like we're settling on "binless" mode meaning that there's exactly one bin, and disallowing zero bins. That would kick the can of where to put sample diagnostics in binless mode -- they can continue to go in the bin. We still might eventually want to shuffle how sample diagnostics are stored so that they can be associated with their sample value.

**Comment by nedn** [comment]
Note that binless mode is only for legacy tests, which I think don't use diagnostics at all. So it's not important to support diagnostics for them.

**Comment by benshayden** [comment]
To be clear, they will need histogram-level diagnostics such as IterationInfo, but, yes, probably not sample diagnostics.
