### ISSUE TITLE
Improve the coloring for memory_metric breakdown

### ISSUE THREAD

**Issue by chromy** [catapult-project/catapult#2970]
ColorScheme sometimes gives too similar colors to diffrent bars in breakdown_span.
This happens in for browser_process and renderer_processes which somehow end up
with the exact same color.

**Comment by benshayden** [comment]
Thank you for putting the doc together! :-)
Looking at the list of special purpose colors, it looks like it's composed of several groups of colors.
My hypothesis is that each of those groups of colors could be split into a separate FixedColorScheme class, likewise for the ChromeUserFriendlyCategoryDriver colors and memory breakdown colors.
The remaining use-case for ColorScheme (General Colors) seems to me to be different enough from Special Purpose Colors that it should be handled by a separate class from the FixedColorSchemes; so leave it where it is in ColorScheme, or rename ColorScheme to GeneralColorScheme to clarify the difference.
So, for example, ThreadTimeSlice would say something like ThreadTimeColorScheme.getColorId() instead of tr.b.ColorScheme.getColorIdForReservedName(); UserExpectation would say UserModelColorScheme.getColorId() instead of getColorIdForReservedName(), etc.
The risk is if there are any places that call getColorIdForReservedName without knowing which FixedColorScheme they want, they'd need to do something slightly gross like try a bunch of named FixedColorSchemes or iterate over all of them using a registry.
It looks like trace_event_importer.html might be the only such caller; I'm not sure if that "cname" is actually limited to one of the groups, but I would be ok with letting it try several different named FixedColorSchemes.
tr.v.d.Breakdown would need a registry of FixedColorSchemes. It might be the only caller that would.

WDYT?

**Comment by chromy** [comment]
sgtm 👍 I will do it in pieces rather than try to refactor all callers at once.

**Comment by benshayden** [comment]
Can this be closed? I'll open a new bug about refactoring ColorScheme and FixedColorScheme.
