### ISSUE TITLE
We can't statically enforce certain eslint rules because --fix doesn't work

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#3004]
Certain eslint rules that can be fixed using --fix would be good to enable, but are infeasible to fix by hand in Catapult. There are at least two that I know of, 1TBS and `let`. @zeptonaut is looking into fixing the upstream issue. If that gets done, then we can probably --fix and enable these two rules.

**Comment by zeptonaut** [comment]
This is tied closely with eslint/eslint#7510.

**Comment by BenoitZugmeyer** [comment]
I just read the eslint/eslint#7510 comments and after a quick search I found this issue. I am the author of eslint-plugin-html , and I just released a new major version featuring all improvement I wanted to see within my plugin, including the --fix support. I hope it can help you and I'd love to have some feedback about this new version. I had to rewrite it nearly completely, and I wouldn't be suprised if some regressions showed up.

**Comment by eakuefner** [comment]
Thanks Benoît! We'll follow up at some point and let you know.

**Comment by zeptonaut** [comment]
^^ what he said! Thanks for your hard work. Getting this working will have a huge impact in the health of our codebase.

**Comment by eakuefner** [comment]
@zeptonaut as per https://codereview.chromium.org/2671663002 I assume you've tested this and it does work?

What was the trouble you were having getting it to work earlier?

**Comment by zeptonaut** [comment]
I was running into a few things:

- There's at least one case where eslint didn't know hot to fix [`no-multiple-empty-lines`](http://eslint.org/docs/rules/no-multiple-empty-lines) when there wasn't a closing `<script>` tag in the file
- There was a bug in our eslint wrapper script, `run_eslint`, that was preventing it from properly printing eslint's output. This is fixed in [this CL](https://codereview.chromium.org/2672013002/), which I have out to you right now.
- Both `eslint` and `eslint-plugin-html` needed to be rolled, whereas I originally only rolled `eslint-plugin-html`.

I have `--fix` working locally after all of these changes, and I have to say: it's pretty incredible.

**Comment by eakuefner** [comment]
Thanks for the explanation. I had thought rolling eslint itself might make a difference.

**Comment by eakuefner** [comment]
I think this is fixed!
