### ISSUE TITLE
Warnings from eslint about ignored files being treated as errors by presubmit script

### ISSUE THREAD

**Issue by andrey-malets** [catapult-project/catapult#3034]
Example CL: https://codereview.chromium.org/2525373002/

Example presubmit job log can be found here: https://build.chromium.org/p/tryserver.client.catapult/builders/Catapult%20Presubmit/builds/5228/steps/presubmit/logs/stdio

A warning about ignored file should not be treated as an error by presubmit script and fail the job. Essentially, I wonder why skipping ignored file should be a warning in the first place.

**Comment by andrey-malets** [comment]
@eakuefner, @nedn FYI.

**Comment by nedn** [comment]
@zeptonaut

**Comment by eakuefner** [comment]
eslint warns when you pass a file explicitly that is ignored, since according to their world view, there should be no sane reason to ever do that. In practice, the depot_tools PRESUBMIT system passes individual files to eslint based on the content of the CL, so that assumption doesn't make sense in our world. There doesn't appear to be any way to simply suppress these warnings, at least using the command-line API.

However, it turns out that we're treating *any output* from eslint as "it found errors", where we should really be checking the exit code instead. If the exit code was 0, then that means there were no errors, since --max-warnings is -1 by default according to http://eslint.org/docs/user-guide/command-line-interface. Warnings should, as in this case, be fine to emit generally, because we (and `eslint-config-google`) use "error" severity for all actual lint rules.

The place to fix is https://github.com/catapult-project/catapult/blob/master/catapult_build/js_checks.py#L90.

**Comment by eakuefner** [comment]
CL: https://codereview.chromium.org/2535983002

**Comment by andrey-malets** [comment]
Thank you for explanation, closing the issue.
