### ISSUE TITLE
load:energy_sum is always zero

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#3061]
Graph: https://chromeperf.appspot.com/report?sid=9d160f40ff527e3cb25d6442520cddf346ea97f738a77fa8475091dbe7a267e3&rev=435383

@Alex319, any idea what might be going on?

**Comment by Alex319** [comment]
I think I understand the problem here. The problem is that the load:energy_sum metric looks at the interval between the navigation start and time-to-interactive. If there is no event corresponding to the time-to-interactive (and there isn't any in the about:blank case, as there's nothing to load) then there won't be any of these intervals.

I think the correct thing to do here (ant I think we've had problems similar to this before on about:blank) could be to disable loading metrics completely for about:blank. Since there's nothing to load, the idea of measuring how much energy it takes to load about:blank doesn't have much meaning anyway.

**Comment by Alex319** [comment]
Another thing we can do in the metrics code itself is to not report any data for this metric if there are no loading intervals rather than report a "zero" value.

**Comment by zeptonaut** [comment]
+1

I think that this sounds like it's probably the best path.

**Comment by zeptonaut** [comment]
Hey Alex,

Any update on making the metrics not report any data if there are no loading intervals rather than a zero value?

**Comment by Alex319** [comment]
I thought I had already done that; I must not have done that. I will have
to check again.

-Alexander Mont

**Comment by zeptonaut** [comment]
Hi Alex,

Any update on this?

**Comment by Alex319** [comment]
I'm currently working on a different task but as soon as I'm finished, I'll get back to this.

**Comment by Alex319** [comment]
After looking at this further, we determined that the best course of action here is to leave it up to the histogram to handle the case where there are zero samples in the histogram. Currently, the histogram seems to be doing the correct thing in this case: just not reporting anything in this case for mean, standard deviation, or variance.
