### ISSUE TITLE
Story-specific metrics

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3078]
Currently, TBMv2 metrics only have access to the information in traces. However, there are some telemetry stories that directly compute interesting high-level metrics. The traces produced by these stories only contain low-level events, so TBMv2 metrics lack access to the high-level metrics produced by the stories. Instead of requiring metric authors to re-compute the metrics from whatever's in the traces, let's allow them to log the existing metrics from the stories into the traces, and make it trivial for the TBMv2 metrics to pass the information through to Histograms.

These stories include tough_video_cases, @eakuefner what else?

I imagine that telemetry would use py_trace_event to log the information from the stories to the trace, but how should telemetry get the information from the stories? Maybe @nedn can help here?

I can figure out how to make it easy for metric authors to take the information from the trace and produce Histograms once we have a trace containing the information. A new kind of ModelHelper might be... helpful. Once we have a trace, it'll be a SMOP.

**Comment by eakuefner** [comment]
I think the term we agreed on was story-specific metrics. I have an idea about how this should be done presently: We should define an API on `Story` called `AddStorySpecificMetrics` that is called after `RunPageInteractions`. I think we should consider blocking this on Python histograms so that users can use histograms instead of legacy Telemetry values. Alternatively, we could support only single-bin histograms initially and give people a simple name/number API.

Off the top of my head, other clients that could make use of this include the HTML parsing tests that @ulan wanted to add: https://codereview.chromium.org/2119413003 and existing microbenchmarks such as Octane and Sunspider.

I'll try to start a design sketch of this today, including a discussion of whether to wait for Python histograms or give people a simple scalar-based API that we back with single-bin histograms.

**Comment by eakuefner** [comment]
Also, agreed: maybe it's time to establish a `telemetry_model_helper`.

**Comment by eakuefner** [comment]
@benshayden pointed out that it may be necessary for stories to measure *while* running, so this could also be a hook that we define on `action_runner` instead.

**Comment by nedn** [comment]
Not `action_runner`, since not all stories have hook to `action_runner`, which is just a wrapper around `tab` object.
Remember that `py_trace` is global, so we can just add s.t like `story.AddStorySpecificMetrics()` that just internally augment events to telemetry traces.

Not that this method is not a callback to be called by telemetry framework, so it can be called by user at anytime during story run.

**Comment by eakuefner** [comment]
Oh, understood. Yeah, I think that design will work.

**Comment by eakuefner** [comment]
Design doc: https://docs.google.com/document/d/11O_Gf74QPImgngMMnVWqZXR9FI1I5hhumOt2JIpfAEs/edit

**Comment by eakuefner** [comment]
Archiving in favor of the PageTestResults AddHistogram stuff that already exists.
