### ISSUE TITLE
Dashboard - Invalid story filter default for media.tough_video_cases_extra

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3103]
Copy/paste my comment from [crbug.com/660245](http://crbug.com/660245)

That story filter doesn't seem valid, how was it picked? When I go to the dashboard it automatically populates the story-filter field with "garden2.10s.webm.seek.warm"

But digging through the log it seems like that's not a valid option, most of the stories look something more like: video.html?src=tulip2.ogg&type=audio

Not clear if this is limited to media.tough_video_cases_extra, but that's where we saw it

**Comment by simonhatch** [comment]
Wrote a quick script to check crbug for any bisect that reported a test with no output values for the last 3 weeks and only found media.android.tough_video_cases (https://bugs.chromium.org/p/chromium/issues/detail?id=660245#c11) as another candidate for bad story filter.

**Comment by perezju** [comment]
Thanks for looking it up. It turns out that `media.*` benchmarks sometimes produce test paths which do not directly correspond to stories. Sometimes the story name could be guessed, but It's probably safer in those case to bail out and not try to do a bad guess.

I've sent out a [CL for review](https://codereview.chromium.org/2589373003/).
