### ISSUE TITLE
Alert current and upcoming sheriff if a sheriff forgets to do sheriffing

### ISSUE THREAD

**Issue by ehlemur** [catapult-project/catapult#3117]
Regarding the alerts for regressions and improvements in the Performance Dashboard, it would be nice if one could alert the current and upcoming sheriff if a sheriff forgets to do sheriffing (e.g. there are untriaged alerts+improvements from Thu and earlier, on Friday)

**Comment by anniesullie** [comment]
This is an interesting idea. I think the biggest blocker is that different teams have different ways of knowing who the current and previous sheriff are: some use a rotation url, but most just have alerts sent to a mailing list. For your use case, which sheriff rotation is it? How would the dashboard know who the sheriff is and what days the rotation is on?

**Comment by hkjellander** [comment]
For us, it's the "WebRTC Perf Sheriff" (https://chromeperf.appspot.com/alerts?sheriff=WebRTC%20Perf%20Sheriff). I understand the problem now, since the Perf dashboard doesn't really have any integration with sheriffing (as Annie explained).

I guess this would have to be implemented as some kind of script that runs periodically and queries Perf dashboard APIs (are there such?) about alerts and their age. Then it could send an e-mail to a rotation alias.

It seems to depend on if there's a Perf dashboard API allowing to write such a script. Otherwise this would have be something that's built into the Perf dashboard (which unfortunately will only be available to Googlers, since I believe the rotations app engine app is not open source?).

**Comment by anniesullie** [comment]
Unfortunately, we don't have an API for alerts. There are a few different use cases which don't add up to it being high enough on our list to implement ourselves, but we would be okay with someone else implementing if it had the proper security. I think [cloud endpoints](https://cloud.google.com/endpoints/) would allow you to generate API keys that we can give out to clients so that we know it is okay to send them internal alert data.

**Comment by benshayden** [comment]
The alerts api is [being generalized](https://chromium-review.googlesource.com/c/catapult/+/1081111) to support V2SPA and soundwave. In order to find the untriaged WebRTC alerts that were found on a given day, a client could POST this query: `/api/alerts?sheriff=WebRTC+Perf+Sheriff&bug_id=&min_timestamp=2018-05-04+00:00&max_timestamp=2018-05-05+00:00`

Archiving this issue since it appears there isn't anything else the dashboard should do.
