### ISSUE TITLE
Stop creating data stoppage alerts for ref builds

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#3121]
There are way too many data stoppage alerts to handle for non-ref builds; it's too hard to triage with double the alerts for ref failures.

@eakuefner @jessimb

**Comment by anniesullie** [comment]
CL: https://codereview.chromium.org/2606383008

**Comment by eakuefner** [comment]
In reviewing the CL, I started to wonder if we might have a roadmap for making these alerts easy to triage and re-enabling them.

In a similar vein to memory-infra and their artificial paring of values so that they can use the perf dashboard, this seems like something we would in theory like to be able to do, but lack the technology for at present. So I think it would be interesting to see if we could fix this problem with better alert grouping, or something like. I expect the number of cases where the ref build stops showing but ToT does not should be relatively small, but in an ideal world, it's coverage I'd like to have.

**Comment by anniesullie** [comment]
We're actually moving toward more having the ref build be a nice-to-have. There's really not much we can do when it fails since the problem is usually in Chrome and not telemetry or the recipe. We're going to start artificially coloring it green on the buildbot status page.

@ehanley324 @nedn

**Comment by eakuefner** [comment]
Neat, I wasn't aware of that plan. Actually, it occurs to me that much of what we wanted the ref build to do could be subsumed by DeviceInfo/BuildbotInfo annotations, since the canonical explanation for why ref builds have been useful has been "imagine if something changed about the test environment but you didn't know it".

**Comment by anniesullie** [comment]
This is now fixed.
