### ISSUE TITLE
Perf Dashboard: No way to see history on sizes perf graphs

### ISSUE THREAD

**Issue by asvitkine-chromium** [catapult-project/catapult#3192]
Chrome version: 55.0.2883.95 (Mac)
URL: https://chromeperf.appspot.com/report?sid=5c4d18bdb14187843fec230023fe424da08f127596cdd8ee17e1b54ebf68e8c9

Please copy and paste any errors from JavaScript console (Command+Option+J to open):

No errors in console

Please describe the problem:

No way to see history on graph. The bottom bar that usually has a green box indicating which timespan to select has no green selection box - so it's not possible to move.

**Comment by anniesullie** [comment]
I took a look at this. In [chart-slider.updateSelection()](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/elements/chart-slider.html#L161), if there are too many total data points, the green selection is so narrow that it doesn't render. It disappears at 279/53115 data points. So we want to pad the start/end index so that it it is a bigger ratio than that. @jessimb @simonhatch @eakuefner can one of you take a look?

**Comment by simonhatch** [comment]
Should be fixed once a new dashboard is deployed.

**Comment by asvitkine-chromium** [comment]
Thanks for the quick fix!
