### ISSUE TITLE
/group_report shows alerts from all sheriffing rotations

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#3205]
It should only show alerts from the sheriffing rotation of the requested alerts, if known:
  * `bug=` show only alerts from the sheriffing rotation the alerts associated with the bug have.
  * `keys=` show only alerts from the sheriffing rotation the alerts with those keys have.
  * `rev=` there isn't currently a way to narrow this down to a rotation.

It's possible that `bug` or `keys` could have multiple rotations, but I think this is extremely unusual in practice. If desired, we could add a `sheriff=` param to narrow further, but it might be confusing to users.

Cc-ing some folks from different rotations to see if they agree: @natorion @CalebRouleau @perezju @tdresser

**Comment by perezju** [comment]
what is the rationale here? e.g. for `bug=` if, for whatever reason it happened, why would we hide some of the alerts that are associated with the bug?

**Comment by CalebRouleau** [comment]
I'm afraid I'm missing some context here. https://chromeperf.appspot.com/group_report does not show me any useful page. What is the exact link?

**Comment by natorion** [comment]
Context: Annie and I were discussing if we should set up an experimental rotation which is creating a lot of alerts.

Problem: Currently the group_report page shows ALL alerts from ALL rotations for the given revision range. This means that this new, very sensitive rotation would spill over alerts into the work flow of other sheriffs as the group_report page is openend, when one clicks on the "Graph" button on a alert page.

Example page: https://chromeperf.appspot.com/group_report?sid=f9712f839b481e5729ced62134807c47c4c7f3aba10ae4ed9f0b907fc2472d8c

The question now is, should alerts from all rotations shown if one is triaging a specific rotation. IMO the current behavior makes sense, because in the V8 team for example have memory and performance sheriffs. Each has a distinct rotation with alerts page set-up. CLs are creating alerts in both rotations and thus I would expect that they use the same bug for tracking purpose.

Might make more sense to mark certain rotations as "Private", which means their alerts are not spilling into other rotations or into global.

**Comment by CalebRouleau** [comment]
My team rarely, if ever, uses the group report feature. Michael's solution above makes sense to me, but it won't affect my team much either way.

**Comment by perezju** [comment]
I'm still having trouble figuring how the proposed workflow would work.

Say some CL triggers 5 alerts on my "regular" rotation and 150 alerts on the new "experimental" rotation.

> CLs are creating alerts in both rotations and thus I would expect that they use the same bug for tracking purpose.

That means all alerts are assigned to the same bug? So I assume I would see a bug report like:

```
Comment 1 by shreiff@chromium.org, Jan 26

All graphs for this bug:
  https://chromeperf.appspot.com/group_report?bug_id={bug-number}

Original alerts at time of bug-filing:
  https://chromeperf.appspot.com/group_report?keys={long-list-of-keys}

Bot(s) for this bug's original alert(s):

android-nexus5X
android-one
```

Then:
- clicking on those links will show the alerts of which rotation?
- why are all the alerts on the same bug to begin with? why don't we get two bugs in this scenario?
- what does the "Graph" button actually do? (sorry for the dumb question!)

**Comment by natorion** [comment]
I think using one or multiple bugs for multiple rotations is an orthogonal problem and likely not something that needs to resolved because currently the two workflows are supported.

My take on this (please exchange the names with something more suiting):

Let's assume we can define an Alert rotation as "Experimental" by setting the property "int:Status" to "Experimental" (Rotations probably don't have that field yet)
"Experimental" means that these alerts are not spilling over into other rotations automatically.
In order to achieve this we could do the following:

An "Experimental" alert is shown on the associated Alert page (this already works)
An "Experimental" alert is only shown on group_report IF  the GET parameter "origin_rotation" equals the ID of the original rotation. This would mean that the alert is shown in these cases:
- Opened via the "Experimental" rotation because the GET parameter is appended on all the group_report links there
- IF GET parameter bug_id is set (If somebody associated the "Experimental" alerts with a bug we assume it is important enough to show up ... it does not matter if there are multiple bugs or only one)

The alert is not shown in the following cases:
- "Normal" rotations (because no GET parameter at all)
- Other "Experimental rotations (because the GET parameter has the wrong value)

**Comment by benshayden** [comment]
Moved to https://bugs.chromium.org/p/chromium/issues/detail?id=917866
