### ISSUE TITLE
Dashboard feature request: which branches CL has cherry-picked to

### ISSUE THREAD

**Issue by benhenry** [catapult-project/catapult#3206]
Related to #1648 - If one could hover over a point in a graph on the dashboard to see which branches a specific CL has been cherry-picked to. 

We could use 'git log --all --grep "<HASH_OF_CL_ON_MASTER>"' in a local checkout to get that information.

**Comment by anniesullie** [comment]
@dave-2 @simonhatch: Is there a gitiles API that would do something like the command @benhenry suggests?

@benshayden @jessimb @eakuefner

**Comment by benhenry** [comment]
I looked, and confirmed with Aaron, that gitiles and the gerrit REST API don't have commands we could use for this, and that (for now) we need a local checkout.

**Comment by benhenry** [comment]
@agable-chromium FYI

**Comment by anniesullie** [comment]
That's not possible from app engine standard environment AFAIK

**Comment by eakuefner** [comment]
Could we get gerrit-team to consider adding such functionality? I feel like it should be easily possible to do using JGit.

**Comment by benhenry** [comment]
+Aaron Gable <agable@google.com> - let's ask?

**Comment by agable-chromium** [comment]
Sure, all you need to do is modify
https://gerrit.googlesource.com/gitiles/+/master/gitiles-servlet/src/main/java/com/google/gitiles/LogServlet.java
to support additional query parameters (presumably ?all=true and
?grep=<pattern>) and then use JGit's PatternMatchRevFilter to do the actual
filtering and produce the set of commits for the servlet to return.

I'm not going to volunteer to to this work because I don't know the
codebase (or Java) well enough, but it seems like a reasonable feature
request for the gitiles/GoB team.

**Comment by benshayden** [comment]
Archiving.
