### ISSUE TITLE
Dashboard - test-picker issues redundant xhrs.

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3211]
If you look in the logs, you'll see 2 xhr's issued when you go to select a test suite from the /report page. Breakpoint in js confirms 2 are sent.

@chromy

**Comment by chromy** [comment]
hmm, seems to be caused by onDropdownSelect firing twice, I'm not sure why yet

**Comment by chromy** [comment]
Okay, it's caused by the following line:
`selectedItemsChanged(selectedItems, selectedItems.*)`
I used the form:
`fooChanged(foo, foo.*)`
in a few places to trigger on all mutations of the array `foo` and also on setting `foo` but it seems this is actually an anti-pattern `fooChanged(foo.*)` triggers correctly on `set('foo', [...])` but  `fooChanged(foo, foo.*)` triggers twice. I'll prepare a CL.
