### ISSUE TITLE
Big regression not on graph

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3213]
I noticed a big regression on Speedometer which already recovered. Out of curiosity I wanted to find out what happened. I opened Speedometer on Mac12: https://chromeperf.appspot.com/report?sid=d2754c1f24871b1870446d548cdbd4f2e5f4c6eb515d0901216aa0e9cf179148 and I can't select the regressing data points because they are "out of chart".

I suppose this is because there was no alert raised?

![grydoqbmegw](https://cloud.githubusercontent.com/assets/7190422/22927598/80179842-f2b2-11e6-91d3-a6d7c6be7c38.png)

**Comment by anniesullie** [comment]
@simonhatch @benshayden @eakuefner 

The chart range is supposed to be automatically set by the flot library to include all data points. In this case, it clearly is not working correctly.

@benshayden if you're able to take a look at this and other chart bugs, would be interested on your opinion of fixing the current version vs prioritizing moving to a version that uses Kari's work to make the tracing UI shareable. Note that the major new feature we'd want to add to add is the ability to brush the X axis like https://arewefastyet.com/

**Comment by simonhatch** [comment]
I took a quick peek and it looks like the data point is an outlier, in the 4000-5000 range, haven't dug much further than that.

**Comment by simonhatch** [comment]
Poke a bit more. So there's code in chart-container to disregard outliers, anything beyond 5 standard deviations from the mean isn't used to calculate the bounds of the chart so this is WAI.

Increased that to 10 standard deviations as a test, and the point shows up:

<img width="908" alt="screen shot 2017-02-14 at 12 01 21 pm" src="https://cloud.githubusercontent.com/assets/11619067/22939647/5d1b78d6-f2ad-11e6-9d1c-44bc22c80ae3.png">

That's not really a fix though, just testing to see if the point shows up.

**Comment by eakuefner** [comment]
@simonhatch Does it seem like a fix here could be to not consider any point that has an associated anomaly an outlier?

**Comment by simonhatch** [comment]
Hmm don't think that will work, this point has no associated anomaly.

**Comment by eakuefner** [comment]
Thanks for pointing that out; that slipped past me. So, I guess another question is, why do we even do outlier detection at all? Any threshold is vulnerable to this same problem due to a sufficiently large change, and we already support vertical scrubbing to zoom if people aren't satisfied with their amount of zoom.

**Comment by anniesullie** [comment]
I think the problem is that different people would want different things when viewing the same graph. At some point someone must have complained and said they couldn't see the slope of the graph because of the outliers. But @natorion really wants to be able to actually see the outliers, and that is a completely valid request.

I don't think this happens too often, and the charts have y-axis zoom, so how about we remove the outlier detection, and if someone complains we add a checkbox for it?

**Comment by eakuefner** [comment]
+1000

**Comment by simonhatch** [comment]
Tried to do some code archeology to find the original change to see if there was some reasoning, but stopped at commit in 2015 that just mass added a bunch of polymer elements.

Yeah can totally see someone logging a bug if the outlier were large enough, since the rest of the graph might just appear as a flat line. I'd support Annie's suggestion of just killing it for now, and adding a checkbox if it becomes a problem. I'll put up a cl tomorrow to do that.

**Comment by benshayden** [comment]
Here's an alternative UI, feel free to ignore. :-)

[Histogram-span](https://github.com/catapult-project/catapult/blob/master/tracing/tracing/value/ui/histogram_span.html#L389) deals with a similar problem by setting the dataRange max to 15% more than the second or third largest bin if the largest 1 or 2 bins are more than twice as large as the next largest bin. This causes the bar chart to draw an asterisk next to the outlying bars but outside of the axes.
![](http://i.imgur.com/RqpYLwI.png)

Extending the concept to a line chart could involve drawing the point's dot just above the "top" of the chart (or just below the x-axis) so that it's still accessible but clearly outside the normal range.

**Comment by simonhatch** [comment]
Like that option, can maybe try it if someone complains. 'll leave a comment and we can revisit.
