### ISSUE TITLE
Why are some alerts grouped together and others not?

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3219]
Example: https://chromeperf.appspot.com/group_report?rev=39407

Some alerts are grouped, others are not. Why?

**Comment by anniesullie** [comment]
The grouping code is pretty basic, but a cursory glance makes me think at least some of these alerts should have been grouped, because they have the same benchmark and overlapping revision range: https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/models/alert_group.py#L228

I think the best way to dig in would be to write a unit test which takes the alerts in the list and debug why it isn't grouping them. @simonhatch @eakuefner ?

**Comment by simonhatch** [comment]
I modified this code recently so I can take a look.

**Comment by simonhatch** [comment]
Poked at this a bit, wasn't able to reproduce a simple test case where they didn't group so far. Did notice that there seems to be 2 different code paths to creating vs updating the groups, seems like it'd be a good idea to clean these up and have a single code path.

The ungrouped alerts "Octane2.1-Ignition/Richards" were marked ignore and both have "V8 Ignition Perf Sheriff" while the grouped ones are "V8 Perf Sheriff", is it possible that they were just triaged separately?

**Comment by natorion** [comment]
For sure. But why should I care on the group report page if the alert is coming from a different rotation?

**Comment by natorion** [comment]
And thanks for investigating. Highly appreciated!

**Comment by simonhatch** [comment]
Just curious, is this from a link from the alerts page or something? I'm unfamiliar with how to actually get to this page besides creating the url myself.

**Comment by natorion** [comment]
I was investigating the perf impact of a CL
