### ISSUE TITLE
Alert on change in moving average

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3221]
It would be great to somehow alert if the moving average changes over the course of 100 revisions or something. I suppose that is somehow model-able via the current anomaly detection. My question is, how would a common performance sheriff approach this?

**Comment by tdresser** [comment]
As a perf sheriff, I would shake my head and walk away...

I don't think we can deal with this kind of "death by a thousand paper cuts" situation via perf sheriffing.
I think the right approach here is:
- Identify what kinds of things are causing gradual regressions over time, by performing deep performance investigations on specific metrics and benchmarks.
- Improve our infrastructure to prevent these sorts of things from landing.

My intuition is that there are some patterns (inlining too much code, using inefficient STL data structures, etc) which commonly contribute to these slow increases. I don't have any justification for this intuition though. I think the right first step would be to start collecting canonical examples of where this happens, to try to identify trends.

**Comment by natorion** [comment]
Fair point and it would be interesting to know if this is more common Chromium-wide.

The last time I can remember this happened in V8 was when we added ES6 support which resulted in a continuous regression in pageload performance. This obviously makes sense because we need to do a more sophisticated parsing.

**Comment by anniesullie** [comment]
I think @tdresser's comment is pretty representative of what chromium perf sheriffs would say. I think the two most common cases where we have slow and gradual increases over time are:

 * binary sizes
 * memory usage

These are both very tough because pretty much every committer can affect these a tiny bit, and for any one CL it's hard to evaluate the tradeoff in bytes of kilobytes. For these metrics we've started filing a per-milestone report, which is currently manually written. @jessimb is working on automating it, and @benhenry is taking over the writing of the manual report from @perezju and @primiano.

**Comment by primiano** [comment]
Agree with the comments above. Alerts that say "the moving average went up in this range, but we have no way to tell where" are completely unactionable.
We can't revert 100 CLs because a slow regression of x% of {memory,binary, any metric} creeped in.
This sort of analysis can be done already by zooming out and observing the trend of a metric over time. I don't think we need the complexity of an actual alert system for this. We are already aware of these problems (at least for memory and binary, maybe you are thinking to something more specific here?), they are just very hard to act on. 

IMHO The only action for these problem there is to call for larger scoped project of the form "hey, our binary is slowly creeping in. we need to kick off some larger project, look into usage patterns, maybe ban some uses of the STL etc" (I'm just making these up, don't take these examples seriously). The problem is that today, for these kinds of issues, we lack the action part (not enough people working on large scope performance projects) not the alerting part.

**Comment by natorion** [comment]
Fair enough and thanks for thinking about it. Concerns make absolutely sense.
