### ISSUE TITLE
Dashboard - Clarify difference when comparing metrics

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3249]
Breaking up #3243 into individual issues.

Behavior of a chart's legend

When comparing two metrics, the difference in the configuration is important, not the name of the actual metric being charted. It would be informative if the differentiator is used instead. See #3231 (comment) for a detailed suggestion on this.

@natorion

**Comment by simonhatch** [comment]
How's this: https://dev-simonhatch-4a916970-dot-chromeperf.appspot.com/report?sid=645703c6ca2919f7e822476e5a9d8789efc254eb6d554cfa24ddd29101cf83e3

**Comment by natorion** [comment]
Showing everything starting from the level of difference feels better. You are right. I tried it out with a deeper nesting level:

Graphs compared:
- internal.client.v8/x64/v8/RuntimeStats/Group-Parse-Total/duration/Total/Default
- internal.client.v8/x64/v8/RuntimeStats/Group-Compile-Total/duration/Total/Default
URL: https://dev-simonhatch-4a916970-dot-chromeperf.appspot.com/report?sid=a8f13d1b310ed6913a2ee140d8d79989af9ab623be44de0b05cbed346fcd5ae9
![rcs](https://cloud.githubusercontent.com/assets/7190422/23451314/aef2c7be-fe5f-11e6-803d-77e7deb58f6d.png)

I would have expected that "Group-Compile-Total/duration/Total/Default" and "Group-Parse-Total/duration/Total/Default" is shown instead of "Default".

Unimportant nit: How about making the string diff of the first diff level bold? Would make it easy to identify "-turbo" in your speedometer example.

**Comment by simonhatch** [comment]
Oops I had hardcoded the demo to stop at the test_suite, here's an updated version:

Demo: https://dev-simonhatch-c20b845c-dot-chromeperf.appspot.com/report?sid=a8f13d1b310ed6913a2ee140d8d79989af9ab623be44de0b05cbed346fcd5ae9

**Comment by natorion** [comment]
Awesome!
