### ISSUE TITLE
Dashboard - Allow "pinning" for commits

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3255]
Breaking up #3243 into individual issues.

Keep displaying information while hovering over a commit despite another commit is pinned

Let's assume I want to investigate an alert. I am pinning that alert to the information pane. Now, I want to see the value or "Chromium Git Commit Range" of one commit before the alert. Even to get to the value I would need to click the commit before the alert thus changing the pinned commit to the other one. Theoretically I could also use the delta tool of the chart to show the difference for the value, but that does not work for the commit range.
I think there are two issues at work here: 1.) I want to compare two commits, so I would need to pin two commits. Other solutions like simply adding the same chart twice is hard/cumbersome when one starts from the Alerts page. 2.) Always display some information while hovering over any commit (e.g. value + variance)

@natorion

**Comment by benshayden** [comment]
Dialog-container has position:absolute, so displaying multiple of them poses a layout problem.

Currently, the dialog-container is always positioned so that its top left corner is at the point of interest on the chart. This means that it is never positioned outside the left side of the viewport, and it rarely overlaps the right side of the viewport because the chart-legend provides a buffer between the chart and the right edge of the viewport, so the dialog-container can sit on top of the chart-legend.

If there are two dialog-containers placed side-by-side, then the left one could fall off the left edge of the viewport and be inaccessible.

In [this old design doc for histograms on the dashboard](https://docs.google.com/document/d/1F7A0WRVC-aYHSz_rDnEBzDpjEDJl0_1Kjb9IKrpAhok/edit#heading=h.rlt028crrwc1), we discussed adding a table below each chart, with columns for each selected point on the chart. That would seem to prevent this layout problem, and make room to display more diagnostic information.

@simonhatch Should I move forward with moving the dialog-container towards the table?

**Comment by simonhatch** [comment]
Believe one of the use cases for histograms will be a deep comparison between points, so it sounds like we'll want something like what's described in the doc.

Seems like if we go that route though, it's basically forcing us to design/implement a good chunk of that UI feature now. I get a rough idea from the doc as to how it might look but that's for full histograms? Some questions around things like how you enable comparison, where the bisect/etc buttons go. Probably need to spin that doc off into a small thing with just that feature. Also guess it'd depend on how long this would take and how much would be reused later.

If we decide to punt and wait, this request is pretty small, basically just showing mean/variance. If you were to add some sort of "pin" button that stickied a small popup box with just that info + implemented #3254, that might do the trick too and we could wait for the full comparison work in Q3?

@anniesullie @eakuefner wdyt?

**Comment by benshayden** [comment]
Archiving. V2SPA will fix this.
