### ISSUE TITLE
Dashboard - Investigate using AppStats to get an overall sense of costs.

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3363]
https://cloud.google.com/appengine/docs/standard/python/tools/appstats

Seems like it might be able to, not totally sure?

@eakuefner @anniesullie

**Comment by simonhatch** [comment]
So I enabled this globally and its pretty amazing the breakdown it gives you. Demo here:

https://dev-simonhatch-1ebe3684-dot-chromeperf.appspot.com/_ah/stats/

I'm not clear what the impact of running this all the time is though, if there's low impact I think this is good data to be able to access whenever but we could also just make it a deployment option.

**Comment by simonhatch** [comment]
Still not clear if there's much impact running this all the time, but at least have some stats. AppStats claims that somewhere in the realm of 97% of time/resources spent via /add_point_queue so we can try optimizing in there a bit as a first step.

**Comment by anniesullie** [comment]
Thanks for looking into this! We had a problem updating the dashboard in September, I think, when @dave-2 added the config for pinpoint, because the dashboard machines were using a default configuration and the pinpoint configs overrode them and lowered the machine specs. We started getting OOM errors and had to explicitly use the highest machine specs, which is what we had been using by default. (Dave, please correct me if I misremembered).

So based on that I think we currently need the memory the high-end machines have, although @eakuefner's more [recent change](https://codereview.chromium.org/2615053003/diff/1/dashboard/dashboard/add_point.py) to do a request.get() on the JSON twice may have helped.

Is there any way to monitor memory usage of `add_point_queue`?

**Comment by simonhatch** [comment]
I'll see if I can find out, but AppStats doesn't provide memory data.

Also I think if we prioritize #3362 we get much more powerful hardware for a similar cost, so more breathing room (especially for the upcoming giant histogramset files).

**Comment by anniesullie** [comment]
I didn't realize the managed VMs were cheaper, awesome!

**Comment by simonhatch** [comment]
Certainly seems like you pay closer to GCE pricing, so it seems like we should check that out first.

**Comment by simonhatch** [comment]
Btw saw there's an "overhead" column on the stats page and it looks roughly like the overhead is a couple % of total time per request. A lot of the /add_point_queue calls I see a couple hundred ms recorded as overhead for AppStats.
