### ISSUE TITLE
Improve report-page's handling of promise rejection

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#3391]
In https://codereview.chromium.org/2716683004 we leave the error handling in report-page a little coarse. We should figure out the best thing to do and modify the reject handler not to just do a console.log.

**Comment by benshayden** [comment]
Looking for clarification on target behavior.

It would be very convenient to have some explicit reminder to sign in when requesting internal-only data, however, I was under the impression that it was considered a security feature to deliberately not differentiate between invalid requests and signed-out requests for internal-only data.

Should the dashboard tell signed-out users to sign-in specifically when requesting internal-only data?
Or when any request fails while not signed-in?
The former would require the backend to communicate (leak) internal-only-ness to the frontend, whereas the latter can be handled entirely on the frontend, but would only be able to say something vague like "You *may* need to sign in, or the requested data may not exist."
Or is there another alternative behavior?

@simonhatch

**Comment by simonhatch** [comment]
I believe it shows the message that some data is only available when you're signed in, in both cases (either it's internal data or it just doesn't exist).

Right now I *think* we do the latter, any failed request (at least to /graph_json I think) turns into a "failed to fetch data, some data only availble when signed in".

@anniesullie To doublecheck.

**Comment by anniesullie** [comment]
That's correct. We try not to allow you to create requests to guess which timeseries might exist only for logged in users.

**Comment by benshayden** [comment]
In [this demo](https://dev-benjhayden-0aa53db3-dot-chromeperf.appspot.com/report?sid=b22d91217ee3ed5a934cb313faeba75904e26dec76f7845df109a98f7175ec05), when /list_tests fails, report-page displays a toast containing "Failed to load some graphs. Do you need to sign in?".

![](http://i.imgur.com/v0OhmRn.png)

- Is that a good place to display the error message, or is it maybe too easy to miss? It doesn't look like I can display the error message about /list_tests in the same place as the error message about /graph_json (in chart-container).
- Thoughts on the error message text?

Thanks!

**Comment by simonhatch** [comment]
So this is slightly different from what's there now, in that public graphs will still show and missing/internal graphs chart-containers will post an big red ugly warning. The only bug I can recall asking about the warnings was #2764 which just asked to get a big ugly error message up.

I think if we went with this, I'd probably want to make the warning somewhere more front and center, since I think people are more used to seeing big red letters right in the middle of the screen.

Also somewhat minor point but related to the behaviour of this. From the CL it looks like test paths that don't exist are filtered out. I can imagine since we're busy migrating tests right now, old report links will become invalid. The old behaviour would have been to have a red warning that the data is missing or needs a login. What will this do?

Other note, I notice this actually fixes the issue of those empty (!) entries on the chart-container.

**Comment by benshayden** [comment]
![](http://i.imgur.com/8ZRoJG2.png)

**Comment by anniesullie** [comment]
lgtm
