### ISSUE TITLE
Dashboard cannot handle duplicate revision range

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#3408]
From https://bugs.chromium.org/p/chromium/issues/detail?id=694537#c16:

If one run has the same V8 range as the previous one the range link looks like: 

https://chromium.googlesource.com/v8/v8/+log/f7036b132f6bcce9312b52a9ba386ae487280713..f7036b132f6bcce9312b52a9ba386ae487280713

As a result no commits are shown. It should only use the link https://chromium.googlesource.com/v8/v8/+/f7036b132f6bcce9312b52a9ba386ae487280713 instead (+ instead of +log and only one commit).

@natorion

**Comment by anniesullie** [comment]
This is actually a much narrower bug: If the v8 commit pos wasn't reported in the previous revision, and it's reported in the next, it doesn't display correctly. Since we're now reporting v8 commit pos in every revision it was a one-time blip. Going to close since there isn't really a reference to use in this case.

But here's a page showing single v8 revisions displaying correctly: https://chromeperf.appspot.com/report?sid=aac0dd8b335248f537b95064ae5ee96d24d03480392f33be8586e16dff251fbf
