### ISSUE TITLE
Allow async/await

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3417]
It's been [in Chrome since 55](https://www.chromestatus.com/feature/5643236399906816). It looks awesome! See histogram_set_table_test.html in [this CL](https://codereview.chromium.org/2747453003) for example.
This will require adding `"parserOptions": { "ecmaVersion": 2017, },` to .eslintrc .

@zeptonaut @eakuefner WDYT?

**Comment by eakuefner** [comment]
+1000

To say a little more about why we _really_ want this, it also allows you to write "async function" inside of a test case, and this will just work, since the harness already allows sync functions that return promises. We're writing increasingly promise-oriented code, so I think async/await are going to be key to maintaining our velocity there.

Since we're allowing other ES2017 features that have landed in stable, I think it should be fine to allow it.

**Comment by zeptonaut** [comment]
sgtm. Looks pretty awesome!

**Comment by eakuefner** [comment]
@benshayden I think we might not have an entry for async/await in the style guide yet, care to add one and mark it approved?

**Comment by eakuefner** [comment]
This is done, thanks Ben!
