### ISSUE TITLE
The blue "Trace" button in perf dashboard doesn't work for Timeline based benchmarks

### ISSUE THREAD

**Issue by wangxianzhu** [catapult-project/catapult#3450]
/cc @simonhatch @zeptonaut 
1. Open https://chromeperf.appspot.com/group_report?bug_id=704182
2. Click the black "!" in the graph
3. Click "Trace"

Actual: after some time, the trace job finished: https://codereview.chromium.org/2775363002/ which seems successful. However, there are failure messages inside: https://luci-logdog.appspot.com/v/?s=chrome%2Fbb%2Ftryserver.chromium.perf%2Fmac_retina_perf_bisect%2F2012%2F%2B%2Frecipes%2Fsteps%2FRunning_WITH_patch%2F0%2Fsteps%2FPerformance_Test__5b49d1384ce8d1a8594bdb49f9f392da784b43bf__1_of_1%2F0%2Fstdout

Traceback (most recent call last):
  RunBenchmark at /b/c/b/mac_retina_perf_bisect/src/third_party/catapult/telemetry/telemetry/internal/story_runner.py:364
    benchmark.ShouldTearDownStateAfterEachStorySetRun())
  Run at /b/c/b/mac_retina_perf_bisect/src/third_party/catapult/telemetry/telemetry/internal/story_runner.py:231
    test, finder_options.Copy(), story_set)
  traced_function at /b/c/b/mac_retina_perf_bisect/src/third_party/catapult/common/py_trace_event/py_trace_event/trace_event_impl/decorators.py:52
    return func(*args, **kwargs)
  __init__ at /b/c/b/mac_retina_perf_bisect/src/third_party/catapult/telemetry/telemetry/page/shared_page_state.py:52
    'This is a Timeline Based Measurement benchmark. You cannot run it '
AssertionError: This is a Timeline Based Measurement benchmark. You cannot run it with trace profiler enabled. If you need trace data, tracing is always enabled in Timeline Based Measurement benchmarks and you can get the trace data by adding --output-format=json.

**Comment by zeptonaut** [comment]
I also find this very confusing: especially the part about "this is a timeline based measurement benchmark: you cannot run it with trace profiler enabled". Isn't that the _point_ of timeline based measurements?

**Comment by tdresser** [comment]
When I do this locally, I run with:

`tools/perf/run_benchmark --output-format=json --output-dir=/tmp/traces`

And then in timeline_based_measurement.py, Options::__init__, I set
overhead_level = DEBUG_OVERHEAD_LEVEL

Could we do something similar here?

**Comment by simonhatch** [comment]
It's been a couple years since I did much with the trace button, info may be out of date. At the time, I introduced something in telemetry benchmark.SetupBenchmarkDefaultTraceRerunOptions that allowed you to extend the tracing categories with additional ones in the event of a trace request from the dashboard. These were uploaded as trace_rerun_options via chartjson, and in the absence of those rerun options the dashboard defaults to --profiler=trace.

**Comment by anniesullie** [comment]
@nedn

**Comment by nedn** [comment]
The whole implementation of this should be overhauled. This could be a Q2 task for benchmarking team, but I need to have a better sense of priority. 
How often do folks use this feature to debug, or do they just do local debugging?

**Comment by anniesullie** [comment]
@wangxianzhu: how much of this is just a UI issue (there is a trace link and a trace button, would the trace link have been good enough?)

If you need the trace button to do something different than the link, are you expecting roughly what @tdresser suggests above?

**Comment by anniesullie** [comment]
For tbm2 benchmarks, we'll fix it like this: every TBM Benchmark has a CreateTimelineBasedMeasurementOptions method. We'll change it so that they also have CreateDebugTimelineBasedMeasurementOptions. When the benchmark is run with "--debug-trace", the benchmark will use the CreateDebugTimelineBasedMeasurementOptions instead. The dashboard will pass in that flag.

**Comment by anniesullie** [comment]
The more I see requests for this, the more I think that we'll want to allow the user to specify categories. Like in https://bugs.chromium.org/p/chromium/issues/detail?id=736279#c9, how would we have predicted the use case of net tracing to debug certificate validation tasks? Similarly, for the recent regressions in translateranker, the team would want to add tracing for that, in their own category. @nedn why not allow the trace categories to be user specified?

**Comment by tdresser** [comment]
+1!

**Comment by zeptonaut** [comment]
I totally agree that it should be possible to specify the categories right from there. From where I stand, there are two difficulties with this:

1. The way that we determine what the possible trace categories even are. I'm not completely clear on this, but I think that it involves some communication with the Chrome instance that's not possible from the perf dashboard. I think the implementation of how we discover trace categories might need to change. One way that I could see to do this (probably not the best) is to log as metadata each of the trace category options when you run a trace. When you click "Trace" on a specific data point, it then looks at the existing trace for that data point, ferrets out the trace categories, and presents them to the user in the record trace dialog.
2. The implementation of the record dialog really sucks, and would likely need to be significantly revamped in order to make this possible.

**Comment by nedn** [comment]
If you exposed those APIs, benchmark designer can allows user to specify categories through flags if they want by doing this.

```

class FooBenchmark(..):

def AddBenchmarkCommandLineArgs(cls, parser):
   parser.add_options('--chrome-tracing-categories-as-string', type='str')

def CreateDebugTimelineBasedMeasurementOptions(cls, options):
   tm_opt = TimelineBasedmeasurement.Options()
   if options.chrome_tracing_categories_as_string:
      tbm_opt.chrome_tracing=True
      tbm_opt.chrome_category_filter.SetFilterString(options.chrome_tracing_categories_as_string)
  else:
     tbm_opt.chrome_tracing = True
     tbm_opt.chrome_category_filter.SetFilterString('cc, toplevel, blink,')
     tbm_opt.enable_battor = True
     tbm_opt.enable_systrace = True
  return tm_opt

```

I would prefer pushing the burden of the tracing debug flags down to individual benchmark harness instead of at the core benchmark class because:
1) It's unclear how different benchmark harnesses would want to enable which kind of tracing. Recall that we don't just support Chrome tracing but other tracing systems like battors, systrace,.. We don't have a unified json string config for all different tracing systems to support a general flag.
2) Dashboard's trace button support Yes/No specification. There is no way to put arbitrary strings there yet.

**Comment by anniesullie** [comment]
It's pretty easy on the dashboard side just to allow the user to add a list of strings, and maybe hardcode some options we know won't change.

I'm not sure how the dashboard side can allow the user to set trace categories if it's done on a per-benchmark basis?

**Comment by nedn** [comment]
If we can add UI to the perf dashboard, we can go the route of providing flags to set different tracing categories. My point is we either do:
1) We keep the dashboard UI simple (Yes/No button), and we don't support setting traces through command line in general (to avoid flag settings conflict).
Or
2) We make sure the dashboard UI can support tracing configs for each tracing types. At this point, all we need is probably few flags for each type of traces:
"--chrome-tracing-categories"
"--systrace-tracing-categories"
"--battor-trace"
...

Though you may want to make sure that all different form of tracing categories are properly supported. IIRC, the complete form of Chrome tracing config is a json.

**Comment by nedn** [comment]
I think about specifying chrome categories through flag this a bit more and leaning toward support s.t like `"--extra-chrome-categories"`. 

We probably only want users to *append*, not *overwrite* the original tracing configs. The reason is it might be confusing for users that benchmark results may not have all the original metrics the benchmark intended to capture if they miss some categories when specify manually.

With this, we probably just start with adding `"--extra-chrome-categories"` & `"--extra-systrace-categories"` flags.

With that, I propose the implementation as follows:
1) Rename `Benchmark.CreateTimelineBasedMeasurementOptions` to `Benchmark.CreateBaseTimelineBasedMeasurementOptions`
2) Add `Benchmark._GetTimelineBasedMeasurementOptions` (private so that it will only be used by core Telemetry code) which is s.t like:
```
def _GetActualTimelineBasedMeasurementOptions(self, options):
   tbm_opt = self.CreateTimelineBasedMeasurementOptions()
   if options.extra_chrome_categories:
       assert tbm_opt.enable_chrome_trace, 'This benchmark does not support chrome trace'
       tbm_opt.chrome_category_filter.AddFilterString(options.extra_chrome_categories)
  ...
  return tbm_opt
```
We then update the TBM client to use the `_GetActualTimelineBasedMeasurementOptions`

**Comment by zeptonaut** [comment]
One weird interaction I foresee with this is (I think) that when you specify an empty filter string (""), it uses the default categories. However, when you append something to that filter string ("sched,toplevel"), it records only those categories, so by appending things to the filter string, you can actually end up tracing fewer categories than you started with. Very confusing.

(This was at least the way that it worked the last time that I looked at it. @wangzhen127 is the expert on this I think.)

**Comment by anniesullie** [comment]
WIP CL for the telemetry side (lots of questions!): https://codereview.chromium.org/2965383002/

**Comment by nedn** [comment]
A user encounter the need of using this today: https://bugs.chromium.org/p/chromium/issues/detail?id=749357#c5

**Comment by anniesullie** [comment]
I've added `--extra-chrome-categories` and `--extra-atrace-categories` flags to telemetry. I'm working on supporting them in `blink_perf` benchmark, but apart from that the main thing to do is dashboard integration.

At a high level on the dashboard, I want to have two options:
* A reasonable default set of trace categories
* An option to type your own filter strings.

Does anyone have opinions on what default filter strings for chrome and atrace would be?

**Comment by anniesullie** [comment]
Fix is now live.
