### ISSUE TITLE
Move UserModelBuilder validation warnings to an on-demand method on the UserModel.

### ISSUE THREAD

**Issue by deepanjanroy** [catapult-project/catapult#3452]
Opening [this trace](https://github.com/catapult-project/catapult/files/873997/trace_youtube.json.gz) gives me the following warning and user expectations are not created:

![image](https://cloud.githubusercontent.com/assets/3505637/24380930/be710072-131b-11e7-8a81-47e818f8b664.png)

The trace was taken during a youtube video playback, which may be relevant to the issue.

**Comment by deepanjanroy** [comment]
After applying https://codereview.chromium.org/2772253003/ I now get "Please file a bug with this trace: double-handled event: MouseLeave @ 6509.617000102997".

**Comment by benshayden** [comment]
Better than a ReferenceError :-)

I added that validation code while I was actively working on the UMB, but UMB is now in maintenance-plus mode: I'll definitely keep it working (fixing ReferenceErrors and the like), and I'll try to fix these logic errors when they're impacting benchmarks/metrics. If there are too many bugs filed due to this validation code that aren't actually impacting benchmarks/metrics, then I'll probably disable it, but I want to ensure that metrics authors and benchmark users don't think that UEs are unsupported. Maybe I should add "If a problem with the UEs is impacting benchmark/metric work, then file a bug..."? Or just disable validate()? Or put it behind a method in UserModel to call from the console?

**Comment by deepanjanroy** [comment]
That message was scary enough to make me think the user model is likely corrupted and if I metrics depend on expectations they won't give meaningful results anymore. If you think most of the time the user model is totally fine after double handing like this, and we should only file a bug when metrics start looking funny, then moving it to a console.warning sounds like a better idea.

**Comment by benshayden** [comment]
We actually just disabled console, so I'll move it to a method on UserModel.
Thanks!
