### ISSUE TITLE
Create chrome_thread_helper

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#3458]
As discussed offline, we want to introduce chrome_thread_helper as a module for dealing with tasks like "given this thread, give me all of the events of particular interest to me", so that we can have brighter, clearer lines around what the various helpers do. In this world, the thread helper is responsible for these sorts of event-level questions, and the process helpers (renderer and browser) will help you locate particular threads of interest.

The first step here is to create chrome_thread_helper and move `getNetworkEventsInRange` out of `thread.html`. Max has volunteered to do this first step since he introduced this method.

@zeptonaut @benshayden

**Comment by zeptonaut** [comment]
A few suggestions about improvements to `getNetworkEventsInRange`:

Right now you're checking for category parts with:

```js
if (slice.category === 'net' ||
    slice.category === 'disabled-by-default-netlog' ||
    ...) {
...
}
```

However, what if there are multiple categories on one of these events?

e.g. 
```js
{ name: 'myNetEvent', cat: 'toplevel,net', ... }
```

your boolean is going to return false. It's for this reason that we usually use `tr.b.getCategoryParts` when checking whether an event has a particular category: this helper function returns the categories as an array, which you can then use like:

```js
const categories = tr.b.getCategoryParts(slice.category)
if (categories.includes('net') || categories.includes('disabled-by-default-netlog') || ...) {
  ...
}
```

One last suggestion: `getNetworkEvents()` feels something that probably belongs on a `ChromeThreadHelper`, but `getNetworkEventsInRange()` feels like it's just a `getNetworkEvents()` function combined with one of many possible predicates that a caller might want. What if, instead of `getNetworkEventsInRange()`, someone instead wants `getNetworkEventsWithTitle()`: are we going to create a separate function for that, too? My suggestion is to try and create a helper function for the domain-specific part (`getNetworkEvents()`), but leave the filtering for the caller (`helper.getNetworkEvents().filter(e => range.intersectsExplicitRangeInclusive(e.start, e.end))`). Then, if someone later wants to filter by title, they can use the same function (`helper.getNetworkEvents().filter(e => e.title === 'FetchStart')`.

**Comment by eakuefner** [comment]
@zeptonaut Just to bring you up-to-date, as far as rephrasing it and using the helper, I had written this comment https://codereview.chromium.org/2769513002/diff/180001/tracing/tracing/model/thread.html#newcode308 where I proposed that @maxlgu should write it as a set intersection (aside, we should consider adding tr.b.setIntersection to iteration_helpers, maybe).

But +1 to filtering in the caller instead, that's a great idea.

**Comment by maxlgu** [comment]
I talked with Ethan offline, we decided to move getAllNetworkEvents() to loading_metric from chrome_renderer_helper because we want each level of helper to be responsible for its own domain without concerning about the lower level domains, and let callers to coordinate helpers of different level according to their needs. In our case, in order to get all the network events, loading_metric should call chrome_renderer_helper to get all the threads and call chrome_thread_helper to get all the network events.
