### ISSUE TITLE
Wrong time units in alerts page (?)

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#3513]
A recent [group of alerts](https://chromeperf.appspot.com/group_report?bug_id=714351) for a regression on benchmark duration is showing:

![zni14a8sxfw](https://cloud.githubusercontent.com/assets/16922344/25332215/8b57798c-28dd-11e7-9c91-5b37671a007a.png)

Which I read as, e.g. 15.718 **microseconds**; looking at the graph below, however, this appear to be **minutes**. Could we format these instead as, say, "15.7 mins"?

**Comment by chromy** [comment]
I think the problem is around this [line](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/elements/alerts-table.html#L561) which ends up eliding the conversion factor when converting from legacy to current units.

A CL like https://codereview.chromium.org/2834403002 fixes some of the problem but means that minutes are formatted like this instead:

<img width="1196" alt="screen shot 2017-04-24 at 12 39 07 pm" src="https://cloud.githubusercontent.com/assets/351085/25335497/32265bf4-28eb-11e7-9229-cf0fba6d0c41.png">

Which is also not ideal.

**Comment by anniesullie** [comment]
Wait, in that screenshot we see 1 billion milliseconds = 11 days. Is that the right value? I think landing the CL is a good first step if it shows the correct time in ms when minutes or hours might be easier to read.

@simonhatch: I know you were looking at ramping up on some of the trace-viewer side UI code. Would you be interested in following up after @chromy's CL lands and seeing if we can get a better unit for the time elapsed? (For example, show 12 million ms as 3.33 hours)
