### ISSUE TITLE
Pinpoint - Bisect with pinned DEPS or patch

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3516]
From @benhenry on crbug.com/714289:

Issue 711282 brought up a case where there is a regression somewhere in the CL range within a roll that we cannot bisect on because another CL in that roll range causes compiler failure or crash. In the issue listed, the subsequent Clank roll contained a fix to the compile issue. I would be nice to be able to kick off a bisect between those two rolls with the patch in place so we wouldn't be left with 0 options except manual bisect, here.

**Comment by dave-2** [comment]
While Pinpoint does technically support this in the Change abstraction, I think we may want special support for pinning to specific revision(s) or patch(es), because the FindIsolate quest uses the first Commit as the base_commit, and UI is designed to show only the most specific commit.

**Comment by dave-2** [comment]
We had our first instance in which a bunch of jobs failed because of a change in Chrome. We're thinking of implementing a way to look up a range where we should automatically apply the revert patch. For many jobs, the failure covers only a part of the range, so it's less useful to apply the patch to the entire job.

https://pinpoint-dot-chromeperf.appspot.com/job/15f24a8f840000

**Comment by dave-2** [comment]
There's a few places we can add this, from most general to most specific:
* `JobState.AddChange()`. I think this is the "most correct" place to add it, but would require some work - the UI shows the most specific commit / patch, so we may need to modify the Change format to distinguish this patch from the try job patch. We would also need to modify `Change.Midpoint()` to handle the patches differently. ❌
* `JobState.AddAttempt()`. We can do the conversion when we're creating the Attempts, since each Attempt holds a reference to a Change. This does means that we're duplicating the lookup work and creating a new Change object for each Attempt, but it is super easy to add it here. ✅
* `FindIsolate` or `_FindIsolateExecution`. We can do the conversion when looking up the build. Unfortunately, this would make the logic specific to this set of Quests, and we want it to be a more general Pinpoint feature. ❌

**Comment by dave-2** [comment]
For bugs like #4323, we're going to want both abilities.
* Ability to pass a Change into a Job, and run the entire Job with that Change pinned.
* Ability to specify fix ranges, and automatically apply fix patches to the range.

Since the title of this bug is the first one, I'm going to split the second one into a new bug.
