### ISSUE TITLE
Graphs y-axis tick-mark labels are obscured by y-axis axis title

### ISSUE THREAD

**Issue by CalebRouleau** [catapult-project/catapult#3519]
![yaxis](https://cloud.githubusercontent.com/assets/1326100/25358972/37a3115a-28f8-11e7-84ba-d13af8571cae.PNG)

For these graphs: https://chromeperf.appspot.com/group_report?bug_id=710017 I keep thinking that the regression is from 2,000,000 to 600,000 because the first "1" is obscured. Not a huge issue, but a nice polish to fix this. Maybe a good first bug for someone.

**Comment by anniesullie** [comment]
@simonhatch @benshayden This might be an example where the solution should be simple, but flot makes it tough. Would be interested to hear whether there's a way to make this simple fix in flot.

**Comment by simonhatch** [comment]
Maybe we can move that to somewhere else, like below the test_path? Either that or you'd have to shrink the text so that they don't overlap, which end up being unreadable.

There's also a legend http://www.flotcharts.org/flot/examples/interacting/index.html that can be displayed, but unfortunately seems to prevent you from clicking on points behind it :(

**Comment by benshayden** [comment]
Flot supports an option `yaxis: {labelWidth: number}`. chart-container can measure the size of the tick label text and set that option. Tracing's d3-based charts already do this. IIRC, the trace-viewer timeline chart track doesn't support axis labels at all yet.

**Comment by benshayden** [comment]
Should I keep this open until a new version of the dashboard is deployed with the fix?

**Comment by anniesullie** [comment]
We usually do, but you can deploy-then-close if you want.
