### ISSUE TITLE
Telemetry documentation: unclear how to run unit tests

### ISSUE THREAD

**Issue by CalebRouleau** [catapult-project/catapult#3540]
Following directions at https://sites.google.com/a/chromium.org/dev/developers/telemetry/telemetry-unittests, I attempted to run the tests in catapult/telemetry/telemetry/internal/actions/play_unittests.py

>  bin/run_tests PlayActionTest.testPlayWithNoSelector --browser=stable 
> [...]
> WARNING:root:Dependency determine_if_keychain_is_locked not configured for platform linux_x86_64. Skipping prefetch.
> No tests to run.
> **Non zero exit code**
> If you don't see any error stack, this could have been a native crash. Consider installing faulthandler (https://faulthandler.readthedocs.io/) for more useful error message

How is this done? I'm happy to update the documentation if someone can give me a command that works. I started rabbit-holing when I was reading the code.

Thanks!

**Comment by CalebRouleau** [comment]
Whoops, didn't mean to submit yet. Adding detail now.

**Comment by CalebRouleau** [comment]
This is blocking crbug/713394, which is blocking crbug/710253, which is blocking crbug/713345 (Reducing the cycle time of perf waterfall from 10 hours to 1 hour)

@martiniss any ideas for this?

**Comment by nedn** [comment]
This is because the test is disabled on Linux, I think: "https://cs.chromium.org/chromium/src/third_party/catapult/telemetry/telemetry/internal/actions/play_unittest.py?rcl=d9a69250dacb324c594020c53e62097a6bb37569&l=23"

I can run the test with `./bin/run_tests --browser=system  PlayActionTest.testPlayWithNoSelector --also-run-disabled-tests`.

Sorry for the confusion, I will add something to logging to make it clearer.

**Comment by nedn** [comment]
@dpranke , this is because Typ bails out too early for the cases of all the tests to be run are skipped. I sent out https://codereview.chromium.org/2867763002/

**Comment by CalebRouleau** [comment]
Seems this is fixed.
