### ISSUE TITLE
Disabled stories should not require opening the browser

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#3549]
Currently, on system health benchmarks, the browser is launched for all stories, even if it turns out that the story itself is disabled. This produces the strange situation where even disabled stories may fail.

For example `long_running:tools:gmail-foreground` is failing on [android nexus-5x](https://luci-milo.appspot.com/buildbot/chromium.perf/Android%20Nexus5X%20Perf/24) despite the fact of [being disabled](https://cs.chromium.org/chromium/src/tools/perf/page_sets/system_health/long_running_stories.py?rcl=faf8e1ebbc65063a01ada0f0c5ac8981076210cb&l=86).

@randalnephew, @nedn Something to consider when designing the new story disabling mechanism.

**Comment by nedn** [comment]
This is because the disabling story mechanism of system_health story is implemented on top of "CanRunOnBrowser" (h@ckz :P). For this CanRunOnBrowser disabling, you need to poke at the browser to know whether the test can keep continue.

Once we move the system health disabling to @randalnephew 's new disabling system, this will no longer be a problem.
