### ISSUE TITLE
Perf Dashboard: can't select range of alerts

### ISSUE THREAD

**Issue by tdresser** [catapult-project/catapult#3569]
When there's a list of 200 alerts, and I need to select ~100 of them, it would be nice if I could shift-checkmark alerts to select a range.

**Comment by simonhatch** [comment]
@benshayden

**Comment by benshayden** [comment]
[In this demo](https://dev-benjhayden-95d73385-dot-chromeperf.appspot.com/alerts), you can click either the first or last checkbox in the intended range of checkboxes and then shift+click the other endpoint. If you don't click any checkboxes before shift+clicking one, then it starts at the first checkbox in the table, skipping `#header-checkbox`. For each checkbox in the range, it calls onCheckboxChange so that grouped alerts are also selected.

 * Is that behavior correct?
 * This demo doesn't allow unchecking ranges. Should it?
 * Should it allow shift+clicking anywhere in rows instead of only on the checkboxes?
 * Any other missing features?

**Comment by tdresser** [comment]
Behavior LGTM.

Being able to deselect things might be nice, but I don't think it'll be much of an issue in practice. If it becomes one, we can file another bug!

If we were going to do deselection, I'd suggest using a separate key chord - maybe ctrl-shift or alt-shift?

**Comment by anniesullie** [comment]
Sorry for the slow response! I looked at the demo. I think:
* The behavior looks correct to me.
* When I do something complicated, like check 6 boxes, leave 2 blank, check 3 more, leave 4 blank, check another, I no longer know what I would expect shift+click to uncheck; not supporting it is probably easier.
* Shift-clicking anywhere on the row should probably be consistent with clicking anywhere on the row--you can't click elsewhere on the row to check a box, so you can't shift-click either.

So LGTM.
