### ISSUE TITLE
Perf Dashboard: Bisect Button Disabled

### ISSUE THREAD

**Issue by tdresser** [catapult-project/catapult#3570]
I have no idea why the bisect button is disabled here...

![image](https://cloud.githubusercontent.com/assets/470465/26220953/c81af066-3be2-11e7-8904-31cb6792f0ab.png)

https://chromeperf.appspot.com/group_report?bug_id=724032

**Comment by simonhatch** [comment]
There's some logic in bisect-button that compares the revisions to make sure the revision range is valid, but in this case these are git hashes coming through instead of integer commit positions, and it's trying to compare bad_rev > good_rev + 1, which happens to work sometimes with hashes. I'll post a fix.
