### ISSUE TITLE
Perf Dashboard: Bad alerts link, blocking triage

### ISSUE THREAD

**Issue by chcunningham** [catapult-project/catapult#3625]
Chrome version: 58.0.3029.110 (Linux)
URL: https://chromeperf.appspot.com/alerts?sortby=end_revision&sortdirection=down&sheriff=Chromium%20Perf%20AV%20Sheriff

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):
(none)

Please describe the problem:
When I load up the AV Sheriff dashboard I see a bucket of 469 alerts, circled in the screenshot below. 
![image](https://cloud.githubusercontent.com/assets/12039355/26796884/e805b126-49df-11e7-9ccc-82800483ace5.png)

When I attempt to click the revision range to the right of the upward arrow icon for this bucket, I'm taken to the following page:
https://chromeperf.appspot.com/group_report?keys=agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDgxpeHjgkM

Showing these alerts:
![image](https://cloud.githubusercontent.com/assets/12039355/26797009/4ab17b70-49e0-11e7-9417-c1a016887f91.png)

This page's alerts do not seem to correspond to the description on the previous page. Things that do not match include:
1. the count of alerts (no where near 469 advertised)
2. the bot is not win-high-dpi mentioned on the previous page
3. the test is not the same (should be memory:chrome:renderer_processes:reported_by_chrome:partition_alloc:allocated_objects_size_avg/video.html?src_tulip2.wav_type_audio_seek)

Additionally, if I try to graph just a single one of these 469 alerts, I am taken to a page listing these same seemingly unrelated alerts, though this time the link is 
https://chromeperf.appspot.com/group_report?sid=5e98d47d5ad7d9097e036f7377ce8eea45ce3d826bb9b45d89f999e3058967a3

**Comment by chcunningham** [comment]
Update: things still weird, now in different ways. 

My colleague managed to create a bug/start-bisect for the 469 alerts shown in the first AV dashboard screenshot above. In spite of this triage, the dashboard now shows 365 alerts still needing triage.

![image](https://cloud.githubusercontent.com/assets/12039355/26799350/0d0cc96e-49ea-11e7-8a96-98d9fdda4efa.png)

When I click that revision range, I'm now taken to [a page](https://chromeperf.appspot.com/group_report?keys=agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDgxoPHmwoM) showing the original 469 alerts, with all marked as having a bug associated...

![image](https://cloud.githubusercontent.com/assets/12039355/26799442/90926f1e-49ea-11e7-8ff4-4958d4bede70.png)

If the issues truly are triaged (bug associated), they should not show up on the main AV perf dashboard page.

**Comment by chcunningham** [comment]
FYI @crouleau

**Comment by anniesullie** [comment]
@simonhatch

**Comment by chcunningham** [comment]
This morning those 365 alerts are no longer showing up as untriaged in the AV performance dashboard.

**Comment by simonhatch** [comment]
Hi sorry for the lack of response so far, I'm trying to slot in looking at this later in the week.

**Comment by simonhatch** [comment]
So these are my notes from digging into this:

First, differences in the report pages and what they show:
- The little graph icon brings you to /report which only shows you the requested anomalies
- The graph button, or the range links bring you to /group_report, which attempts to show you ALL anomalies that overlap the range of the anomaly you specified.


The alerts page only shows 500 alerts at a time, using this query:
- sheriff, not improvements (unless specified), untriaged (unless specified), ordered by timestamp

The group_report also only allows 500 at a time, using this query:
- sheriff, regressions or improvements, triaged or untriaged, ordering by timestamp

On the backend, the group_report page actually queries for 2000 anomalies at a time, by sheriff and ordered by timestamp, then checking if they overlap with the specified anomaly, then only displays the first 500 found. This is because the query used can't actually directly find anomalies that overlap the range.

So as an experiment, I bumped cap up to 5000 for group_report, managed to find all anomalies (probably?) in the range, a bit less than 1300 (including improvements).

At the time of writing this:

On the /alerts page:
- 365 remained untriaged

On /group_reports:
- found 1240 regressions to display on group_report
- - 875 were already triaged
- - 365 were untriaged


So the numbers line up and I think the weirdness arises from the query caps we put on each page, along with the way we do queries using a desending query on timestamps. Maybe if we could do a better query on the range and get a better sense of how many alerts there actually are out there that overlap this range, the numbers could potentially match up between those 2 pages

On the alerts page, the query can count exactly how many untriaged alerts are left but on group_reports, the query can't actually tell you how many alerts overlap the range, we have to exhaustively search.

This has probably never come up since we don't usually deal with those kind of numbers of alerts. Maybe if we could have the query do an overlap check directly, we'd know how many anomalies there were and could surface that in the UI. We're looking into that for something else (Histogram Pipeline), but we can loop back and do the same thing here.

**Comment by chcunningham** [comment]
Thanks for digging in. I definitely learned some things about what exactly these buttons do. I'll leave it to you to experiment further, but I would add some tidbits

-  that the strangest part of the result for me is when the "graph button" does not actually load a page with graphs for the selected results.

- i don't know what makes media special, but in my AV perf sheriffing its not uncommon for me to see buckets with hundreds of results.

**Comment by benshayden** [comment]
Archiving.
