### ISSUE TITLE
Dashboard - 400 error adding from test-picker

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3633]
/list_tests Failed to load resource: the server responded with a status of 400 ()
jquery.flot.min.js:7 Uncaught Error: Invalid dimensions for plot, width = 0, height = 0
    at Canvas.resize (jquery.flot.min.js:7)
    at Plot.plot.resize (jquery.flot.min.js:7)
    at HTMLElement.resizeGraph (chart-slider.html:402)
Canvas.resize @ jquery.flot.min.js:7
Plot.plot.resize @ jquery.flot.min.js:7
resizeGraph @ chart-slider.html:402
jquery.flot.min.js:7 Uncaught Error: Invalid dimensions for plot, width = 0, height = 0
    at Canvas.resize (jquery.flot.min.js:7)
    at Plot.plot.resize (jquery.flot.min.js:7)
    at HTMLElement.resizeGraph (chart-slider.html:402)

internal.client.v8/x64/v8 / RuntimeStats / Group-Total-V8 / duration

**Comment by benshayden** [comment]
All list_tests 400s that I can find in logs say "path must be a full subtest path in order to select core tests".
https://cs.chromium.org/chromium/src/third_party/catapult/dashboard/dashboard/list_tests.py?q=%22path+must+be+a+full+subtest+path+in+order+to+select+core+tests%22&sq=package:chromium&g=0&l=472

IIUC, this can only happen if users clear the Subtest boxes and click Add, which the UI should prevent, so I'm not sure how this can happen.

Either way, v2spa's descriptors replace list_tests.
