### ISSUE TITLE
"Select all" alerts doesn't work anymore?

### ISSUE THREAD

**Issue by primiano** [catapult-project/catapult#3637]
I am sheriffing and selecting a checkbox for a group doesn't select all the alerts.
![image](https://user-images.githubusercontent.com/7137473/26938008-e5b9ba4c-4c6a-11e7-999a-047234b03694.png)

which sorta suggests that I am going to spend most of my day ticking checkboxes?
I seem to recall that checking the root entry did select all the children, is that broken?

**Comment by simonhatch** [comment]
Hmm, I think if the group is collapsed, clicking on the checkbox ticks them all. I don't recall if the behaviour was different in the past, but checking a nearly month old version, it acts the same way.

Also, @benshayden added shift-select, so you can click on one, and shift select a range, so that should help.

**Comment by primiano** [comment]
Ah, you are right, if I tick before expanding it does what I expect. I was convinced it did that even when they were expanded but it looks like I am wrong.
The shfit-select is super cool, but is also super undiscoverable. Maybe add some tooltip?

Closing this in the meantime
