### ISSUE TITLE
GetDiagnosticsHandler for /get_diagnostics

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3681]
Several features need to be able to query the SparseDiagnostic model from the frontend via a new end point:
- Display SparseDiagnostics on charts #3680 
- Dashboard should support story tags #3494
- Probably others I can't remember right now

Most (all?) of these callers need to be able to query the model with a test path and revision range. Some callers also need to filter by type (TagMap vs Ownership).

Some callers will need to be able to get SparseDiagnostics by guid.

**Comment by benshayden** [comment]
After @hannahtwiggsmith wrote this, I was reviewing it and noticed that, if the test-picker were going to query for TagMap specifically, then SparseDiagnostic should probably index by `type` (soon to be changed to `name` due to splitting Infos into GenericSets #3507 ).

However, indexing by `name` would significantly increase the size and cost of the indices.
Would it? I don't know how to model index cost.

@eakuefner recommends plumbing TagMap through the `test_suites` returned by `/report`, which already contains per-test-suite metadata such as description.
- This would increase the size of the `/report` response by `(average size of TagMap) * (number of benchmarks that have TagMap)`, which could be several dozen KB.
- This would also reduce latency to fetch the TagMap by eliminating the `/get_diagnostics` request, but that latency is usually hidden from the user because the request can be started when the user selects a test suite and would only need to complete by the time the user selects the bot and then the measurement, at which time the story-tag-filter and the Story autocomplete-box appear.

This strategy requires either
A. dependent queries for Diagnostics when building the test suite dict stored object in [_CreateTestSuiteDict](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/update_test_suites.py#L69), which would not require additional storage space but would increase `/report` latency, OR
B. plumbing the TagMap through the test-suite-level TestMetadata entity in `/add_histograms` via `GetOrCreateAncestors`, which would add a single copy of each benchmark's TagMap (which could comprise a few KB, so negligible) to the database.

As for displaying SparseDiagnostics on charts, @eakuefner recommends plumbing them through `/graph_json` so that the frontend doesn't need to make a dependent query to `/get_diagnostics`.

As for a new results2.html-like page, SparseDiagnostics should be queried and returned by `/get_histograms` for the same reason.

So it appears that a `/get_diagnostics` handler is unnecessary.

@simonhatch Do you see any reason to continue with `/get_diagnostics` instead of plumbing TagMap into the test-suite-level TestMetadata?

**Comment by simonhatch** [comment]
Aren't there only a few suite level sparse diagnostics? So querying and getting them is inefficient, but in a super small and not really noticeable way. Additionally, adding a type or name field would increase the size and cost of indices, but again since there's so few of these I can't imagine this will be much. I'd just go with grabbing them all and returning the one you want specifically for now, can add an index later if it becomes an issue.

Plumbing it through test_suites would, I assume, involve caching it as part of the mega-dict from update_test_suites, something we very much want to remove, since we've hit various AppEngine limits (both memory/time) building that thing. The other options is to copy it into TestMetadata, and keeping that in sync whenever TagMap's are uploaded?

I don't really see the tradeoff or benefit here, since (as you mention) the latency is already hidden since the test-picker is busy calling /list_tests anyway. I'd probably just opt for the endpoint for simplicity, and optimize later if it turns into a problem.

**Comment by benshayden** [comment]
After the GenericSet splitting, here are the suite-level SparseDiagnostics:
- tag map
- benchmark name
- owner emails
- bug components
- master
- bot

I think everything else will be time-series-level.

`/get_diagnostics` without indexing by type/name seems like the simplest approach from an API design standpoint, so we can go with it until profiling warrants optimization.

**Comment by hannahtwiggsmith** [comment]
@simonhatch @eakuefner 
Should get_diagnostics return the diagnostics for the test suite as well as the specified test path?

**Comment by simonhatch** [comment]
Maybe it'd be good to enumerate the different places and ways this endpoint will be used?
