### ISSUE TITLE
Perf Dashboard: Associating with Existing Bug fails frequently

### ISSUE THREAD

**Issue by tdresser** [catapult-project/catapult#3684]
I don't have a completely consistent repro, but it happens fairly regularly.

To repro:
* Select ~30 data stoppage alerts.
* Try to associate them with a bug.

They aren't being associated, and I'm receiving the following error:

alerts-table.html:1208 Uncaught TypeError: Cannot read property 'map' of undefined
    at HTMLElement.onTriaged (alerts-table.html:1208)
    at HTMLElement.handler (polymer.html:566)
    at HTMLElement.fire (polymer.html:1343)
    at HTMLElement.<anonymous> (triage-dialog.html:200)

**Comment by tdresser** [comment]
It looks like some of the alerts are being triaged correctly, but others aren't...

**Comment by simonhatch** [comment]
Kinda looks like there's 2 triage-dialogs and they're listening to each other's messages. Will poke at this a bit more after meetings.

**Comment by simonhatch** [comment]
Update: This turned out to be happening slightly deeper, there are multiple triage-dialogs receiving the message that /associate_alerts or whatever is finished, which in turn fire 'triaged' to alerts-table with their checked alerts. This can cause a bunch of weird issues UI side, with alerts in other tables showing the wrong bug ids.

**Comment by simonhatch** [comment]
Another update, we're getting rid of stoppage alerts entirely which will make this a non-issue.

**Comment by simonhatch** [comment]
Closing, original issue was fixed with removal of stoppage alerts and v2 will make it obsolete.
