### ISSUE TITLE
Graphs of different units should be normalized when putting in the same plot

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#3689]
Perf dashboard currently support the use cases of overlaying many graphs of different units in the same plot. This is especially useful for understanding the correlation of different perf data (e.g: temperature & loading speed).

One important question here is "how to determine the right scale?". Perf dashboard currently pick the scale of the first graph in the plot (which seems.. wrong). I propose that we normalize all the graphs to a same scale (mean = 0, std=1) (the same technique that skia uses for clustering graphs of same shape) when they are placed in the same plot. 

@simonhatch @anniesullie @zeptonaut

**Comment by anniesullie** [comment]
@benshayden @eakuefner @simonhatch 

Let's add a concrete example. We want to see if the page load time metric correlates to device temperature. Let's say that page load times are in the range 1200-1500ms and temperature is in the range 25-40C. Right now, we'd have one chart with both lines plotted on it, so it would be hard to see trends. We had discussed changing the units of the axis depending on which was highlighted. 

But ideally we could shift the lines nearer to each other so that it's easier to see how a trend in one relates to the other. Ned's suggestion is to use skia's approach of normalizing the graphs as skia does. In the case of two timeseries that are very far apart, I think this makes sense. I worry that this will get confusing for people trying to compare absolute numbers though, for example looking at how google.com loads compare to cnn.com loads.

**Comment by nedn** [comment]
Annie: agree that if people look at graphs of same units, I think there is little point in trying normalize it. 

Maybe we can make "graph normalization" toggle that user can use & default it to "off" for graphs of same units, and "on" for graphs of different units.

**Comment by zeptonaut** [comment]
I think this ties in to the "make y-axis zero-based" feature that we've been talking about. It seems like if we're comparing graphs of multiple units, we'd pretty much always want to make both axes zero-based.

**Comment by simonhatch** [comment]
I could imagine having customizable options to address Annie's concerns about absolute values, but yeah this sounds similar to the y-axis zero based feature. I think we had some discussion around prioritization of the features that came out of the UI discussion last week, @benshayden maybe can share the notes he had.

**Comment by benshayden** [comment]
v2spa does this.
