### ISSUE TITLE
Add 'IsEmpty' method to GenericSet

### ISSUE THREAD

**Issue by phrmsilva** [catapult-project/catapult#3734]
Following the code review of https://codereview.chromium.org/2977283002 addressing issue #3715, by @eakuefner  we may want a 'IsEmpty' method as syntatic sugar in order to minimize code that repeatedly checks if there are any values in a GenericSet such as `if list(my_generic_set):`

**Comment by sashakruglov** [comment]
I'd like to take this. But is this a right idea?
It looks like you can just go by with `if my_generic_set` which is more "Pythonic".
Under the hood, it should then call `__nonzero__` which is not implemented in this class, and then fallback to `__len__` which is implemented in this class, and then it will be true if `self._values` contain anything and false otherwise.

**Comment by benshayden** [comment]
You're right, thanks!
We can just use `if generic_set` since it implements __len__. We don't need IsEmpty().
