### ISSUE TITLE
Need original story name for Pinpoint

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#3753]
Looks like the dashboard [escapes special characters in story names](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/add_point.py#L457) when it adds points to the datastore. E.g. `http://www.fifa.com/` becomes `http___www.fifa.com_`.

Pinpoint needs the original story name in order to:
* Look up the result in the benchmark output.
* Specify `--story-filter`.

@eakuefner @benshayden @anniesullie @simonhatch

**Comment by anniesullie** [comment]
CL: https://codereview.chromium.org/2993673002

**Comment by anniesullie** [comment]
@eakuefner I have a CL in the CQ for the old `add_point` pipeline, and now I'm looking at how this should work in `add_histograms`.

Currently, instead of doing the escaping that `add_point` does, `add_histograms` always uses `story_display_name` if set:
https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/add_histograms.py#L176

Two questions about this:
1. Will `story_display_name` ever have the `/` character in it? Those would need to be escaped on the dashboard side if so, otherwise they will confuse all our test path logic.
2. Can `story_display_name` always be passed directly into telemetry's `--story-filter` argument? If so, we wouldn't need to store any additional data for pinpoint.

@ashley3 @nedn in case they know the telemetry-side answers.

**Comment by eakuefner** [comment]
I know @ashley3 has been doing some rationalization of how story names work on the Telemetry side, so this may have changed. But, last I recall, a `Page` instance without a custom name (which many of our stories are) would have a URL as its display name and thus have slashes in.

@anniesullie To answer your questions in order:

1. As above, probably, pending Ashley's confirmation. We can do the escaping on the dashboard side to make this work.
2. I'm pretty sure that --story-filter is a regex-based filter. If we do have to do the escaping as described above, then I think we do have to store the unescaped name regardless. An alternative solution here that assumes the histogram pipeline could use the 'stories' `GenericSet` for a given test path, but we'd probably want to discuss with @simonhatch and @benshayden what the right approach is there. For now, I'd say the approach in your CL is appropriate, and with the fix in 1. will work for histograms as well.

**Comment by ashley3** [comment]
All stories are now required to have (custom) names set upon initialization
Many of those stories have URLs as their set names so they do have slashes in it (such as https://cs.chromium.org/chromium/src/tools/perf/page_sets/idle_after_loading_stories.py)

I removed the display_name property from story since it now matches story.name directly. That said, if you need a variation of the name with no slashes, there is a file_safe_name property here: https://cs.chromium.org/chromium/src/third_party/catapult/telemetry/telemetry/story/story.py?q=story.py&dr&l=118

**Comment by nedn** [comment]
Sorry, but I think the fact that dashboard cannot handle "/" in story name is a big problem in itself. This leads to converging names used & understood by dashboard vs by Telemetry benchmark, and we have hacked to make things like bisect per story work.

Is it possible to make perf dashboard be able to take names with special characters like "/", ":" etc..?

**Comment by anniesullie** [comment]
The dashboard can store the original story name. But the entire architecture is based around a concept of a master/bot/benchmark/metric/story hierarchy, which can have varying number of levels. This predates telemetry.

**Comment by dave-2** [comment]
Pinpoint is working fine with Annie's patch, so closing this issue.
It sounds like there's further discussion needed for the story name handling in dashboard. Please open a follow-up issue if so.
