### ISSUE TITLE
[Feature Request] [PerfDashboard] Indicate perf analysis completeness in group report

### ISSUE THREAD

**Issue by eleve11** [catapult-project/catapult#3769]
At the moment if I open a group report of a there is no indication of how much of the analysis has been conducted so far and whether the displayed number of anomalies is complete or not.
For example, I could come back to a report a couple of days later see that there are a bunch of new anomalies that change the overall impact I believed I had.

So I would like to use this indicator to know how confident should I be about the displayed data at a given point in time.

I would also like this value to be retrievable via API

cc: @natorion

**Comment by natorion** [comment]
@eleve11 works on V8 as part of the Cr8er project.

@anniesullie we already talked in the past about exposing bot coverage (% of bots that already passed that particlar revision)

**Comment by anniesullie** [comment]
This is for `/group_report` with the `rev=` parameter? Currently that shows all monitored timeseries for all sheriff rotations. Would it be possible to constrain to one sheriff rotation?

The implementation would look something like:
1. Get a list of monitored timeseries
2. For each timeseries, get `min_segment_size` from alerting config
3. For each timeseries, grab last `min_segment_size` data points.
4. Provide some indicator of how many timeseries aren't yet beyond `rev` in those last data_points.

The problem is that app engine is not great at these type of computations in real time, and caching seems impractical because the use case is all about understanding the current state. @simonhatch any ideas?

**Comment by benshayden** [comment]
Can add_point_queue annotate TestMetadata entries to indicate their completed rev so that GroupReportHandler can query for a count of TestMetadata entries whose completed_rev < rev?

**Comment by simonhatch** [comment]
No, unfortunately touching TestMetadata's is expensive right now.

**Comment by natorion** [comment]
@anniesullie 
Yes this is for /group_report?rev=xxxx, sorry forgot to mention that. Would be very interesting to surface that information there (and also via the related API).

Do you suggest that the coverage is only available if a sheriff rotation is also supplied? AFAIK we don't use that concept on group_report yet, right? Would be confusing. For Cr8er that would also not work because it does not know which rotation you would be interested in. What would work though if one could filter the whole data by sheriff rotation and each rotation has the percentage, but that sounds like more work.

**Comment by anniesullie** [comment]
Right now there are too many monitored timeseries to even list in one dashboard request, so I was thinking of a sheriff rotation as a way to narrow that. Unfortunately, there are also too many to list with large sheriffing rotations like Chromium Perf Sheriff. Not sure a good way to implement this.

**Comment by simonhatch** [comment]
So what does Cr8er need this feature for? How would it be used?

**Comment by natorion** [comment]
By surfacing the bot coverage one can reason about the confidence (?) of the data e.g. if coverage is 5 % and I see no regressions, that doesn't mean anything. On the other hand if coverage is 95 % and I don't see any regression, there probably will not be any negative performance impact.

**Comment by anniesullie** [comment]
I agree surfacing coverage would be really useful! Just can't think of a feasible implementation.

**Comment by natorion** [comment]
Taking a step back: A user simply wants to know if there is already enough coverage to judge the impact. How about a low-tech solution? So, what if instead of surfacing actual percents there are simply three states:

-Red
-Yellow
-Green/Blue/Whatever works for color blind people :-D

Instead of using actual coverage data we probably have the average full cycle time on Chromeperf for CL at hand. Let's assume that is ... 3 days:

-If the commit is less than a day old mark it as red
-If the commit is less than two day old mark it as yellow
-If the commit is more than two days old mark it as green

I suppose we could manually calculate this data and create a good enough model.

**Comment by anniesullie** [comment]
Sure, that works for us. @martiniss and @ehanley324 are working on driving down the cycle time, maybe there is data an app could pull to estimate?

**Comment by mi-ac** [comment]
I assume the color model's time is based on some cycle-time Chromeperf knows or deduces about each time series individually? If we used just the commit time, we wouldn't need Chromeperf for the calculation.

But even with good average cycle-time numbers we get wrong numbers in low traffic times or when a bot is down for a while. E.g. in the evening or in the weekends, there might be few commits only, and the min_segment_size is not reached like on average. We'd report a wrong judgement with the color approach in these situations.

IMO a good tool should always be correct, but can be incomplete. E.g. when the tool claims that performance analysis is complete, but it in fact wasn't, the tool is incorrect (which it should not be IMO). E.g. if the tool claims the performance analysis might not be done, but in fact it was done, the tool is incomplete, which could be tolerated (i.e. it wouldn't be worse than now).

**Comment by natorion** [comment]
Yes. That is the reason why the tool should never claim that there is 100 % coverage. It is something we can't answer with good conscious and the present data. We should keep the precision intentionally low in order to have a higher accuracy.

Sorry if I was not clear enough in my proposal regarding cycle time.

**Comment by benshayden** [comment]
Moved to https://bugs.chromium.org/p/chromium/issues/detail?id=918174
