### ISSUE TITLE
Provide an easy way to rerun a bisect from a "bisect result" code review comment

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#3797]
I've noticed that rerunning a bisect that fails is actually pretty difficult, requiring many clicks and a little bit of expertise on how to kick off bisects in the first place.

It would be _awesome_ if, when a bisect failed and posted a comment into a bug, it provided some link that you could click to either

1) (best) Take you to a page where you can rerun the bisect in one click. Preferably, this page would use the original bisect parameters if the bisect failed entirely, or a narrowed revision range if the bisect was indeed successful at narrowing the revision range before failing
2) (good) Take you to the perf dashboard time series for the bisect that you ran, at least providing you with an easy means to rerun the bisect.

@simonhatch, do you have any idea how hard this would be?

**Comment by anniesullie** [comment]
@dave-2 @perezju 

This sounds similar to some of the ideas we've had for pinpoint. @dave-2 had mentioned he wanted people to be able to get used to pinpoint before adding a ton of UI features. I wonder if this is one of them--instead of "retry entire bisect" maybe you could retry the range in which things failed. I think in some cases you'd really want to "retry with catapult@head".

Thoughts?

**Comment by zeptonaut** [comment]
Agreed. I think that a couple of different options would be really useful, ordered roughly in the order of how useful I think each would be:

- Rerun original bisect
- Rerun bisect with narrowed revision range
- Rerun bisect with custom revision range
- Ability to run each of the above with catapult@`HEAD`. It seems like this should be an orthogonal concept to each of the above.

**Comment by simonhatch** [comment]
1. A page to rerun it wouldn't be that difficult, one idea is that we could potentially just add a link to retry from the buildbucket page to retry with same params. Being able to modify those params would be a bit more work since we'd have to bring up the dialog and all that.

2. Taking you back to the dashboard time-series, again could provide a link in the buildbucket page to /group_report?bug_id=X. I'm not sure how easy it'd be to bring you to the specific time series that was used to kick off the bisect.


And yeah, retry with foo@HEAD is a separate feature all together.

**Comment by zeptonaut** [comment]
I'd love having the first available. Bonus points if the revision range were specified via URL parameters, which I could "copy link", paste, and easily change in the omnibox to match any narrowed ranges that were found.

**Comment by perezju** [comment]
Agree with Annie's comments. Some of these things will probably be quite different in the pinpoint world. For example, rather than "retrying the whole bisect" you might want to try re-run only some specific revisions, or add extra points to the existing bisect on either wider or narrower ranges.

On of the great strengths of pinpoint as it is being designed is that even a "failed" bisect should now contain tons of useful information. I assume we won't be wanting to "retry" as much as "digging further down" when investigating/diagnosing issues.

**Comment by dave-2** [comment]
I echo Annie's comments. I think we can satisfy all those needs, but maybe not in those exact forms.

Failures are handled a little differently in Pinpoint and you will find that retrying a Job is less useful than before. In Pinpoint, "failure" means "Pinpoint fell over", and my first priority is to get these failures down to <0.1%.

In bisects where the test fails in the middle of the range ([example](https://pinpoint-dot-chromeperf.appspot.com/job/12b6783fb80000)), Pinpoint doesn't show a "failure", but instead shows the commits that caused the test to start and stop failing. I agree that we want an option to re-run in that range with a pinned DEP or patch, or even do it automatically.

@perezju also made some good points, hinting at the fact that a Job in Pinpoint is more mutable than a recipe bisect job. If you want to change the range or add or remove points, you can do so without rerunning the entire Job.

I'm also excited about features like #3928, where Pinpoint may expand the range or try different points automatically.

**Comment by zeptonaut** [comment]
SGTM. Going to close this bug because it doesn't sound super applicable in the pinpoint world, and we don't want to invest much more effort into making the non-pinpoint world better given its short remaining lifespan.
