### ISSUE TITLE
Diagnostics for hinting find_anomalies

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3823]
Currently, the chromeperf dashboard detects anomalies (regressions and improvements) in timeseries using a one-size-fits-all statistical algorithm based on the t-test.
However, this algorithm sometimes misses regressions and sometimes incorrectly identifies anomalies. Some metric authors know a better algorithm for detecting regressions.

**Comment by anniesullie** [comment]
Can you list examples of missed regressions? Or better algorithms known by metric authors?

**Comment by benshayden** [comment]
WebVR team mentioned how the DrawFrame measurement in their frame cycle duration metric should never rise above something like 16ms or 8ms so they always hit their target fps consistently. The t-test algorithm might not alert if DrawFrame rises from 15ms to 17ms, but a simple threshold algorithm would.

I seem to recall a request for the ability to manually add alerts to timeseries. Was that from @perezju or @hjd ? Would memory-infra make use of a custom alerting algorithm?

**Comment by perezju** [comment]
I don't think we have in mind using any special alerting algorithm; other than maybe tweaking thresholds on the current one (e.g. ignore regressions under _x_ KiB in some metrics).

What we've mentioned a few times was the ability to be able to manually add alerts to timeseries (e.g. maybe because that timeseries is for an unmonitored submetric; but now we want to keep track of it while investigating some particular issue.)

**Comment by anniesullie** [comment]
A few comments:

* I think configuration about how we alert should all be stored in the [alerting config](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/models/anomaly_config.py). Currently, alerting configs are stored in the datastore and associated to metrics by test path globs. Eventually I think we'll want to check these configs into catapult (with associated names) and have some better way of clearly mapping metrics->configs. I think there will be tons of opinions on how to do that mapping.
* I'm really wary of adding threshold alerting to the perf dashboard. It opens up a lot of edge cases that I don't think we have bandwidth to deal with. Examples:
  * A metric that hovers up and down so that it constantly crosses the 16ms threshold will generate tons of alerts.
  * Most teams end up wishing they had earlier warning when they see jumps. Like if their metric jumps from 14ms to 15ms to 15.999ms, then 3 months later it finally crossed over to 16ms, wouldn't they wish they'd investigated earlier?
  * The actual value of a metric is usually devices-specific (it even varies on the same model/OS config between devices). So just because the lab machine is giving a value of 15.8ms, doesn't mean they're under 16ms in production. A better way to monitor is to collect the metric from end users, and correlate with lab regressions.
* There is a feature request to be able to manually add an alert, but I don't see how it's related to threshold alerting. It's tracked in #1381.

**Comment by perezju** [comment]
+1 Agree with all of that. Particularly the bit about storing alert configs into catapult.
