### ISSUE TITLE
Consider removing support for ns time display mode

### ISSUE THREAD

**Issue by benshayden** [catapult-project/catapult#3831]
Currently, traces can specify whether their timestamps should be displayed in nanoseconds.
However, nsDisplayMode is effectively the same level of detail as msDisplayMode because the former has maximumFractionDigits: 0 and the latter has maximumFractionDigits: 3.
We can use analytics to see how often this mode is used #2121 
[This](https://github.com/catapult-project/catapult/commit/15d5a8e93038e318c50788e9090c9f14dacacc3f) appears to be the change that added this mode. Not helpful.
[This](https://github.com/catapult-project/catapult/commit/0be14c93960cf88f5c0d4086535cb59d831ab194) appears to be the change that allowed traces to specify displayTimeUnit. Not helpful.

**Comment by anniesullie** [comment]
@egonelbre who added the support

**Comment by egonelbre** [comment]
See the bugs linked from the commits:
* https://github.com/catapult-project/catapult/issues/624
* https://github.com/catapult-project/catapult/issues/927

Go uses tracing for [`go tool trace`](https://making.pusher.com/go-tool-trace/) with `ns` precision. It's embedded/vendored from here, so it wouldn't show up in analytics (unless someone opened a go trace from chrome).

As for viewing ns data, seeing "0.00001ms" instead of "10ns" would be pretty bad from usability perspective.

**Comment by benshayden** [comment]
Perfect, thank you!
