### ISSUE TITLE
Trace link is gone from chromeperf dashboard

### ISSUE THREAD

**Issue by primiano** [catapult-project/catapult#3851]
https://chromeperf.appspot.com/report?sid=c02b152d19692fd21b71134119ec81cff17ad50c470fa9f0c191a602bfd8a585

The "Trace" link is no more :/

![image](https://user-images.githubusercontent.com/7137473/30215023-6ce68eae-94a6-11e7-8f23-6706297e5a59.png)

**Comment by anniesullie** [comment]
This is a problem with summary metrics that trips a lot of people up :(

Basically, there are multiple levels of summaries happening here:
1. The individual pages themselves. These have trace links, like this:
https://chromeperf.appspot.com/report?sid=039cf8d6d2e00206c6abd1a26683ecb4d2316de92ceb1b909137d2441dd9785b
2. The categories of page sets, like `background_media`, `browse_news`, etc. You can see these if you click "21 more" in the legend. But these don't have traces, because they're the average of a group of pages.
3. The summary for the entire metric. The chart your looking at, like `system_health.memory_mobile / memory:chrome:all_processes:reported_by_os:system_memory:java_heap:proportional_resident_size_avg`, is a summary, which means it's the average of all the `browse_news`, `background_media`, etc categories from above.

We alert on 1). But people of course find it useful to view the high-level summary, and it's required for filing system health reports. So we keep having graphs of 3), and people keep using them and being confused that they don't show alerts, traces, etc.

@perezju @dave-2 @simonhatch @eakuefner @benshayden have all talked about better solutions here.

Removing P1 since there is a way to get to the traces, it's just awkward from the POV of someone trying to browse metrics.

**Comment by perezju** [comment]
Maybe instead of the "trace link" it should have some text like "Summary of *n* traces."; we could even make that a link that reveals the per-story sparklines.

**Comment by primiano** [comment]
Ahh I even knew about this, I just didn't realize in the rush that was an aggregated metric
# 🤦


As Juan suggested, I think that a simple link / text of the form "Please expand the individual stories for traces" would help a lot.

**Comment by anniesullie** [comment]
@benshayden This should definitely go on your backlog of UI issues.

**Comment by benshayden** [comment]
When histograms are merged across stories before being uploaded to the dashboard, the merged histograms contain all trace urls for all stories. V2spa will display them below charts:
https://bugs.chromium.org/p/chromium/issues/detail?id=865515
