### ISSUE TITLE
Pinpoint - Old values from job-page-change-table linger

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3860]
Repro:

- Click on a point
- Go back to jobs list
- Go to another job

@dave-2

**Comment by dave-2** [comment]
Instead of adding more event handlers and observers to take care of this, I'd like us to be more Polymeric and migrate things over to use more data binding first.

We have two major things that use events instead of data binding:
1. Clicking the points on the graph. Flot is completely event-driven, but I'm working on a d3-based graph which, since it manipulates the DOM, lets us use Polymer components like `<iron-selector>` to do the point selection.
2. Loading page data using `<loading-wrapper>`. Internally, it uses `simple_xhr`, which is event-driven, and we can use `<iron-ajax>` instead, which would also let us remove any front-end dashboard dependencies.
