### ISSUE TITLE
Perf tryjob "Easy" button

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#3883]
Here's the workflow:
* User is on the Job page. There is a Floating Action button with a Forward icon.
* User clicks the FAB and a small dialog opens up with an input box for a Gerrit URL.
* User enters their code review URL and hits "Submit".
*  Pinpoint kicks off a perf tryjob with the current Job config and the latest patchset from that code review.
* Pinpoint redirects the user to the new Job page.

@benshayden

**Comment by anniesullie** [comment]
What's the use case for this? User wants to run with the same benchmark/bot config as the bisect that said their CL was the culprit? If so, we should also make it possible to specify `--extra-chrome-categories` and `--extra-atrace-categories` to telemetry, since that is a major reason for running a tryjob.

**Comment by benshayden** [comment]
Would it be possible to add a link to gerrit so that users don't need to copy-paste urls?

Could pinpoint look through the CL's Bugs to find regressions found by pinpoint, and re-use any configuration from the regression pinpoint job? Maybe it could comment on the CL to say whether it fixes the associated regression?

**Comment by simonhatch** [comment]
So just re-iterating what was discussed in services, think one of the things that we need to look into more deeply is how to get the results2.html if we want to preserve that functionality.

Legacy bisect has access to the command line and runs on the same bot, so it can just use the --results-label and --output-format flags to get telemetry to accumulate and spit out an html results file.

Since Pinpoint is done via swarming, we'd need to gather the chartjson/histograms (later) results from each one, and produce an HTML file somehow. One possibility is to embed a results page that we can just supply with the raw chartjson values from each run, for example. Maybe @benshayden can comment more about what's possible.

**Comment by dave-2** [comment]
@anniesullie Yep. We can do that. Do we have other use cases for perf tryjobs that are not supported by this workflow? E.g. user wants to test their patch before landing. Right now, this is the only planned entry point for perf tryjobs, since we decided to not do the command-line perf tryjobs.

@benshayden Do you mean a link on the CL page in Gerrit instead of a button on the Job page in Pinpoint? So Gerrit would need to embed a Pinpoint endpoint. We would need some way of guessing which Jobs are associated with the regression, which sounds like it could be flaky.

**Comment by anniesullie** [comment]
@dave-2: The other use case I was imagining is a page that's like a simpler version of https://ct.skia.org/ -- users can specify their CL, the benchmark, the bots to run on, the flags to telemetry, etc. They might use it before submission, or just to get data about an idea ("how much memory do we save on android one if we turn off iframes entirely?")

**Comment by dave-2** [comment]
I created a new bug for the results2 discussion, so we can focus this one on "Perf tryjob entry points"

**Comment by anniesullie** [comment]
@nedn - are there ways pinpoint could get a list from telemetry of which benchmarks run on which platforms?

**Comment by nedn** [comment]
Moving forward, a benchmark is either runnable on mobile, or on desktop, or both.

Once @randalnephew finished his disabling migration work, getting that list should be easy.

**Comment by dave-2** [comment]
My original plan was to have another similar FAB on the Jobs listing page.
When you click on the FAB you have two options: "Perf tryjob" and "Bisect job".
Either one pops up a dialog for creating a new job of the respective type.
We need the Jobs page to have some kind of filtering to "show only jobs I care about" so the user can track their jobs.
Does that sound good? I can file bugs for those too.

**Comment by anniesullie** [comment]
About the dialogs, those sound good. The only request I have is that it's a linkable page, so documentation, `run_benchmark try`, etc can point the user to the right place easily.

**Comment by benshayden** [comment]
> Do you mean a link on the CL page in Gerrit instead of a button on the Job page in Pinpoint? So Gerrit would need to embed a Pinpoint endpoint.

Or just a button that posts a form to a pinpoint endpoint? It can be like 10 LoC, doesn't have to be a big thing.

> We would need some way of guessing which Jobs are associated with the regression, which sounds like it could be flaky.

I assumed that pinpoint would do something like update regression bugs with a link to the pinpoint job?
