### ISSUE TITLE
Perf tryjob results2 support.

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#3885]
Splitting off from #3883.

@simonhatch said:

> So just re-iterating what was discussed in services, think one of the things that we need to look into more deeply is how to get the results2.html if we want to preserve that functionality.
> 
> Legacy bisect has access to the command line and runs on the same bot, so it can just use the --results-label and --output-format flags to get telemetry to accumulate and spit out an html results file.
> 
> Since Pinpoint is done via swarming, we'd need to gather the chartjson/histograms (later) results from each one, and produce an HTML file somehow. One possibility is to embed a results page that we can just supply with the raw chartjson values from each run, for example. Maybe @benshayden can comment more about what's possible.

**Comment by benshayden** [comment]
Vulcanizing histograms into results.html currently requires a catapult checkout, but that can be fixed by uploading a results-stub.html when deploying pinpoint. The stub can be checked into catapult if it can't be vulcanized at deploy time for some reason.

Converting chart json to histograms currently requires vinn, but we can translate the converter to python.

Results.html currently cannot be embedded in dashboard pages because tracing UI requires useNativeShadow and dashboard UI requires not useNativeShadow. [Enabling useNativeShadow on the dashboard is complicated](https://codereview.chromium.org/2959503002).

Let's sync up on this in the next services weekly?

**Comment by simonhatch** [comment]
Sounds good, will add an agenda item. It might be ok to just link to a results page rather than embed it directly in Pinpoint, that would at least provide the same level of functionality as recipe bisect.

**Comment by simonhatch** [comment]
This is working, closing out. Bugs etc, can be tracked in separate issues.
