### ISSUE TITLE
[pinpoint] Only record repository info when bisecting into a DEPS roll

### ISSUE THREAD

**Issue by dave-2** [catapult-project/catapult#3921]
Right now, we store repository info for every DEP in every DEPS file that we come across.
So far, we've already encountered name collisions when webrtc and breakpad moved.

If it becomes a chronic problem, we can change `Commit.Deps()` to return a dict or list of strings instead of a list of Commits, so that we only store repository info when we expand a DEPS roll. That would significantly reduce the number of repositories we need to keep track of.

**Comment by dave-2** [comment]
Ok, I think it's often enough to warrant a priority bump. Just got one in a weird repo.

```
Traceback (most recent call last):
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-d787680b.404693255904803368/dashboard/pinpoint/models/job.py", line 192, in Run
    self.state.Explore()
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-d787680b.404693255904803368/dashboard/pinpoint/models/job.py", line 299, in Explore
    midpoint = change_module.Change.Midpoint(change_a, change_b)
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-d787680b.404693255904803368/dashboard/pinpoint/models/change/change.py", line 117, in Midpoint
    commits_midpoint = _FindMidpoints(commits_a, commits_b)
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-d787680b.404693255904803368/dashboard/pinpoint/models/change/change.py", line 200, in _FindMidpoints
    deps_a = commit_a.Deps()
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-d787680b.404693255904803368/dashboard/pinpoint/models/change/commit.py", line 65, in Deps
    add_if_missing=True)
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-d787680b.404693255904803368/dashboard/pinpoint/models/change/repository.py", line 66, in Repository
    return _AddRepository(url)
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-dtu-d787680b.404693255904803368/dashboard/pinpoint/models/change/repository.py", line 87, in _AddRepository
    'Datastore: %s: %s' % (name, url))
AssertionError: Attempted to add a repository that's already in the Datastore: SPIRV-Tools: https://github.com/KhronosGroup/SPIRV-Tools
```

**Comment by dave-2** [comment]
It looks like for this particular one, `chromium/src/DEPS` and `skia/DEPS` pull in the same repo from different locations.

Chromium from the googlesource.com mirror.
https://chromium.googlesource.com/external/github.com/KhronosGroup/SPIRV-Tools

And Skia from Github directly.
https://github.com/KhronosGroup/SPIRV-Tools

**Comment by perezju** [comment]
Deferring the point at which we give names to repositories sgtm. However having sometimes `commit` objects and sometimes `(repository_url, git_hash)` tuples as in [CL](https://chromium-review.googlesource.com/c/catapult/+/804515) I think can be confusing and hinders readability.

My suggestion would be:

* When creating a commit, if a repository URL is not in _URLS_TO_NAMES_KEY, let the URL be their name (and don't add it to the mapping).

* Commit objects can have a, say, "materialize_repository" method that checks and adds if needed a new repository URL to the mapping, and then returns a new commit object with the short name as repository rather than the URL.

So we can deal with repositories as URLs most of the times when doing midpoint computations, and only "materialize" the repository when we know we're likely to put that commit into the datastore e.g. when actually expanding a roll.

Thoughts?

**Comment by dave-2** [comment]
I find that to be more confusing. Then a `Commit` object can have either a repository name or a repository URL. The distinction is even blurrier.

With the above linked CL, the primary change is that `Deps()` no longer returns `Commit` objects. I might even argue that it was confusing for it to return `Commit` objects in the first place, as the DEPS file doesn't contain `Commit` objects.

**Comment by perezju** [comment]
Yes, you are correct. The bit I found annoying was having now to write `deps[0] == repository_url`, it seemed like a step back going from a named tuple to a plain tuple. But named tuples are cheap! Let's just define:

    Dep = collections.namedtuple('Dep', ('repository_url', 'git_hash'))

And have `Deps()` return a frozenset of those. That will make very clear and explicit what the distinction is between what a Dep and a Commit.

I'll leave some comments on the CL.
