### ISSUE TITLE
Unexpected identifier  dispatchAsync

### ISSUE THREAD

**Issue by rmargold** [catapult-project/catapult#3937]
I've built the embedded version of Trace Viewer following this doc: https://github.com/catapult-project/catapult/blob/master/tracing/docs/embedding-trace-viewer.md
Loading this version generates a "Unexpected identifier" JS error on line 4235, column 48, which corresponds to dispatchAsync in event_target.html.

**Comment by benshayden** [comment]
What version of what runtime are you loading it in? (Chrome? Firefox? Node?)
[async/await](http://caniuse.com/#feat=async-functions) is an ES2017 feature.

**Comment by rmargold** [comment]
Chrome 60. 
http://kangax.github.io/compat-table/es2016plus/ says it should support it, but sounds like feature support is the issue. Is there any option to build for browsers that don't support it?
Thank you!

**Comment by benshayden** [comment]
> Is there any option to build for browsers that don't support it?

Sorry, not right now. Can you manually remove the offending method?
If not, it looks like ViewState is the only caller of dispatchSimpleEventAsync which is the only caller of EventTarget.dispatchAsync, so we could temporarily inline those helper functions so that event_target.html doesn't require await. ViewState is only imported by the histogram-set-view, which is imported by the metrics-side-panel and results2_template.html.

I'm still confused why your Chrome 60 doesn't support await when the compat-table says it should, and we've been using it for a while. Can you explain that again?

Also, can you provide more context about what you're trying to do?

**Comment by rmargold** [comment]
So I was going to inline dispatchSimpleEventAsync, but then I realized I might have messed up, and indeed I did. The Chrome version running the code was 47. Looking at the long history of full support of the feature, I'm much better making sure that gets updated, or even ignore it.
Thank you so much for the help!
