### ISSUE TITLE
Perf Dashboard: Are Pinpoint jobs automatically triggered?

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3959]
Chrome version: 62.0.3202.29 (Linux)
URL: https://chromeperf.appspot.com/group_report?bug_id=772703

Please describe the problem:
I noticed this today while triaging some open bugs. It seems Pinpoint jobs are not automatically triggered when a bug for an alert is created. With the old bisection, a bisection was automatically created. Why this change?

**Comment by anniesullie** [comment]
@dave-2 @simonhatch

**Comment by simonhatch** [comment]
They should be, if they're not then that's a bug. I'll take a look since this will probably be dashboard side.

**Comment by simonhatch** [comment]
So looking at this, believe it's a side effect of #3947 . These rows don't have the git hash info since the uploads weren't working properly for a few days, and lot of extra revision info wasn't being uploaded. There's some code duplication going on, which I'll go ahead and clean up but this shouldn't be an issue outside of that upload problem window.

**Comment by simonhatch** [comment]
Should be fixed, reopen if it happens again.
