### ISSUE TITLE
Perf Dashboard: Subtest not showing all its subtests

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3967]
Chrome version: 62.0.3202.45 (Linux)
URL: https://chromeperf.appspot.com/report?sid=3836adf633ca2e5d9aae5063a1311543a95b023badb484cd80de96f92fba1a29

Please describe the problem:
See above URL. The subtest "browse_news_reddit" is below "browse_news". It does not appear though if I simply add "browse_news" to the graph.

![image](https://user-images.githubusercontent.com/7190422/31435345-8ce0ec34-ae7f-11e7-8f10-96405946f714.png)

**Comment by anniesullie** [comment]
@benshayden @simonhatch

**Comment by simonhatch** [comment]
These tests have been marked deprecated (no data received since Sept 2), and are filtered out when getting the graph data. The test-picker still allows you to choose them, but they're not included when you select the top level metric.

We could see about surfacing this better, either through the chart legend or test picker itself?

**Comment by natorion** [comment]
probably both. There is already a similar functionality in the test picker for tests and benchmarks. It is "simply" missing for subtests.

The same information probably should be displayed on the chart if there is any meta information like this.

**Comment by benshayden** [comment]
V2spa descriptors filter test cases the same as measurements and bots.
