### ISSUE TITLE
Pinpoint - Revisit perf try job repository params

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4007]
Right now they're hardcoded to chromium for perf try jobs, not sure how we want to select these for "easy" perf try jobs? Based on the initial 2 points? The patch? Add a dropdown?

@dave-2

**Comment by dave-2** [comment]
Maybe by looking up the builder name, which we get from looking up the bot (`configuration`) name. Since each builder is hard-coded to a particular repository.

**Comment by perezju** [comment]
I've probably asked this already, but I'm still a bit confused. Is this about the "Test a patch" button when looking at specific job? What does this button actually do? And what is the difference between this and the "Run a try job" button at the main (jobs) page?

**Comment by dave-2** [comment]
The bug description is confusing because it says it's about the "test a patch" button, but with that button you should be able to just copy the params from the parent job. I think it's more about the "run a try job" button on the main jobs page.

The "test a patch" button is for "this bisect blamed my CL, how do I run with a patch or revert to see if that fixes it?" It copies the old job's params into the new job. And the "run a try job" button is for generally seeing the impact of a CL without a specific metric in mind, where all the params are created from scratch.

**Comment by perezju** [comment]
Ok, so:

* "Run a try job" runs ToT vs (ToT + patch) and the user will probably want to see the results.html comparing all metrics between the two. Your CL to infer the repository is for this case, to figure out whether "ToT" means e.g. clank ToT or chromium ToT.

* "Test a patch" also runs ToT vs (ToT + patch), but the results graph will highlight the particular metric that triggered the alert and used for the bisect. (And whether ToT is clank or chromium is inherited from the bisect job.)

Did I get that right?

**Comment by dave-2** [comment]
Yep!

**Comment by perezju** [comment]
Got it. Thanks! I wonder whether these could be condensed into some short crisp descriptions to show below the title under each of these two dialog boxes?
