### ISSUE TITLE
Histogram Pipeline - Seeing lots of failures in /add_histogram_queue over missing guid

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4015]
Looks like some diagnostics that are expected to be sparse, aren't?

Specifically from log:

<snippet>
  "diagnostics": {
   "masters": "37b9d2b6-6cbf-4323-b6c1-57918a5e17f6", 
   "builds": "b6176d04-f5f0-456f-8abf-2d35ebd93ed7", 
   "benchmarkStart": {
    "type": "DateRange", 
    "min": 1509565701739
   }, 
   "chromiumCommitPositions": "698608a0-b3ee-4b01-aa05-5f5f906c385a", 
   "owners": "776189ed-b1ff-43d6-9cee-324411d9a32a", 
   "osVersions": "b56580c7-911c-4f6e-8c39-87a0ad761d3f", 
   "isReferenceBuild": "e598924c-ff70-410d-ac7e-3e81acdf9460", 
   "chromiumRevisions": "63aebb4c-5633-4546-8bd7-fce18d94f81e", 
   "stories": {
    "type": "GenericSet", 
    "values": [
     "dummy_page.html"
    ]
   }, 
   "osNames": "a3c674e9-0b8c-4b92-9d74-b225202fd8e4", 
   "benchmarks": "9b395dfd-166d-4313-92ec-b50ea1a34585", 
   "memoryAmounts": "ef53f877-c2e2-46d7-84f5-08738e416732", 
   "bots": "ac904c9e-ae39-4f0d-91c1-26a0088266a3", 
   "architectures": "1fed4aeb-7b35-4724-8ee2-530c0cf54f3b"
  }, 

"stories" is expected to be sparse, but looks inlined.

@benshayden @eakuefner

**Comment by simonhatch** [comment]
So running blink_perf.events with histogram output has the stories diagnostic as a sparse diagnostic, as expected. So guessing this is something telemetry is doing?

Ben, can you take a look?

**Comment by benshayden** [comment]
Looking

**Comment by benshayden** [comment]
TBMv2's metric map function adds stories as a shared diagnostic, but the dummy benchmarks don't use TBMv2, so they're running telemetry Values through ChartJsonConverter, which does not use shared diagnostics.
Again, this problem would not affect metrics that produce more than 1 Value because deduplicateDiagnostics would share them.
I'll make ChartJsonConverter add shared diagnostics. This will make it a bit more complicated, but will make it behave more like TBMv2.

**Comment by simonhatch** [comment]
Can this be closed out?

**Comment by eakuefner** [comment]
Yup, fixed as of Catapult roll a while ago.
