### ISSUE TITLE
Perf Dashboard: Pinpoint "Analyze Benchmark Results" button doesn't work.

### ISSUE THREAD

**Issue by tdresser** [catapult-project/catapult#4035]
Pinpoint "Analyze Benchmark Results" button doesn't work.

**Comment by dave-2** [comment]
The URL is correct; if you refresh the page, it loads. I think this is because it uses client-side routing, and this particular page is generated from the server side.

Easiest thing is to load it with `target="_blank"`. It also might be right from the UI perspective, because results2 / histograms viewer may become a separate service.

**Comment by dave-2** [comment]
Deployed!
