### ISSUE TITLE
/add_histograms_queue: datastore contention

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#4087]
We occasionally see a bit of datastore contention in add_histograms_queue; we suspect this is to do with histogram-level sparse diagnostics and trying to put the same one many times.

There are a number of approaches we could take here, like maybe just storing sets of histogram-level sparse diagnostics and querying for "all sparse diagnostics between A and B" instead of trying to filter by type, or "un-deduplicating" (normalization) where we store a copy per histogram.

**Comment by simonhatch** [comment]
So just confirming that this is what's happening, a lot of the histogram level diagnostics are shared at the moment across the entire benchmark. Since they can potentially vary from histogram to histogram, we probably don't want to promote them to suite level. Possible solutions:

- 'Unique' them, in that for each histogram, clone all the diagnostics into new ones with new guids. Downside here is that we use a bit more storage.
- Write them out separately from the histograms. Downside is complexity in implementation, this requires deduplicating them all first, before patching histograms.

I'd favour the first option.

On top of that, we can simplify things a bit by storing all the diagnostics together as a single SparseDiagnostic instead of separately, both at the histogram and suite levels. Cuts down on # entities we need to keep track of.
