### ISSUE TITLE
Accommodate out-of-order uploads when deduplicating sparse diagnostics

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#4094]
We don't currently do this, but Cros uploads points out of order and V8 wants to as well, so when they switch to the histogram pipeline we'll have to make sure to take that into account.

**Comment by simonhatch** [comment]
We also need to fix up the diagnostics when you do a test migration, since you can migrate one test onto another.

An easy fix that I wrote up on the plane would be to just write a FixDiagnostics function that queries for all the diagnostics for a test_path, sorts them by start_revision, deletes any non-unique ones, fixes up the end_revisions for all of them, and puts() them back. Migration can just call that. Potentially be used by /add_histograms as well, if the revision is < latest diagnostics start_point, just do a full fixup. Most out of order points would still avoid the call since these are sparse.
