### ISSUE TITLE
Dashboard - /add_histograms must handle duplicate histograms

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4122]
What's the expected behaviour, should 2 histograms resolve to the same test_path coming out of add_reserved_diagnostics? Right now that seems to happen.

@eakuefner

**Comment by simonhatch** [comment]
I tried on 2, media.desktop and kraken, saw duplicates on both.

**Comment by benshayden** [comment]
Can you link to a specific json file? I might be able to diagnose the issue from that.

**Comment by simonhatch** [comment]
Logging revealed it's still happening on media.desktop (only that one it seems). Will investigate.

**Comment by eakuefner** [comment]
@benshayden From investigating the media.desktop JSON, I think I've narrowed the problem down to we're grouping by storyTags https://github.com/catapult-project/catapult/blob/3b3f9e1e789dbed2726dcd3c97d9dcd080ca7f23/tracing/bin/add_reserved_diagnostics#L56 which I don't think we should be doing at all.

You wrote the original code, so I'm wondering if you can recall the rationale. If we look at the media.desktop results from bots that are uploading chartjson, e.g. https://chromeperf.appspot.com/report?sid=5fbf9c4f8a6a6068fa4e459410ac2ef8fdc9c6ba8264a99e4674039418bccc1c we see that the test hierarchy doesn't consider tags at all.

It seems like this might have been intended to cover a case where we have the same story name but different tags, but Telemetry enforces that all story names should be unique regardless of tags, so I think there is no need to consider tags when merging for the dashboard. If we do consider tags, then we end up with multiple summaries, per tag set, that have the same test path, which we don't want.

@simonhatch wondered about a more foolproof algorithm where we actually compute test paths first and then merge based on that (i.e. rather than using the very general, designed-for-results2 merging functionality of HistogramSet), though I'd like to just make sure if I understand the root cause first.

**Comment by simonhatch** [comment]
Confirmed that with the change to remove storyTags, we're not getting duplicate histogram warnings now.

**Comment by eakuefner** [comment]
Great, can you stamp https://chromium-review.googlesource.com/c/catapult/+/843417 and we'll get the fix on master? This bug will automatically close when it lands.
