### ISSUE TITLE
Clean up dashboard-side stat filtering functionality

### ISSUE THREAD

**Issue by eakuefner** [catapult-project/catapult#4213]
We should clean up dashboard-side stat filtering functionality either when @benshayden devises a better approach for handling the two different summary stats use cases on the TBMv2 side, or if we figure out that /add_point can sustain the additional load.

@simonhatch

**Comment by benshayden** [comment]
The two uses of Histogram.summaryOptions are currently
 * results.html histogram-span's scalar-map-table when cells are open, and
 * metricMapFunction generates the scalars that Telemetry turns into Values that are uploaded to add_point in chartjson.

The HistogramPipeline will eventually remove the second use: instead of creating one test-path per statistic, add_histograms will create one test-path per Histogram. V2SPA contains a statistic picker to allow users to choose which statistic to plot, default to 'avg'. (Maybe some custom logic could automatically switch to median or another statistic for specific measurements, etc.)

V2SPA also contains a histogram-span, so I suspect that summaryOptions will eventually be nothing but an optional display-level hint to the histogram-span (in both V2SPA and results.html), instead of the architectural feature that it is today.

**Comment by benshayden** [comment]
Moved to https://bugs.chromium.org/p/chromium/issues/detail?id=918188
