### ISSUE TITLE
Dashboard alerts should store reference to their bisects

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#4216]
It would be really helpful to be able to see which bisects correspond to each individual alert:

  * In the UI, for making it easy to see which timeseries have been bisected and what the results were.
  * In the API, for long-term tracking of bisect results for bot/metric/page etc.

I think this would be implemented with a `KeyProperty` that refers to a pinpoint `Job` (or the deprecated-bisect equivalent) but any implementation that can be agreed upon is fine with me.

@dave-2 @simonhatch

**Comment by simonhatch** [comment]
So I think plumbing through the alert ids to the bisect/pinpoint dialogs is pretty straightforward.

A note about storing them, since we've up until now kept Pinpoint at arm's length and treated it as another service, if we want to keep doing that then we only store the string id that's returned from creating the job.
