### ISSUE TITLE
Dashboard - Hitting exception accessing /report for suites with histogram data

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4237]
```
test-picker.html:125 Uncaught (in promise) ReferenceError: diagnostics is not defined
    at TagMapCache.process_ (test-picker.html:125)
    at <anonymous>
```

**Comment by eakuefner** [comment]
I'm not seeing this. The picker does trigger a lot of 400s to /get_diagnostics in my testing. Can you give a report URL?

**Comment by eakuefner** [comment]
Okay, in any case, the 400s are at least part of the problem. Looking at the code, we try to look at the length property no matter whether the XHR to /get_diagnostics succeeds. Also curious why we're getting 400s in /get_diagnostics, so that's worth looking into also.

I'll take ownership of this bug, and look into these two things.

**Comment by simonhatch** [comment]
Just pick anything with a histogram source, ie. histogram-diff-histograms-3

I already fixed it btw
