### ISSUE TITLE
We need to update the terminology in the monitoring request bug template

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#4480]
Right now it asks for:
* Buildbot master name
  * These don't even exist anymore with the luci migration. But I think we'll have some kind of grouping of bots long term.
* Test Suite names
  * This should probably say benchmarks
* Restrict to traces
  * This is asking for the rest of the test path after the benchmark name. It uses a super old term that predates the perf dashboard or chrome tracing.

@benshayden what would the form look like using the terms we use in v2 spa?
@simonhatch @eakuefner @perezju This should probably work well with @simonhatch's proposal to change monitoring configurations.

**Comment by benshayden** [comment]
V2SPA describes timeseries using these terms:
 * Test suite
 * Bot (includes "master" or whatever, separated by colons, e.g. `ChromiumPerf:macbook-air11`)
 * Measurement
 * Test case
 * Statistic
 * build type (generalization of "test" vs "ref"; I imagine only test builds should be monitored so this can be left off this form)

Instead of "buildbot master name", the form could ask for "Bot prefix" or "Bot name pattern (e.g. `ChromiumPerf:*`)".

I think the term "test case" (as a replacement for and generalization of "trace" or "page" or "story") maps well to other types of tests like functional test cases, and so "test suite" seems to make more sense than "benchmark" even though most users refer to benchmarks. "Test suite" doesn't seem to confuse users too much, in my experience, but I'm open to using "benchmarks" if there's a strong opinion.

**Comment by perezju** [comment]
For what it's worth. We've been using the same v2spa terminology that Ben just listed when coding in soundwave, and I believe that has worked pretty well in keeping things readable and understandable.

**Comment by benshayden** [comment]
This looks done pending deployment.
