### ISSUE TITLE
[📍] Pinpoint apparently can't find isolate hashes of completed builds

### ISSUE THREAD

**Issue by gburgessiv** [catapult-project/catapult#4481]
Hi! I've been getting this error for the last ~day trying to run speedometer on the linux bots. All I have to go off of is a Python stack from mousing over "Error." The exception message is: "Buildbucket says the build completed successfully, but pinpoint can't find the isolate hash"

Links to failed runs:

https://pinpoint-dot-chromeperf.appspot.com/job/14f2a942240000
https://pinpoint-dot-chromeperf.appspot.com/job/12c945ec240000
https://pinpoint-dot-chromeperf.appspot.com/job/14c63d2c240000
https://pinpoint-dot-chromeperf.appspot.com/job/14bd4702240000
https://pinpoint-dot-chromeperf.appspot.com/job/16a9afec240000
https://pinpoint-dot-chromeperf.appspot.com/job/12813702240000

Thank you!

**Comment by camillobruni** [comment]
Got the same issue on an Android build:
https://pinpoint-dot-chromeperf.appspot.com/job/1682316c240000

**Comment by benshayden** [comment]
@dave-2

**Comment by gburgessiv** [comment]
Looks like this is still failing: https://pinpoint-dot-chromeperf.appspot.com/job/11f7285a240000 :/

**Comment by dave-2** [comment]
Sorry about that! This is because of a configuration change on the perf waterfall (See: [chromium issue 836037](https://bugs.chromium.org/p/chromium/issues/detail?id=836037#c7))
I deployed a fix for this last week, but because the configuration changed, re-running the failed jobs won't work, since they will retain the old (now incorrect) configuration. Please try kicking off a new job instead, and let me know if that still doesn't work!

**Comment by gburgessiv** [comment]
No worries! Looks like [making a new job worked](https://pinpoint-dot-chromeperf.appspot.com/job/12e7d806240000), so I'll close this. Thanks again
