### ISSUE TITLE
Perf Dashboard 1 & 2 disagree on number of alerts

### ISSUE THREAD

**Issue by tdresser** [catapult-project/catapult#4542]
Right now V1 says 1097 alerts (*sigh*) and V2 says 497 alerts.

**Comment by tdresser** [comment]
They seem to agree now that the number is < 500.

**Comment by benshayden** [comment]
Thanks for reporting and apologies for the delay.
This is currently somewhat expected.
V1 runs a single query for all untriaged alerts with limit=5000. V2 runs a single query for *all* alerts with limit=2000 in order to group and display triaged alerts alongside untriaged alerts. V2 gets the 2000 most recent alerts regardless of whether they're triaged. All alerts queries sort by timestamp descending so they get more recent alerts first.
The fix for V2 is to make it chase cursors (loading alerts progressively) until it finds the earliest untriaged alert, and possibly a few more even earlier alerts. That logic is already in the master branch, so I'll merge it to the v2spa branch at some point.

**Comment by benshayden** [comment]
The alerts-section in the master branch chases cursors, so I just need to merge that code into the v2spa branch and re-deploy, which will probably be done within a week or two.
