### ISSUE TITLE
Include p-value (t-statistic?) on results page.

### ISSUE THREAD

**Issue by bfgeek** [catapult-project/catapult#4609]
One thing I've noticed folks doing is "p-hacking" results sometimes, or relying on an intuition of which tests matter in a particular benchmark suite, or performing multiple runs of a benchmark to get a better signal out of a benchmark.

It'd might be helpful if on the results page there was an additional column with a p-value (based on t-stat?) 🤷‍♂️

**Comment by benshayden** [comment]
When a [reference column is selected](https://github.com/catapult-project/catapult/blob/master/docs/metrics-results-ui.md#the-reference-column-selector), open cells display a p-value indicating (warning, approximate statistical language ahead) the probability that the cell is indistinguishable from the reference cell (same row, reference column). I'm not sure if that's the p-value you might be looking for?

I think that running the same benchmark multiple times, or passing --pageset-repeat to run_benchmark, is a valid way to strengthen the signal, right?

The best way to combat p-hacking that I've found so far is to educate users on how to avoid it. Every results.html links to the [doc](https://github.com/catapult-project/catapult/blob/master/docs/metrics-results-ui.md#significance), where I've tried to explain statistical significance as best I can without taking a year off to write a textbook, but patches are always welcome, either for results.html or the doc.

I'm going to close this since we're moving to monorail.
[This bug](https://bugs.chromium.org/p/chromium/issues/detail?id=908893&desc=4) and the [tbm2 component](https://bugs.chromium.org/p/chromium/issues/list?q=component:Speed%3ETBM2) might be relevant. Please feel free to comment there or file a new crbug.
